// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ed-evo/hankinson/server/ent/argomento"
)

// Argomento is the model entity for the Argomento schema.
type Argomento struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Nome holds the value of the "nome" field.
	Nome string `json:"nome,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArgomentoQuery when eager-loading is set.
	Edges        ArgomentoEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ArgomentoEdges holds the relations/edges for other nodes in the graph.
type ArgomentoEdges struct {
	// Domande holds the value of the domande edge.
	Domande []*Domanda `json:"domande,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DomandeOrErr returns the Domande value or an error if the edge
// was not loaded in eager-loading.
func (e ArgomentoEdges) DomandeOrErr() ([]*Domanda, error) {
	if e.loadedTypes[0] {
		return e.Domande, nil
	}
	return nil, &NotLoadedError{edge: "domande"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Argomento) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case argomento.FieldID:
			values[i] = new(sql.NullInt64)
		case argomento.FieldNome:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Argomento fields.
func (_m *Argomento) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case argomento.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case argomento.FieldNome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nome", values[i])
			} else if value.Valid {
				_m.Nome = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Argomento.
// This includes values selected through modifiers, order, etc.
func (_m *Argomento) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDomande queries the "domande" edge of the Argomento entity.
func (_m *Argomento) QueryDomande() *DomandaQuery {
	return NewArgomentoClient(_m.config).QueryDomande(_m)
}

// Update returns a builder for updating this Argomento.
// Note that you need to call Argomento.Unwrap() before calling this method if this Argomento
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Argomento) Update() *ArgomentoUpdateOne {
	return NewArgomentoClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Argomento entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Argomento) Unwrap() *Argomento {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Argomento is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Argomento) String() string {
	var builder strings.Builder
	builder.WriteString("Argomento(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("nome=")
	builder.WriteString(_m.Nome)
	builder.WriteByte(')')
	return builder.String()
}

// Argomentos is a parsable slice of Argomento.
type Argomentos []*Argomento
