// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ed-evo/hankinson/server/ent/argomento"
	"github.com/ed-evo/hankinson/server/ent/domanda"
)

// ArgomentoCreate is the builder for creating a Argomento entity.
type ArgomentoCreate struct {
	config
	mutation *ArgomentoMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNome sets the "nome" field.
func (_c *ArgomentoCreate) SetNome(v string) *ArgomentoCreate {
	_c.mutation.SetNome(v)
	return _c
}

// AddDomandeIDs adds the "domande" edge to the Domanda entity by IDs.
func (_c *ArgomentoCreate) AddDomandeIDs(ids ...int) *ArgomentoCreate {
	_c.mutation.AddDomandeIDs(ids...)
	return _c
}

// AddDomande adds the "domande" edges to the Domanda entity.
func (_c *ArgomentoCreate) AddDomande(v ...*Domanda) *ArgomentoCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDomandeIDs(ids...)
}

// Mutation returns the ArgomentoMutation object of the builder.
func (_c *ArgomentoCreate) Mutation() *ArgomentoMutation {
	return _c.mutation
}

// Save creates the Argomento in the database.
func (_c *ArgomentoCreate) Save(ctx context.Context) (*Argomento, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ArgomentoCreate) SaveX(ctx context.Context) *Argomento {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArgomentoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArgomentoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ArgomentoCreate) check() error {
	if _, ok := _c.mutation.Nome(); !ok {
		return &ValidationError{Name: "nome", err: errors.New(`ent: missing required field "Argomento.nome"`)}
	}
	if v, ok := _c.mutation.Nome(); ok {
		if err := argomento.NomeValidator(v); err != nil {
			return &ValidationError{Name: "nome", err: fmt.Errorf(`ent: validator failed for field "Argomento.nome": %w`, err)}
		}
	}
	return nil
}

func (_c *ArgomentoCreate) sqlSave(ctx context.Context) (*Argomento, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ArgomentoCreate) createSpec() (*Argomento, *sqlgraph.CreateSpec) {
	var (
		_node = &Argomento{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(argomento.Table, sqlgraph.NewFieldSpec(argomento.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Nome(); ok {
		_spec.SetField(argomento.FieldNome, field.TypeString, value)
		_node.Nome = value
	}
	if nodes := _c.mutation.DomandeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   argomento.DomandeTable,
			Columns: argomento.DomandePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Argomento.Create().
//		SetNome(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArgomentoUpsert) {
//			SetNome(v+v).
//		}).
//		Exec(ctx)
func (_c *ArgomentoCreate) OnConflict(opts ...sql.ConflictOption) *ArgomentoUpsertOne {
	_c.conflict = opts
	return &ArgomentoUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Argomento.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ArgomentoCreate) OnConflictColumns(columns ...string) *ArgomentoUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ArgomentoUpsertOne{
		create: _c,
	}
}

type (
	// ArgomentoUpsertOne is the builder for "upsert"-ing
	//  one Argomento node.
	ArgomentoUpsertOne struct {
		create *ArgomentoCreate
	}

	// ArgomentoUpsert is the "OnConflict" setter.
	ArgomentoUpsert struct {
		*sql.UpdateSet
	}
)

// SetNome sets the "nome" field.
func (u *ArgomentoUpsert) SetNome(v string) *ArgomentoUpsert {
	u.Set(argomento.FieldNome, v)
	return u
}

// UpdateNome sets the "nome" field to the value that was provided on create.
func (u *ArgomentoUpsert) UpdateNome() *ArgomentoUpsert {
	u.SetExcluded(argomento.FieldNome)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Argomento.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ArgomentoUpsertOne) UpdateNewValues() *ArgomentoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Argomento.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ArgomentoUpsertOne) Ignore() *ArgomentoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArgomentoUpsertOne) DoNothing() *ArgomentoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArgomentoCreate.OnConflict
// documentation for more info.
func (u *ArgomentoUpsertOne) Update(set func(*ArgomentoUpsert)) *ArgomentoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArgomentoUpsert{UpdateSet: update})
	}))
	return u
}

// SetNome sets the "nome" field.
func (u *ArgomentoUpsertOne) SetNome(v string) *ArgomentoUpsertOne {
	return u.Update(func(s *ArgomentoUpsert) {
		s.SetNome(v)
	})
}

// UpdateNome sets the "nome" field to the value that was provided on create.
func (u *ArgomentoUpsertOne) UpdateNome() *ArgomentoUpsertOne {
	return u.Update(func(s *ArgomentoUpsert) {
		s.UpdateNome()
	})
}

// Exec executes the query.
func (u *ArgomentoUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArgomentoCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArgomentoUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ArgomentoUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ArgomentoUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ArgomentoCreateBulk is the builder for creating many Argomento entities in bulk.
type ArgomentoCreateBulk struct {
	config
	err      error
	builders []*ArgomentoCreate
	conflict []sql.ConflictOption
}

// Save creates the Argomento entities in the database.
func (_c *ArgomentoCreateBulk) Save(ctx context.Context) ([]*Argomento, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Argomento, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArgomentoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ArgomentoCreateBulk) SaveX(ctx context.Context) []*Argomento {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArgomentoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArgomentoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Argomento.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArgomentoUpsert) {
//			SetNome(v+v).
//		}).
//		Exec(ctx)
func (_c *ArgomentoCreateBulk) OnConflict(opts ...sql.ConflictOption) *ArgomentoUpsertBulk {
	_c.conflict = opts
	return &ArgomentoUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Argomento.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ArgomentoCreateBulk) OnConflictColumns(columns ...string) *ArgomentoUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ArgomentoUpsertBulk{
		create: _c,
	}
}

// ArgomentoUpsertBulk is the builder for "upsert"-ing
// a bulk of Argomento nodes.
type ArgomentoUpsertBulk struct {
	create *ArgomentoCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Argomento.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ArgomentoUpsertBulk) UpdateNewValues() *ArgomentoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Argomento.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ArgomentoUpsertBulk) Ignore() *ArgomentoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArgomentoUpsertBulk) DoNothing() *ArgomentoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArgomentoCreateBulk.OnConflict
// documentation for more info.
func (u *ArgomentoUpsertBulk) Update(set func(*ArgomentoUpsert)) *ArgomentoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArgomentoUpsert{UpdateSet: update})
	}))
	return u
}

// SetNome sets the "nome" field.
func (u *ArgomentoUpsertBulk) SetNome(v string) *ArgomentoUpsertBulk {
	return u.Update(func(s *ArgomentoUpsert) {
		s.SetNome(v)
	})
}

// UpdateNome sets the "nome" field to the value that was provided on create.
func (u *ArgomentoUpsertBulk) UpdateNome() *ArgomentoUpsertBulk {
	return u.Update(func(s *ArgomentoUpsert) {
		s.UpdateNome()
	})
}

// Exec executes the query.
func (u *ArgomentoUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ArgomentoCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArgomentoCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArgomentoUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
