// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ed-evo/hankinson/server/ent/argomento"
	"github.com/ed-evo/hankinson/server/ent/domanda"
	"github.com/ed-evo/hankinson/server/ent/predicate"
)

// ArgomentoUpdate is the builder for updating Argomento entities.
type ArgomentoUpdate struct {
	config
	hooks    []Hook
	mutation *ArgomentoMutation
}

// Where appends a list predicates to the ArgomentoUpdate builder.
func (_u *ArgomentoUpdate) Where(ps ...predicate.Argomento) *ArgomentoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNome sets the "nome" field.
func (_u *ArgomentoUpdate) SetNome(v string) *ArgomentoUpdate {
	_u.mutation.SetNome(v)
	return _u
}

// SetNillableNome sets the "nome" field if the given value is not nil.
func (_u *ArgomentoUpdate) SetNillableNome(v *string) *ArgomentoUpdate {
	if v != nil {
		_u.SetNome(*v)
	}
	return _u
}

// AddDomandeIDs adds the "domande" edge to the Domanda entity by IDs.
func (_u *ArgomentoUpdate) AddDomandeIDs(ids ...int) *ArgomentoUpdate {
	_u.mutation.AddDomandeIDs(ids...)
	return _u
}

// AddDomande adds the "domande" edges to the Domanda entity.
func (_u *ArgomentoUpdate) AddDomande(v ...*Domanda) *ArgomentoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDomandeIDs(ids...)
}

// Mutation returns the ArgomentoMutation object of the builder.
func (_u *ArgomentoUpdate) Mutation() *ArgomentoMutation {
	return _u.mutation
}

// ClearDomande clears all "domande" edges to the Domanda entity.
func (_u *ArgomentoUpdate) ClearDomande() *ArgomentoUpdate {
	_u.mutation.ClearDomande()
	return _u
}

// RemoveDomandeIDs removes the "domande" edge to Domanda entities by IDs.
func (_u *ArgomentoUpdate) RemoveDomandeIDs(ids ...int) *ArgomentoUpdate {
	_u.mutation.RemoveDomandeIDs(ids...)
	return _u
}

// RemoveDomande removes "domande" edges to Domanda entities.
func (_u *ArgomentoUpdate) RemoveDomande(v ...*Domanda) *ArgomentoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDomandeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArgomentoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArgomentoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArgomentoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArgomentoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArgomentoUpdate) check() error {
	if v, ok := _u.mutation.Nome(); ok {
		if err := argomento.NomeValidator(v); err != nil {
			return &ValidationError{Name: "nome", err: fmt.Errorf(`ent: validator failed for field "Argomento.nome": %w`, err)}
		}
	}
	return nil
}

func (_u *ArgomentoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(argomento.Table, argomento.Columns, sqlgraph.NewFieldSpec(argomento.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nome(); ok {
		_spec.SetField(argomento.FieldNome, field.TypeString, value)
	}
	if _u.mutation.DomandeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   argomento.DomandeTable,
			Columns: argomento.DomandePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDomandeIDs(); len(nodes) > 0 && !_u.mutation.DomandeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   argomento.DomandeTable,
			Columns: argomento.DomandePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomandeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   argomento.DomandeTable,
			Columns: argomento.DomandePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{argomento.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArgomentoUpdateOne is the builder for updating a single Argomento entity.
type ArgomentoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArgomentoMutation
}

// SetNome sets the "nome" field.
func (_u *ArgomentoUpdateOne) SetNome(v string) *ArgomentoUpdateOne {
	_u.mutation.SetNome(v)
	return _u
}

// SetNillableNome sets the "nome" field if the given value is not nil.
func (_u *ArgomentoUpdateOne) SetNillableNome(v *string) *ArgomentoUpdateOne {
	if v != nil {
		_u.SetNome(*v)
	}
	return _u
}

// AddDomandeIDs adds the "domande" edge to the Domanda entity by IDs.
func (_u *ArgomentoUpdateOne) AddDomandeIDs(ids ...int) *ArgomentoUpdateOne {
	_u.mutation.AddDomandeIDs(ids...)
	return _u
}

// AddDomande adds the "domande" edges to the Domanda entity.
func (_u *ArgomentoUpdateOne) AddDomande(v ...*Domanda) *ArgomentoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDomandeIDs(ids...)
}

// Mutation returns the ArgomentoMutation object of the builder.
func (_u *ArgomentoUpdateOne) Mutation() *ArgomentoMutation {
	return _u.mutation
}

// ClearDomande clears all "domande" edges to the Domanda entity.
func (_u *ArgomentoUpdateOne) ClearDomande() *ArgomentoUpdateOne {
	_u.mutation.ClearDomande()
	return _u
}

// RemoveDomandeIDs removes the "domande" edge to Domanda entities by IDs.
func (_u *ArgomentoUpdateOne) RemoveDomandeIDs(ids ...int) *ArgomentoUpdateOne {
	_u.mutation.RemoveDomandeIDs(ids...)
	return _u
}

// RemoveDomande removes "domande" edges to Domanda entities.
func (_u *ArgomentoUpdateOne) RemoveDomande(v ...*Domanda) *ArgomentoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDomandeIDs(ids...)
}

// Where appends a list predicates to the ArgomentoUpdate builder.
func (_u *ArgomentoUpdateOne) Where(ps ...predicate.Argomento) *ArgomentoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArgomentoUpdateOne) Select(field string, fields ...string) *ArgomentoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Argomento entity.
func (_u *ArgomentoUpdateOne) Save(ctx context.Context) (*Argomento, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArgomentoUpdateOne) SaveX(ctx context.Context) *Argomento {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArgomentoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArgomentoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArgomentoUpdateOne) check() error {
	if v, ok := _u.mutation.Nome(); ok {
		if err := argomento.NomeValidator(v); err != nil {
			return &ValidationError{Name: "nome", err: fmt.Errorf(`ent: validator failed for field "Argomento.nome": %w`, err)}
		}
	}
	return nil
}

func (_u *ArgomentoUpdateOne) sqlSave(ctx context.Context) (_node *Argomento, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(argomento.Table, argomento.Columns, sqlgraph.NewFieldSpec(argomento.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Argomento.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, argomento.FieldID)
		for _, f := range fields {
			if !argomento.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != argomento.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nome(); ok {
		_spec.SetField(argomento.FieldNome, field.TypeString, value)
	}
	if _u.mutation.DomandeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   argomento.DomandeTable,
			Columns: argomento.DomandePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDomandeIDs(); len(nodes) > 0 && !_u.mutation.DomandeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   argomento.DomandeTable,
			Columns: argomento.DomandePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomandeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   argomento.DomandeTable,
			Columns: argomento.DomandePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Argomento{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{argomento.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
