// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ed-evo/hankinson/server/ent/attivitaquesitoesame"
	"github.com/ed-evo/hankinson/server/ent/quesitoesame"
)

// AttivitaQuesitoEsame is the model entity for the AttivitaQuesitoEsame schema.
type AttivitaQuesitoEsame struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Tipo holds the value of the "tipo" field.
	Tipo attivitaquesitoesame.Tipo `json:"tipo,omitempty"`
	// RispostaData holds the value of the "risposta_data" field.
	RispostaData *bool `json:"risposta_data,omitempty"`
	// Inizio holds the value of the "inizio" field.
	Inizio time.Time `json:"inizio,omitempty"`
	// Fine holds the value of the "fine" field.
	Fine time.Time `json:"fine,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AttivitaQuesitoEsameQuery when eager-loading is set.
	Edges              AttivitaQuesitoEsameEdges `json:"edges"`
	quesito_esame_logs *int
	selectValues       sql.SelectValues
}

// AttivitaQuesitoEsameEdges holds the relations/edges for other nodes in the graph.
type AttivitaQuesitoEsameEdges struct {
	// QuesitoEsame holds the value of the quesito_esame edge.
	QuesitoEsame *QuesitoEsame `json:"quesito_esame,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// QuesitoEsameOrErr returns the QuesitoEsame value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttivitaQuesitoEsameEdges) QuesitoEsameOrErr() (*QuesitoEsame, error) {
	if e.QuesitoEsame != nil {
		return e.QuesitoEsame, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: quesitoesame.Label}
	}
	return nil, &NotLoadedError{edge: "quesito_esame"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AttivitaQuesitoEsame) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attivitaquesitoesame.FieldRispostaData:
			values[i] = new(sql.NullBool)
		case attivitaquesitoesame.FieldID:
			values[i] = new(sql.NullInt64)
		case attivitaquesitoesame.FieldTipo:
			values[i] = new(sql.NullString)
		case attivitaquesitoesame.FieldInizio, attivitaquesitoesame.FieldFine, attivitaquesitoesame.FieldTimestamp:
			values[i] = new(sql.NullTime)
		case attivitaquesitoesame.ForeignKeys[0]: // quesito_esame_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AttivitaQuesitoEsame fields.
func (_m *AttivitaQuesitoEsame) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attivitaquesitoesame.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case attivitaquesitoesame.FieldTipo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tipo", values[i])
			} else if value.Valid {
				_m.Tipo = attivitaquesitoesame.Tipo(value.String)
			}
		case attivitaquesitoesame.FieldRispostaData:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field risposta_data", values[i])
			} else if value.Valid {
				_m.RispostaData = new(bool)
				*_m.RispostaData = value.Bool
			}
		case attivitaquesitoesame.FieldInizio:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field inizio", values[i])
			} else if value.Valid {
				_m.Inizio = value.Time
			}
		case attivitaquesitoesame.FieldFine:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fine", values[i])
			} else if value.Valid {
				_m.Fine = value.Time
			}
		case attivitaquesitoesame.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case attivitaquesitoesame.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field quesito_esame_logs", value)
			} else if value.Valid {
				_m.quesito_esame_logs = new(int)
				*_m.quesito_esame_logs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AttivitaQuesitoEsame.
// This includes values selected through modifiers, order, etc.
func (_m *AttivitaQuesitoEsame) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryQuesitoEsame queries the "quesito_esame" edge of the AttivitaQuesitoEsame entity.
func (_m *AttivitaQuesitoEsame) QueryQuesitoEsame() *QuesitoEsameQuery {
	return NewAttivitaQuesitoEsameClient(_m.config).QueryQuesitoEsame(_m)
}

// Update returns a builder for updating this AttivitaQuesitoEsame.
// Note that you need to call AttivitaQuesitoEsame.Unwrap() before calling this method if this AttivitaQuesitoEsame
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AttivitaQuesitoEsame) Update() *AttivitaQuesitoEsameUpdateOne {
	return NewAttivitaQuesitoEsameClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AttivitaQuesitoEsame entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AttivitaQuesitoEsame) Unwrap() *AttivitaQuesitoEsame {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AttivitaQuesitoEsame is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AttivitaQuesitoEsame) String() string {
	var builder strings.Builder
	builder.WriteString("AttivitaQuesitoEsame(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tipo=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tipo))
	builder.WriteString(", ")
	if v := _m.RispostaData; v != nil {
		builder.WriteString("risposta_data=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("inizio=")
	builder.WriteString(_m.Inizio.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("fine=")
	builder.WriteString(_m.Fine.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AttivitaQuesitoEsames is a parsable slice of AttivitaQuesitoEsame.
type AttivitaQuesitoEsames []*AttivitaQuesitoEsame
