// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ed-evo/hankinson/server/ent/attivitaquesitoesame"
	"github.com/ed-evo/hankinson/server/ent/predicate"
	"github.com/ed-evo/hankinson/server/ent/quesitoesame"
)

// AttivitaQuesitoEsameUpdate is the builder for updating AttivitaQuesitoEsame entities.
type AttivitaQuesitoEsameUpdate struct {
	config
	hooks    []Hook
	mutation *AttivitaQuesitoEsameMutation
}

// Where appends a list predicates to the AttivitaQuesitoEsameUpdate builder.
func (_u *AttivitaQuesitoEsameUpdate) Where(ps ...predicate.AttivitaQuesitoEsame) *AttivitaQuesitoEsameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTipo sets the "tipo" field.
func (_u *AttivitaQuesitoEsameUpdate) SetTipo(v attivitaquesitoesame.Tipo) *AttivitaQuesitoEsameUpdate {
	_u.mutation.SetTipo(v)
	return _u
}

// SetNillableTipo sets the "tipo" field if the given value is not nil.
func (_u *AttivitaQuesitoEsameUpdate) SetNillableTipo(v *attivitaquesitoesame.Tipo) *AttivitaQuesitoEsameUpdate {
	if v != nil {
		_u.SetTipo(*v)
	}
	return _u
}

// SetDurataMs sets the "durata_ms" field.
func (_u *AttivitaQuesitoEsameUpdate) SetDurataMs(v int) *AttivitaQuesitoEsameUpdate {
	_u.mutation.ResetDurataMs()
	_u.mutation.SetDurataMs(v)
	return _u
}

// SetNillableDurataMs sets the "durata_ms" field if the given value is not nil.
func (_u *AttivitaQuesitoEsameUpdate) SetNillableDurataMs(v *int) *AttivitaQuesitoEsameUpdate {
	if v != nil {
		_u.SetDurataMs(*v)
	}
	return _u
}

// AddDurataMs adds value to the "durata_ms" field.
func (_u *AttivitaQuesitoEsameUpdate) AddDurataMs(v int) *AttivitaQuesitoEsameUpdate {
	_u.mutation.AddDurataMs(v)
	return _u
}

// SetQuesitoEsameID sets the "quesito_esame" edge to the QuesitoEsame entity by ID.
func (_u *AttivitaQuesitoEsameUpdate) SetQuesitoEsameID(id int) *AttivitaQuesitoEsameUpdate {
	_u.mutation.SetQuesitoEsameID(id)
	return _u
}

// SetQuesitoEsame sets the "quesito_esame" edge to the QuesitoEsame entity.
func (_u *AttivitaQuesitoEsameUpdate) SetQuesitoEsame(v *QuesitoEsame) *AttivitaQuesitoEsameUpdate {
	return _u.SetQuesitoEsameID(v.ID)
}

// Mutation returns the AttivitaQuesitoEsameMutation object of the builder.
func (_u *AttivitaQuesitoEsameUpdate) Mutation() *AttivitaQuesitoEsameMutation {
	return _u.mutation
}

// ClearQuesitoEsame clears the "quesito_esame" edge to the QuesitoEsame entity.
func (_u *AttivitaQuesitoEsameUpdate) ClearQuesitoEsame() *AttivitaQuesitoEsameUpdate {
	_u.mutation.ClearQuesitoEsame()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AttivitaQuesitoEsameUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttivitaQuesitoEsameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AttivitaQuesitoEsameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttivitaQuesitoEsameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttivitaQuesitoEsameUpdate) check() error {
	if v, ok := _u.mutation.Tipo(); ok {
		if err := attivitaquesitoesame.TipoValidator(v); err != nil {
			return &ValidationError{Name: "tipo", err: fmt.Errorf(`ent: validator failed for field "AttivitaQuesitoEsame.tipo": %w`, err)}
		}
	}
	if _u.mutation.QuesitoEsameCleared() && len(_u.mutation.QuesitoEsameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AttivitaQuesitoEsame.quesito_esame"`)
	}
	return nil
}

func (_u *AttivitaQuesitoEsameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attivitaquesitoesame.Table, attivitaquesitoesame.Columns, sqlgraph.NewFieldSpec(attivitaquesitoesame.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tipo(); ok {
		_spec.SetField(attivitaquesitoesame.FieldTipo, field.TypeEnum, value)
	}
	if _u.mutation.RispostaDataCleared() {
		_spec.ClearField(attivitaquesitoesame.FieldRispostaData, field.TypeBool)
	}
	if value, ok := _u.mutation.DurataMs(); ok {
		_spec.SetField(attivitaquesitoesame.FieldDurataMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurataMs(); ok {
		_spec.AddField(attivitaquesitoesame.FieldDurataMs, field.TypeInt, value)
	}
	if _u.mutation.QuesitoEsameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attivitaquesitoesame.QuesitoEsameTable,
			Columns: []string{attivitaquesitoesame.QuesitoEsameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuesitoEsameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attivitaquesitoesame.QuesitoEsameTable,
			Columns: []string{attivitaquesitoesame.QuesitoEsameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attivitaquesitoesame.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AttivitaQuesitoEsameUpdateOne is the builder for updating a single AttivitaQuesitoEsame entity.
type AttivitaQuesitoEsameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttivitaQuesitoEsameMutation
}

// SetTipo sets the "tipo" field.
func (_u *AttivitaQuesitoEsameUpdateOne) SetTipo(v attivitaquesitoesame.Tipo) *AttivitaQuesitoEsameUpdateOne {
	_u.mutation.SetTipo(v)
	return _u
}

// SetNillableTipo sets the "tipo" field if the given value is not nil.
func (_u *AttivitaQuesitoEsameUpdateOne) SetNillableTipo(v *attivitaquesitoesame.Tipo) *AttivitaQuesitoEsameUpdateOne {
	if v != nil {
		_u.SetTipo(*v)
	}
	return _u
}

// SetDurataMs sets the "durata_ms" field.
func (_u *AttivitaQuesitoEsameUpdateOne) SetDurataMs(v int) *AttivitaQuesitoEsameUpdateOne {
	_u.mutation.ResetDurataMs()
	_u.mutation.SetDurataMs(v)
	return _u
}

// SetNillableDurataMs sets the "durata_ms" field if the given value is not nil.
func (_u *AttivitaQuesitoEsameUpdateOne) SetNillableDurataMs(v *int) *AttivitaQuesitoEsameUpdateOne {
	if v != nil {
		_u.SetDurataMs(*v)
	}
	return _u
}

// AddDurataMs adds value to the "durata_ms" field.
func (_u *AttivitaQuesitoEsameUpdateOne) AddDurataMs(v int) *AttivitaQuesitoEsameUpdateOne {
	_u.mutation.AddDurataMs(v)
	return _u
}

// SetQuesitoEsameID sets the "quesito_esame" edge to the QuesitoEsame entity by ID.
func (_u *AttivitaQuesitoEsameUpdateOne) SetQuesitoEsameID(id int) *AttivitaQuesitoEsameUpdateOne {
	_u.mutation.SetQuesitoEsameID(id)
	return _u
}

// SetQuesitoEsame sets the "quesito_esame" edge to the QuesitoEsame entity.
func (_u *AttivitaQuesitoEsameUpdateOne) SetQuesitoEsame(v *QuesitoEsame) *AttivitaQuesitoEsameUpdateOne {
	return _u.SetQuesitoEsameID(v.ID)
}

// Mutation returns the AttivitaQuesitoEsameMutation object of the builder.
func (_u *AttivitaQuesitoEsameUpdateOne) Mutation() *AttivitaQuesitoEsameMutation {
	return _u.mutation
}

// ClearQuesitoEsame clears the "quesito_esame" edge to the QuesitoEsame entity.
func (_u *AttivitaQuesitoEsameUpdateOne) ClearQuesitoEsame() *AttivitaQuesitoEsameUpdateOne {
	_u.mutation.ClearQuesitoEsame()
	return _u
}

// Where appends a list predicates to the AttivitaQuesitoEsameUpdate builder.
func (_u *AttivitaQuesitoEsameUpdateOne) Where(ps ...predicate.AttivitaQuesitoEsame) *AttivitaQuesitoEsameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AttivitaQuesitoEsameUpdateOne) Select(field string, fields ...string) *AttivitaQuesitoEsameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AttivitaQuesitoEsame entity.
func (_u *AttivitaQuesitoEsameUpdateOne) Save(ctx context.Context) (*AttivitaQuesitoEsame, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttivitaQuesitoEsameUpdateOne) SaveX(ctx context.Context) *AttivitaQuesitoEsame {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AttivitaQuesitoEsameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttivitaQuesitoEsameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttivitaQuesitoEsameUpdateOne) check() error {
	if v, ok := _u.mutation.Tipo(); ok {
		if err := attivitaquesitoesame.TipoValidator(v); err != nil {
			return &ValidationError{Name: "tipo", err: fmt.Errorf(`ent: validator failed for field "AttivitaQuesitoEsame.tipo": %w`, err)}
		}
	}
	if _u.mutation.QuesitoEsameCleared() && len(_u.mutation.QuesitoEsameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AttivitaQuesitoEsame.quesito_esame"`)
	}
	return nil
}

func (_u *AttivitaQuesitoEsameUpdateOne) sqlSave(ctx context.Context) (_node *AttivitaQuesitoEsame, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attivitaquesitoesame.Table, attivitaquesitoesame.Columns, sqlgraph.NewFieldSpec(attivitaquesitoesame.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AttivitaQuesitoEsame.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attivitaquesitoesame.FieldID)
		for _, f := range fields {
			if !attivitaquesitoesame.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attivitaquesitoesame.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tipo(); ok {
		_spec.SetField(attivitaquesitoesame.FieldTipo, field.TypeEnum, value)
	}
	if _u.mutation.RispostaDataCleared() {
		_spec.ClearField(attivitaquesitoesame.FieldRispostaData, field.TypeBool)
	}
	if value, ok := _u.mutation.DurataMs(); ok {
		_spec.SetField(attivitaquesitoesame.FieldDurataMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurataMs(); ok {
		_spec.AddField(attivitaquesitoesame.FieldDurataMs, field.TypeInt, value)
	}
	if _u.mutation.QuesitoEsameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attivitaquesitoesame.QuesitoEsameTable,
			Columns: []string{attivitaquesitoesame.QuesitoEsameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuesitoEsameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attivitaquesitoesame.QuesitoEsameTable,
			Columns: []string{attivitaquesitoesame.QuesitoEsameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AttivitaQuesitoEsame{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attivitaquesitoesame.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
