// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ed-evo/hankinson/server/ent/capitolo"
	"github.com/ed-evo/hankinson/server/ent/domanda"
)

// CapitoloCreate is the builder for creating a Capitolo entity.
type CapitoloCreate struct {
	config
	mutation *CapitoloMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNome sets the "nome" field.
func (_c *CapitoloCreate) SetNome(v string) *CapitoloCreate {
	_c.mutation.SetNome(v)
	return _c
}

// SetMinNumeroDomanda sets the "min_numero_domanda" field.
func (_c *CapitoloCreate) SetMinNumeroDomanda(v int) *CapitoloCreate {
	_c.mutation.SetMinNumeroDomanda(v)
	return _c
}

// SetMaxNumeroDomanda sets the "max_numero_domanda" field.
func (_c *CapitoloCreate) SetMaxNumeroDomanda(v int) *CapitoloCreate {
	_c.mutation.SetMaxNumeroDomanda(v)
	return _c
}

// SetTotaleDomande sets the "totale_domande" field.
func (_c *CapitoloCreate) SetTotaleDomande(v int) *CapitoloCreate {
	_c.mutation.SetTotaleDomande(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CapitoloCreate) SetID(v int) *CapitoloCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddDomandeIDs adds the "domande" edge to the Domanda entity by IDs.
func (_c *CapitoloCreate) AddDomandeIDs(ids ...int) *CapitoloCreate {
	_c.mutation.AddDomandeIDs(ids...)
	return _c
}

// AddDomande adds the "domande" edges to the Domanda entity.
func (_c *CapitoloCreate) AddDomande(v ...*Domanda) *CapitoloCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDomandeIDs(ids...)
}

// Mutation returns the CapitoloMutation object of the builder.
func (_c *CapitoloCreate) Mutation() *CapitoloMutation {
	return _c.mutation
}

// Save creates the Capitolo in the database.
func (_c *CapitoloCreate) Save(ctx context.Context) (*Capitolo, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CapitoloCreate) SaveX(ctx context.Context) *Capitolo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CapitoloCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CapitoloCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CapitoloCreate) check() error {
	if _, ok := _c.mutation.Nome(); !ok {
		return &ValidationError{Name: "nome", err: errors.New(`ent: missing required field "Capitolo.nome"`)}
	}
	if v, ok := _c.mutation.Nome(); ok {
		if err := capitolo.NomeValidator(v); err != nil {
			return &ValidationError{Name: "nome", err: fmt.Errorf(`ent: validator failed for field "Capitolo.nome": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MinNumeroDomanda(); !ok {
		return &ValidationError{Name: "min_numero_domanda", err: errors.New(`ent: missing required field "Capitolo.min_numero_domanda"`)}
	}
	if _, ok := _c.mutation.MaxNumeroDomanda(); !ok {
		return &ValidationError{Name: "max_numero_domanda", err: errors.New(`ent: missing required field "Capitolo.max_numero_domanda"`)}
	}
	if _, ok := _c.mutation.TotaleDomande(); !ok {
		return &ValidationError{Name: "totale_domande", err: errors.New(`ent: missing required field "Capitolo.totale_domande"`)}
	}
	return nil
}

func (_c *CapitoloCreate) sqlSave(ctx context.Context) (*Capitolo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CapitoloCreate) createSpec() (*Capitolo, *sqlgraph.CreateSpec) {
	var (
		_node = &Capitolo{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(capitolo.Table, sqlgraph.NewFieldSpec(capitolo.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Nome(); ok {
		_spec.SetField(capitolo.FieldNome, field.TypeString, value)
		_node.Nome = value
	}
	if value, ok := _c.mutation.MinNumeroDomanda(); ok {
		_spec.SetField(capitolo.FieldMinNumeroDomanda, field.TypeInt, value)
		_node.MinNumeroDomanda = value
	}
	if value, ok := _c.mutation.MaxNumeroDomanda(); ok {
		_spec.SetField(capitolo.FieldMaxNumeroDomanda, field.TypeInt, value)
		_node.MaxNumeroDomanda = value
	}
	if value, ok := _c.mutation.TotaleDomande(); ok {
		_spec.SetField(capitolo.FieldTotaleDomande, field.TypeInt, value)
		_node.TotaleDomande = value
	}
	if nodes := _c.mutation.DomandeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   capitolo.DomandeTable,
			Columns: []string{capitolo.DomandeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Capitolo.Create().
//		SetNome(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CapitoloUpsert) {
//			SetNome(v+v).
//		}).
//		Exec(ctx)
func (_c *CapitoloCreate) OnConflict(opts ...sql.ConflictOption) *CapitoloUpsertOne {
	_c.conflict = opts
	return &CapitoloUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Capitolo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CapitoloCreate) OnConflictColumns(columns ...string) *CapitoloUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CapitoloUpsertOne{
		create: _c,
	}
}

type (
	// CapitoloUpsertOne is the builder for "upsert"-ing
	//  one Capitolo node.
	CapitoloUpsertOne struct {
		create *CapitoloCreate
	}

	// CapitoloUpsert is the "OnConflict" setter.
	CapitoloUpsert struct {
		*sql.UpdateSet
	}
)

// SetNome sets the "nome" field.
func (u *CapitoloUpsert) SetNome(v string) *CapitoloUpsert {
	u.Set(capitolo.FieldNome, v)
	return u
}

// UpdateNome sets the "nome" field to the value that was provided on create.
func (u *CapitoloUpsert) UpdateNome() *CapitoloUpsert {
	u.SetExcluded(capitolo.FieldNome)
	return u
}

// SetMinNumeroDomanda sets the "min_numero_domanda" field.
func (u *CapitoloUpsert) SetMinNumeroDomanda(v int) *CapitoloUpsert {
	u.Set(capitolo.FieldMinNumeroDomanda, v)
	return u
}

// UpdateMinNumeroDomanda sets the "min_numero_domanda" field to the value that was provided on create.
func (u *CapitoloUpsert) UpdateMinNumeroDomanda() *CapitoloUpsert {
	u.SetExcluded(capitolo.FieldMinNumeroDomanda)
	return u
}

// AddMinNumeroDomanda adds v to the "min_numero_domanda" field.
func (u *CapitoloUpsert) AddMinNumeroDomanda(v int) *CapitoloUpsert {
	u.Add(capitolo.FieldMinNumeroDomanda, v)
	return u
}

// SetMaxNumeroDomanda sets the "max_numero_domanda" field.
func (u *CapitoloUpsert) SetMaxNumeroDomanda(v int) *CapitoloUpsert {
	u.Set(capitolo.FieldMaxNumeroDomanda, v)
	return u
}

// UpdateMaxNumeroDomanda sets the "max_numero_domanda" field to the value that was provided on create.
func (u *CapitoloUpsert) UpdateMaxNumeroDomanda() *CapitoloUpsert {
	u.SetExcluded(capitolo.FieldMaxNumeroDomanda)
	return u
}

// AddMaxNumeroDomanda adds v to the "max_numero_domanda" field.
func (u *CapitoloUpsert) AddMaxNumeroDomanda(v int) *CapitoloUpsert {
	u.Add(capitolo.FieldMaxNumeroDomanda, v)
	return u
}

// SetTotaleDomande sets the "totale_domande" field.
func (u *CapitoloUpsert) SetTotaleDomande(v int) *CapitoloUpsert {
	u.Set(capitolo.FieldTotaleDomande, v)
	return u
}

// UpdateTotaleDomande sets the "totale_domande" field to the value that was provided on create.
func (u *CapitoloUpsert) UpdateTotaleDomande() *CapitoloUpsert {
	u.SetExcluded(capitolo.FieldTotaleDomande)
	return u
}

// AddTotaleDomande adds v to the "totale_domande" field.
func (u *CapitoloUpsert) AddTotaleDomande(v int) *CapitoloUpsert {
	u.Add(capitolo.FieldTotaleDomande, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Capitolo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(capitolo.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CapitoloUpsertOne) UpdateNewValues() *CapitoloUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(capitolo.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Capitolo.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CapitoloUpsertOne) Ignore() *CapitoloUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CapitoloUpsertOne) DoNothing() *CapitoloUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CapitoloCreate.OnConflict
// documentation for more info.
func (u *CapitoloUpsertOne) Update(set func(*CapitoloUpsert)) *CapitoloUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CapitoloUpsert{UpdateSet: update})
	}))
	return u
}

// SetNome sets the "nome" field.
func (u *CapitoloUpsertOne) SetNome(v string) *CapitoloUpsertOne {
	return u.Update(func(s *CapitoloUpsert) {
		s.SetNome(v)
	})
}

// UpdateNome sets the "nome" field to the value that was provided on create.
func (u *CapitoloUpsertOne) UpdateNome() *CapitoloUpsertOne {
	return u.Update(func(s *CapitoloUpsert) {
		s.UpdateNome()
	})
}

// SetMinNumeroDomanda sets the "min_numero_domanda" field.
func (u *CapitoloUpsertOne) SetMinNumeroDomanda(v int) *CapitoloUpsertOne {
	return u.Update(func(s *CapitoloUpsert) {
		s.SetMinNumeroDomanda(v)
	})
}

// AddMinNumeroDomanda adds v to the "min_numero_domanda" field.
func (u *CapitoloUpsertOne) AddMinNumeroDomanda(v int) *CapitoloUpsertOne {
	return u.Update(func(s *CapitoloUpsert) {
		s.AddMinNumeroDomanda(v)
	})
}

// UpdateMinNumeroDomanda sets the "min_numero_domanda" field to the value that was provided on create.
func (u *CapitoloUpsertOne) UpdateMinNumeroDomanda() *CapitoloUpsertOne {
	return u.Update(func(s *CapitoloUpsert) {
		s.UpdateMinNumeroDomanda()
	})
}

// SetMaxNumeroDomanda sets the "max_numero_domanda" field.
func (u *CapitoloUpsertOne) SetMaxNumeroDomanda(v int) *CapitoloUpsertOne {
	return u.Update(func(s *CapitoloUpsert) {
		s.SetMaxNumeroDomanda(v)
	})
}

// AddMaxNumeroDomanda adds v to the "max_numero_domanda" field.
func (u *CapitoloUpsertOne) AddMaxNumeroDomanda(v int) *CapitoloUpsertOne {
	return u.Update(func(s *CapitoloUpsert) {
		s.AddMaxNumeroDomanda(v)
	})
}

// UpdateMaxNumeroDomanda sets the "max_numero_domanda" field to the value that was provided on create.
func (u *CapitoloUpsertOne) UpdateMaxNumeroDomanda() *CapitoloUpsertOne {
	return u.Update(func(s *CapitoloUpsert) {
		s.UpdateMaxNumeroDomanda()
	})
}

// SetTotaleDomande sets the "totale_domande" field.
func (u *CapitoloUpsertOne) SetTotaleDomande(v int) *CapitoloUpsertOne {
	return u.Update(func(s *CapitoloUpsert) {
		s.SetTotaleDomande(v)
	})
}

// AddTotaleDomande adds v to the "totale_domande" field.
func (u *CapitoloUpsertOne) AddTotaleDomande(v int) *CapitoloUpsertOne {
	return u.Update(func(s *CapitoloUpsert) {
		s.AddTotaleDomande(v)
	})
}

// UpdateTotaleDomande sets the "totale_domande" field to the value that was provided on create.
func (u *CapitoloUpsertOne) UpdateTotaleDomande() *CapitoloUpsertOne {
	return u.Update(func(s *CapitoloUpsert) {
		s.UpdateTotaleDomande()
	})
}

// Exec executes the query.
func (u *CapitoloUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CapitoloCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CapitoloUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CapitoloUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CapitoloUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CapitoloCreateBulk is the builder for creating many Capitolo entities in bulk.
type CapitoloCreateBulk struct {
	config
	err      error
	builders []*CapitoloCreate
	conflict []sql.ConflictOption
}

// Save creates the Capitolo entities in the database.
func (_c *CapitoloCreateBulk) Save(ctx context.Context) ([]*Capitolo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Capitolo, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CapitoloMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CapitoloCreateBulk) SaveX(ctx context.Context) []*Capitolo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CapitoloCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CapitoloCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Capitolo.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CapitoloUpsert) {
//			SetNome(v+v).
//		}).
//		Exec(ctx)
func (_c *CapitoloCreateBulk) OnConflict(opts ...sql.ConflictOption) *CapitoloUpsertBulk {
	_c.conflict = opts
	return &CapitoloUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Capitolo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CapitoloCreateBulk) OnConflictColumns(columns ...string) *CapitoloUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CapitoloUpsertBulk{
		create: _c,
	}
}

// CapitoloUpsertBulk is the builder for "upsert"-ing
// a bulk of Capitolo nodes.
type CapitoloUpsertBulk struct {
	create *CapitoloCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Capitolo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(capitolo.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CapitoloUpsertBulk) UpdateNewValues() *CapitoloUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(capitolo.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Capitolo.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CapitoloUpsertBulk) Ignore() *CapitoloUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CapitoloUpsertBulk) DoNothing() *CapitoloUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CapitoloCreateBulk.OnConflict
// documentation for more info.
func (u *CapitoloUpsertBulk) Update(set func(*CapitoloUpsert)) *CapitoloUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CapitoloUpsert{UpdateSet: update})
	}))
	return u
}

// SetNome sets the "nome" field.
func (u *CapitoloUpsertBulk) SetNome(v string) *CapitoloUpsertBulk {
	return u.Update(func(s *CapitoloUpsert) {
		s.SetNome(v)
	})
}

// UpdateNome sets the "nome" field to the value that was provided on create.
func (u *CapitoloUpsertBulk) UpdateNome() *CapitoloUpsertBulk {
	return u.Update(func(s *CapitoloUpsert) {
		s.UpdateNome()
	})
}

// SetMinNumeroDomanda sets the "min_numero_domanda" field.
func (u *CapitoloUpsertBulk) SetMinNumeroDomanda(v int) *CapitoloUpsertBulk {
	return u.Update(func(s *CapitoloUpsert) {
		s.SetMinNumeroDomanda(v)
	})
}

// AddMinNumeroDomanda adds v to the "min_numero_domanda" field.
func (u *CapitoloUpsertBulk) AddMinNumeroDomanda(v int) *CapitoloUpsertBulk {
	return u.Update(func(s *CapitoloUpsert) {
		s.AddMinNumeroDomanda(v)
	})
}

// UpdateMinNumeroDomanda sets the "min_numero_domanda" field to the value that was provided on create.
func (u *CapitoloUpsertBulk) UpdateMinNumeroDomanda() *CapitoloUpsertBulk {
	return u.Update(func(s *CapitoloUpsert) {
		s.UpdateMinNumeroDomanda()
	})
}

// SetMaxNumeroDomanda sets the "max_numero_domanda" field.
func (u *CapitoloUpsertBulk) SetMaxNumeroDomanda(v int) *CapitoloUpsertBulk {
	return u.Update(func(s *CapitoloUpsert) {
		s.SetMaxNumeroDomanda(v)
	})
}

// AddMaxNumeroDomanda adds v to the "max_numero_domanda" field.
func (u *CapitoloUpsertBulk) AddMaxNumeroDomanda(v int) *CapitoloUpsertBulk {
	return u.Update(func(s *CapitoloUpsert) {
		s.AddMaxNumeroDomanda(v)
	})
}

// UpdateMaxNumeroDomanda sets the "max_numero_domanda" field to the value that was provided on create.
func (u *CapitoloUpsertBulk) UpdateMaxNumeroDomanda() *CapitoloUpsertBulk {
	return u.Update(func(s *CapitoloUpsert) {
		s.UpdateMaxNumeroDomanda()
	})
}

// SetTotaleDomande sets the "totale_domande" field.
func (u *CapitoloUpsertBulk) SetTotaleDomande(v int) *CapitoloUpsertBulk {
	return u.Update(func(s *CapitoloUpsert) {
		s.SetTotaleDomande(v)
	})
}

// AddTotaleDomande adds v to the "totale_domande" field.
func (u *CapitoloUpsertBulk) AddTotaleDomande(v int) *CapitoloUpsertBulk {
	return u.Update(func(s *CapitoloUpsert) {
		s.AddTotaleDomande(v)
	})
}

// UpdateTotaleDomande sets the "totale_domande" field to the value that was provided on create.
func (u *CapitoloUpsertBulk) UpdateTotaleDomande() *CapitoloUpsertBulk {
	return u.Update(func(s *CapitoloUpsert) {
		s.UpdateTotaleDomande()
	})
}

// Exec executes the query.
func (u *CapitoloUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CapitoloCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CapitoloCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CapitoloUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
