// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/ed-evo/hankinson/server/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ed-evo/hankinson/server/ent/argomento"
	"github.com/ed-evo/hankinson/server/ent/capitolo"
	"github.com/ed-evo/hankinson/server/ent/domanda"
	"github.com/ed-evo/hankinson/server/ent/seed"

	stdsql "database/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Argomento is the client for interacting with the Argomento builders.
	Argomento *ArgomentoClient
	// Capitolo is the client for interacting with the Capitolo builders.
	Capitolo *CapitoloClient
	// Domanda is the client for interacting with the Domanda builders.
	Domanda *DomandaClient
	// Seed is the client for interacting with the Seed builders.
	Seed *SeedClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Argomento = NewArgomentoClient(c.config)
	c.Capitolo = NewCapitoloClient(c.config)
	c.Domanda = NewDomandaClient(c.config)
	c.Seed = NewSeedClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Argomento: NewArgomentoClient(cfg),
		Capitolo:  NewCapitoloClient(cfg),
		Domanda:   NewDomandaClient(cfg),
		Seed:      NewSeedClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Argomento: NewArgomentoClient(cfg),
		Capitolo:  NewCapitoloClient(cfg),
		Domanda:   NewDomandaClient(cfg),
		Seed:      NewSeedClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Argomento.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Argomento.Use(hooks...)
	c.Capitolo.Use(hooks...)
	c.Domanda.Use(hooks...)
	c.Seed.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Argomento.Intercept(interceptors...)
	c.Capitolo.Intercept(interceptors...)
	c.Domanda.Intercept(interceptors...)
	c.Seed.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ArgomentoMutation:
		return c.Argomento.mutate(ctx, m)
	case *CapitoloMutation:
		return c.Capitolo.mutate(ctx, m)
	case *DomandaMutation:
		return c.Domanda.mutate(ctx, m)
	case *SeedMutation:
		return c.Seed.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ArgomentoClient is a client for the Argomento schema.
type ArgomentoClient struct {
	config
}

// NewArgomentoClient returns a client for the Argomento from the given config.
func NewArgomentoClient(c config) *ArgomentoClient {
	return &ArgomentoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `argomento.Hooks(f(g(h())))`.
func (c *ArgomentoClient) Use(hooks ...Hook) {
	c.hooks.Argomento = append(c.hooks.Argomento, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `argomento.Intercept(f(g(h())))`.
func (c *ArgomentoClient) Intercept(interceptors ...Interceptor) {
	c.inters.Argomento = append(c.inters.Argomento, interceptors...)
}

// Create returns a builder for creating a Argomento entity.
func (c *ArgomentoClient) Create() *ArgomentoCreate {
	mutation := newArgomentoMutation(c.config, OpCreate)
	return &ArgomentoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Argomento entities.
func (c *ArgomentoClient) CreateBulk(builders ...*ArgomentoCreate) *ArgomentoCreateBulk {
	return &ArgomentoCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ArgomentoClient) MapCreateBulk(slice any, setFunc func(*ArgomentoCreate, int)) *ArgomentoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ArgomentoCreateBulk{err: fmt.Errorf("calling to ArgomentoClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ArgomentoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ArgomentoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Argomento.
func (c *ArgomentoClient) Update() *ArgomentoUpdate {
	mutation := newArgomentoMutation(c.config, OpUpdate)
	return &ArgomentoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ArgomentoClient) UpdateOne(_m *Argomento) *ArgomentoUpdateOne {
	mutation := newArgomentoMutation(c.config, OpUpdateOne, withArgomento(_m))
	return &ArgomentoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ArgomentoClient) UpdateOneID(id int) *ArgomentoUpdateOne {
	mutation := newArgomentoMutation(c.config, OpUpdateOne, withArgomentoID(id))
	return &ArgomentoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Argomento.
func (c *ArgomentoClient) Delete() *ArgomentoDelete {
	mutation := newArgomentoMutation(c.config, OpDelete)
	return &ArgomentoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ArgomentoClient) DeleteOne(_m *Argomento) *ArgomentoDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ArgomentoClient) DeleteOneID(id int) *ArgomentoDeleteOne {
	builder := c.Delete().Where(argomento.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ArgomentoDeleteOne{builder}
}

// Query returns a query builder for Argomento.
func (c *ArgomentoClient) Query() *ArgomentoQuery {
	return &ArgomentoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeArgomento},
		inters: c.Interceptors(),
	}
}

// Get returns a Argomento entity by its id.
func (c *ArgomentoClient) Get(ctx context.Context, id int) (*Argomento, error) {
	return c.Query().Where(argomento.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ArgomentoClient) GetX(ctx context.Context, id int) *Argomento {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDomande queries the domande edge of a Argomento.
func (c *ArgomentoClient) QueryDomande(_m *Argomento) *DomandaQuery {
	query := (&DomandaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(argomento.Table, argomento.FieldID, id),
			sqlgraph.To(domanda.Table, domanda.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, argomento.DomandeTable, argomento.DomandePrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ArgomentoClient) Hooks() []Hook {
	return c.hooks.Argomento
}

// Interceptors returns the client interceptors.
func (c *ArgomentoClient) Interceptors() []Interceptor {
	return c.inters.Argomento
}

func (c *ArgomentoClient) mutate(ctx context.Context, m *ArgomentoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ArgomentoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ArgomentoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ArgomentoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ArgomentoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Argomento mutation op: %q", m.Op())
	}
}

// CapitoloClient is a client for the Capitolo schema.
type CapitoloClient struct {
	config
}

// NewCapitoloClient returns a client for the Capitolo from the given config.
func NewCapitoloClient(c config) *CapitoloClient {
	return &CapitoloClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `capitolo.Hooks(f(g(h())))`.
func (c *CapitoloClient) Use(hooks ...Hook) {
	c.hooks.Capitolo = append(c.hooks.Capitolo, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `capitolo.Intercept(f(g(h())))`.
func (c *CapitoloClient) Intercept(interceptors ...Interceptor) {
	c.inters.Capitolo = append(c.inters.Capitolo, interceptors...)
}

// Create returns a builder for creating a Capitolo entity.
func (c *CapitoloClient) Create() *CapitoloCreate {
	mutation := newCapitoloMutation(c.config, OpCreate)
	return &CapitoloCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Capitolo entities.
func (c *CapitoloClient) CreateBulk(builders ...*CapitoloCreate) *CapitoloCreateBulk {
	return &CapitoloCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CapitoloClient) MapCreateBulk(slice any, setFunc func(*CapitoloCreate, int)) *CapitoloCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CapitoloCreateBulk{err: fmt.Errorf("calling to CapitoloClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CapitoloCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CapitoloCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Capitolo.
func (c *CapitoloClient) Update() *CapitoloUpdate {
	mutation := newCapitoloMutation(c.config, OpUpdate)
	return &CapitoloUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CapitoloClient) UpdateOne(_m *Capitolo) *CapitoloUpdateOne {
	mutation := newCapitoloMutation(c.config, OpUpdateOne, withCapitolo(_m))
	return &CapitoloUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CapitoloClient) UpdateOneID(id int) *CapitoloUpdateOne {
	mutation := newCapitoloMutation(c.config, OpUpdateOne, withCapitoloID(id))
	return &CapitoloUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Capitolo.
func (c *CapitoloClient) Delete() *CapitoloDelete {
	mutation := newCapitoloMutation(c.config, OpDelete)
	return &CapitoloDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CapitoloClient) DeleteOne(_m *Capitolo) *CapitoloDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CapitoloClient) DeleteOneID(id int) *CapitoloDeleteOne {
	builder := c.Delete().Where(capitolo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CapitoloDeleteOne{builder}
}

// Query returns a query builder for Capitolo.
func (c *CapitoloClient) Query() *CapitoloQuery {
	return &CapitoloQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCapitolo},
		inters: c.Interceptors(),
	}
}

// Get returns a Capitolo entity by its id.
func (c *CapitoloClient) Get(ctx context.Context, id int) (*Capitolo, error) {
	return c.Query().Where(capitolo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CapitoloClient) GetX(ctx context.Context, id int) *Capitolo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDomande queries the domande edge of a Capitolo.
func (c *CapitoloClient) QueryDomande(_m *Capitolo) *DomandaQuery {
	query := (&DomandaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(capitolo.Table, capitolo.FieldID, id),
			sqlgraph.To(domanda.Table, domanda.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, capitolo.DomandeTable, capitolo.DomandeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CapitoloClient) Hooks() []Hook {
	return c.hooks.Capitolo
}

// Interceptors returns the client interceptors.
func (c *CapitoloClient) Interceptors() []Interceptor {
	return c.inters.Capitolo
}

func (c *CapitoloClient) mutate(ctx context.Context, m *CapitoloMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CapitoloCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CapitoloUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CapitoloUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CapitoloDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Capitolo mutation op: %q", m.Op())
	}
}

// DomandaClient is a client for the Domanda schema.
type DomandaClient struct {
	config
}

// NewDomandaClient returns a client for the Domanda from the given config.
func NewDomandaClient(c config) *DomandaClient {
	return &DomandaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `domanda.Hooks(f(g(h())))`.
func (c *DomandaClient) Use(hooks ...Hook) {
	c.hooks.Domanda = append(c.hooks.Domanda, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `domanda.Intercept(f(g(h())))`.
func (c *DomandaClient) Intercept(interceptors ...Interceptor) {
	c.inters.Domanda = append(c.inters.Domanda, interceptors...)
}

// Create returns a builder for creating a Domanda entity.
func (c *DomandaClient) Create() *DomandaCreate {
	mutation := newDomandaMutation(c.config, OpCreate)
	return &DomandaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Domanda entities.
func (c *DomandaClient) CreateBulk(builders ...*DomandaCreate) *DomandaCreateBulk {
	return &DomandaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DomandaClient) MapCreateBulk(slice any, setFunc func(*DomandaCreate, int)) *DomandaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DomandaCreateBulk{err: fmt.Errorf("calling to DomandaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DomandaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DomandaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Domanda.
func (c *DomandaClient) Update() *DomandaUpdate {
	mutation := newDomandaMutation(c.config, OpUpdate)
	return &DomandaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DomandaClient) UpdateOne(_m *Domanda) *DomandaUpdateOne {
	mutation := newDomandaMutation(c.config, OpUpdateOne, withDomanda(_m))
	return &DomandaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DomandaClient) UpdateOneID(id int) *DomandaUpdateOne {
	mutation := newDomandaMutation(c.config, OpUpdateOne, withDomandaID(id))
	return &DomandaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Domanda.
func (c *DomandaClient) Delete() *DomandaDelete {
	mutation := newDomandaMutation(c.config, OpDelete)
	return &DomandaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DomandaClient) DeleteOne(_m *Domanda) *DomandaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DomandaClient) DeleteOneID(id int) *DomandaDeleteOne {
	builder := c.Delete().Where(domanda.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DomandaDeleteOne{builder}
}

// Query returns a query builder for Domanda.
func (c *DomandaClient) Query() *DomandaQuery {
	return &DomandaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDomanda},
		inters: c.Interceptors(),
	}
}

// Get returns a Domanda entity by its id.
func (c *DomandaClient) Get(ctx context.Context, id int) (*Domanda, error) {
	return c.Query().Where(domanda.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DomandaClient) GetX(ctx context.Context, id int) *Domanda {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryArgomenti queries the argomenti edge of a Domanda.
func (c *DomandaClient) QueryArgomenti(_m *Domanda) *ArgomentoQuery {
	query := (&ArgomentoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(domanda.Table, domanda.FieldID, id),
			sqlgraph.To(argomento.Table, argomento.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, domanda.ArgomentiTable, domanda.ArgomentiPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCapitolo queries the capitolo edge of a Domanda.
func (c *DomandaClient) QueryCapitolo(_m *Domanda) *CapitoloQuery {
	query := (&CapitoloClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(domanda.Table, domanda.FieldID, id),
			sqlgraph.To(capitolo.Table, capitolo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, domanda.CapitoloTable, domanda.CapitoloColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DomandaClient) Hooks() []Hook {
	return c.hooks.Domanda
}

// Interceptors returns the client interceptors.
func (c *DomandaClient) Interceptors() []Interceptor {
	return c.inters.Domanda
}

func (c *DomandaClient) mutate(ctx context.Context, m *DomandaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DomandaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DomandaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DomandaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DomandaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Domanda mutation op: %q", m.Op())
	}
}

// SeedClient is a client for the Seed schema.
type SeedClient struct {
	config
}

// NewSeedClient returns a client for the Seed from the given config.
func NewSeedClient(c config) *SeedClient {
	return &SeedClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `seed.Hooks(f(g(h())))`.
func (c *SeedClient) Use(hooks ...Hook) {
	c.hooks.Seed = append(c.hooks.Seed, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `seed.Intercept(f(g(h())))`.
func (c *SeedClient) Intercept(interceptors ...Interceptor) {
	c.inters.Seed = append(c.inters.Seed, interceptors...)
}

// Create returns a builder for creating a Seed entity.
func (c *SeedClient) Create() *SeedCreate {
	mutation := newSeedMutation(c.config, OpCreate)
	return &SeedCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Seed entities.
func (c *SeedClient) CreateBulk(builders ...*SeedCreate) *SeedCreateBulk {
	return &SeedCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SeedClient) MapCreateBulk(slice any, setFunc func(*SeedCreate, int)) *SeedCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SeedCreateBulk{err: fmt.Errorf("calling to SeedClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SeedCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SeedCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Seed.
func (c *SeedClient) Update() *SeedUpdate {
	mutation := newSeedMutation(c.config, OpUpdate)
	return &SeedUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SeedClient) UpdateOne(_m *Seed) *SeedUpdateOne {
	mutation := newSeedMutation(c.config, OpUpdateOne, withSeed(_m))
	return &SeedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SeedClient) UpdateOneID(id int) *SeedUpdateOne {
	mutation := newSeedMutation(c.config, OpUpdateOne, withSeedID(id))
	return &SeedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Seed.
func (c *SeedClient) Delete() *SeedDelete {
	mutation := newSeedMutation(c.config, OpDelete)
	return &SeedDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SeedClient) DeleteOne(_m *Seed) *SeedDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SeedClient) DeleteOneID(id int) *SeedDeleteOne {
	builder := c.Delete().Where(seed.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SeedDeleteOne{builder}
}

// Query returns a query builder for Seed.
func (c *SeedClient) Query() *SeedQuery {
	return &SeedQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSeed},
		inters: c.Interceptors(),
	}
}

// Get returns a Seed entity by its id.
func (c *SeedClient) Get(ctx context.Context, id int) (*Seed, error) {
	return c.Query().Where(seed.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SeedClient) GetX(ctx context.Context, id int) *Seed {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SeedClient) Hooks() []Hook {
	return c.hooks.Seed
}

// Interceptors returns the client interceptors.
func (c *SeedClient) Interceptors() []Interceptor {
	return c.inters.Seed
}

func (c *SeedClient) mutate(ctx context.Context, m *SeedMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SeedCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SeedUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SeedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SeedDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Seed mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Argomento, Capitolo, Domanda, Seed []ent.Hook
	}
	inters struct {
		Argomento, Capitolo, Domanda, Seed []ent.Interceptor
	}
)

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
