// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/ed-evo/hankinson/server/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ed-evo/hankinson/server/ent/argomento"
	"github.com/ed-evo/hankinson/server/ent/attivitaquesitoesame"
	"github.com/ed-evo/hankinson/server/ent/capitolo"
	"github.com/ed-evo/hankinson/server/ent/domanda"
	"github.com/ed-evo/hankinson/server/ent/esame"
	"github.com/ed-evo/hankinson/server/ent/quesitoesame"
	"github.com/ed-evo/hankinson/server/ent/seed"
	"github.com/ed-evo/hankinson/server/ent/utente"

	stdsql "database/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Argomento is the client for interacting with the Argomento builders.
	Argomento *ArgomentoClient
	// AttivitaQuesitoEsame is the client for interacting with the AttivitaQuesitoEsame builders.
	AttivitaQuesitoEsame *AttivitaQuesitoEsameClient
	// Capitolo is the client for interacting with the Capitolo builders.
	Capitolo *CapitoloClient
	// Domanda is the client for interacting with the Domanda builders.
	Domanda *DomandaClient
	// Esame is the client for interacting with the Esame builders.
	Esame *EsameClient
	// QuesitoEsame is the client for interacting with the QuesitoEsame builders.
	QuesitoEsame *QuesitoEsameClient
	// Seed is the client for interacting with the Seed builders.
	Seed *SeedClient
	// Utente is the client for interacting with the Utente builders.
	Utente *UtenteClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Argomento = NewArgomentoClient(c.config)
	c.AttivitaQuesitoEsame = NewAttivitaQuesitoEsameClient(c.config)
	c.Capitolo = NewCapitoloClient(c.config)
	c.Domanda = NewDomandaClient(c.config)
	c.Esame = NewEsameClient(c.config)
	c.QuesitoEsame = NewQuesitoEsameClient(c.config)
	c.Seed = NewSeedClient(c.config)
	c.Utente = NewUtenteClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		Argomento:            NewArgomentoClient(cfg),
		AttivitaQuesitoEsame: NewAttivitaQuesitoEsameClient(cfg),
		Capitolo:             NewCapitoloClient(cfg),
		Domanda:              NewDomandaClient(cfg),
		Esame:                NewEsameClient(cfg),
		QuesitoEsame:         NewQuesitoEsameClient(cfg),
		Seed:                 NewSeedClient(cfg),
		Utente:               NewUtenteClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		Argomento:            NewArgomentoClient(cfg),
		AttivitaQuesitoEsame: NewAttivitaQuesitoEsameClient(cfg),
		Capitolo:             NewCapitoloClient(cfg),
		Domanda:              NewDomandaClient(cfg),
		Esame:                NewEsameClient(cfg),
		QuesitoEsame:         NewQuesitoEsameClient(cfg),
		Seed:                 NewSeedClient(cfg),
		Utente:               NewUtenteClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Argomento.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Argomento, c.AttivitaQuesitoEsame, c.Capitolo, c.Domanda, c.Esame,
		c.QuesitoEsame, c.Seed, c.Utente,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Argomento, c.AttivitaQuesitoEsame, c.Capitolo, c.Domanda, c.Esame,
		c.QuesitoEsame, c.Seed, c.Utente,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ArgomentoMutation:
		return c.Argomento.mutate(ctx, m)
	case *AttivitaQuesitoEsameMutation:
		return c.AttivitaQuesitoEsame.mutate(ctx, m)
	case *CapitoloMutation:
		return c.Capitolo.mutate(ctx, m)
	case *DomandaMutation:
		return c.Domanda.mutate(ctx, m)
	case *EsameMutation:
		return c.Esame.mutate(ctx, m)
	case *QuesitoEsameMutation:
		return c.QuesitoEsame.mutate(ctx, m)
	case *SeedMutation:
		return c.Seed.mutate(ctx, m)
	case *UtenteMutation:
		return c.Utente.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ArgomentoClient is a client for the Argomento schema.
type ArgomentoClient struct {
	config
}

// NewArgomentoClient returns a client for the Argomento from the given config.
func NewArgomentoClient(c config) *ArgomentoClient {
	return &ArgomentoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `argomento.Hooks(f(g(h())))`.
func (c *ArgomentoClient) Use(hooks ...Hook) {
	c.hooks.Argomento = append(c.hooks.Argomento, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `argomento.Intercept(f(g(h())))`.
func (c *ArgomentoClient) Intercept(interceptors ...Interceptor) {
	c.inters.Argomento = append(c.inters.Argomento, interceptors...)
}

// Create returns a builder for creating a Argomento entity.
func (c *ArgomentoClient) Create() *ArgomentoCreate {
	mutation := newArgomentoMutation(c.config, OpCreate)
	return &ArgomentoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Argomento entities.
func (c *ArgomentoClient) CreateBulk(builders ...*ArgomentoCreate) *ArgomentoCreateBulk {
	return &ArgomentoCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ArgomentoClient) MapCreateBulk(slice any, setFunc func(*ArgomentoCreate, int)) *ArgomentoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ArgomentoCreateBulk{err: fmt.Errorf("calling to ArgomentoClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ArgomentoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ArgomentoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Argomento.
func (c *ArgomentoClient) Update() *ArgomentoUpdate {
	mutation := newArgomentoMutation(c.config, OpUpdate)
	return &ArgomentoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ArgomentoClient) UpdateOne(_m *Argomento) *ArgomentoUpdateOne {
	mutation := newArgomentoMutation(c.config, OpUpdateOne, withArgomento(_m))
	return &ArgomentoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ArgomentoClient) UpdateOneID(id int) *ArgomentoUpdateOne {
	mutation := newArgomentoMutation(c.config, OpUpdateOne, withArgomentoID(id))
	return &ArgomentoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Argomento.
func (c *ArgomentoClient) Delete() *ArgomentoDelete {
	mutation := newArgomentoMutation(c.config, OpDelete)
	return &ArgomentoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ArgomentoClient) DeleteOne(_m *Argomento) *ArgomentoDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ArgomentoClient) DeleteOneID(id int) *ArgomentoDeleteOne {
	builder := c.Delete().Where(argomento.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ArgomentoDeleteOne{builder}
}

// Query returns a query builder for Argomento.
func (c *ArgomentoClient) Query() *ArgomentoQuery {
	return &ArgomentoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeArgomento},
		inters: c.Interceptors(),
	}
}

// Get returns a Argomento entity by its id.
func (c *ArgomentoClient) Get(ctx context.Context, id int) (*Argomento, error) {
	return c.Query().Where(argomento.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ArgomentoClient) GetX(ctx context.Context, id int) *Argomento {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDomande queries the domande edge of a Argomento.
func (c *ArgomentoClient) QueryDomande(_m *Argomento) *DomandaQuery {
	query := (&DomandaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(argomento.Table, argomento.FieldID, id),
			sqlgraph.To(domanda.Table, domanda.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, argomento.DomandeTable, argomento.DomandePrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ArgomentoClient) Hooks() []Hook {
	return c.hooks.Argomento
}

// Interceptors returns the client interceptors.
func (c *ArgomentoClient) Interceptors() []Interceptor {
	return c.inters.Argomento
}

func (c *ArgomentoClient) mutate(ctx context.Context, m *ArgomentoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ArgomentoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ArgomentoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ArgomentoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ArgomentoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Argomento mutation op: %q", m.Op())
	}
}

// AttivitaQuesitoEsameClient is a client for the AttivitaQuesitoEsame schema.
type AttivitaQuesitoEsameClient struct {
	config
}

// NewAttivitaQuesitoEsameClient returns a client for the AttivitaQuesitoEsame from the given config.
func NewAttivitaQuesitoEsameClient(c config) *AttivitaQuesitoEsameClient {
	return &AttivitaQuesitoEsameClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `attivitaquesitoesame.Hooks(f(g(h())))`.
func (c *AttivitaQuesitoEsameClient) Use(hooks ...Hook) {
	c.hooks.AttivitaQuesitoEsame = append(c.hooks.AttivitaQuesitoEsame, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `attivitaquesitoesame.Intercept(f(g(h())))`.
func (c *AttivitaQuesitoEsameClient) Intercept(interceptors ...Interceptor) {
	c.inters.AttivitaQuesitoEsame = append(c.inters.AttivitaQuesitoEsame, interceptors...)
}

// Create returns a builder for creating a AttivitaQuesitoEsame entity.
func (c *AttivitaQuesitoEsameClient) Create() *AttivitaQuesitoEsameCreate {
	mutation := newAttivitaQuesitoEsameMutation(c.config, OpCreate)
	return &AttivitaQuesitoEsameCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AttivitaQuesitoEsame entities.
func (c *AttivitaQuesitoEsameClient) CreateBulk(builders ...*AttivitaQuesitoEsameCreate) *AttivitaQuesitoEsameCreateBulk {
	return &AttivitaQuesitoEsameCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AttivitaQuesitoEsameClient) MapCreateBulk(slice any, setFunc func(*AttivitaQuesitoEsameCreate, int)) *AttivitaQuesitoEsameCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AttivitaQuesitoEsameCreateBulk{err: fmt.Errorf("calling to AttivitaQuesitoEsameClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AttivitaQuesitoEsameCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AttivitaQuesitoEsameCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AttivitaQuesitoEsame.
func (c *AttivitaQuesitoEsameClient) Update() *AttivitaQuesitoEsameUpdate {
	mutation := newAttivitaQuesitoEsameMutation(c.config, OpUpdate)
	return &AttivitaQuesitoEsameUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AttivitaQuesitoEsameClient) UpdateOne(_m *AttivitaQuesitoEsame) *AttivitaQuesitoEsameUpdateOne {
	mutation := newAttivitaQuesitoEsameMutation(c.config, OpUpdateOne, withAttivitaQuesitoEsame(_m))
	return &AttivitaQuesitoEsameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AttivitaQuesitoEsameClient) UpdateOneID(id int) *AttivitaQuesitoEsameUpdateOne {
	mutation := newAttivitaQuesitoEsameMutation(c.config, OpUpdateOne, withAttivitaQuesitoEsameID(id))
	return &AttivitaQuesitoEsameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AttivitaQuesitoEsame.
func (c *AttivitaQuesitoEsameClient) Delete() *AttivitaQuesitoEsameDelete {
	mutation := newAttivitaQuesitoEsameMutation(c.config, OpDelete)
	return &AttivitaQuesitoEsameDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AttivitaQuesitoEsameClient) DeleteOne(_m *AttivitaQuesitoEsame) *AttivitaQuesitoEsameDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AttivitaQuesitoEsameClient) DeleteOneID(id int) *AttivitaQuesitoEsameDeleteOne {
	builder := c.Delete().Where(attivitaquesitoesame.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AttivitaQuesitoEsameDeleteOne{builder}
}

// Query returns a query builder for AttivitaQuesitoEsame.
func (c *AttivitaQuesitoEsameClient) Query() *AttivitaQuesitoEsameQuery {
	return &AttivitaQuesitoEsameQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAttivitaQuesitoEsame},
		inters: c.Interceptors(),
	}
}

// Get returns a AttivitaQuesitoEsame entity by its id.
func (c *AttivitaQuesitoEsameClient) Get(ctx context.Context, id int) (*AttivitaQuesitoEsame, error) {
	return c.Query().Where(attivitaquesitoesame.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AttivitaQuesitoEsameClient) GetX(ctx context.Context, id int) *AttivitaQuesitoEsame {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryQuesitoEsame queries the quesito_esame edge of a AttivitaQuesitoEsame.
func (c *AttivitaQuesitoEsameClient) QueryQuesitoEsame(_m *AttivitaQuesitoEsame) *QuesitoEsameQuery {
	query := (&QuesitoEsameClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(attivitaquesitoesame.Table, attivitaquesitoesame.FieldID, id),
			sqlgraph.To(quesitoesame.Table, quesitoesame.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attivitaquesitoesame.QuesitoEsameTable, attivitaquesitoesame.QuesitoEsameColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AttivitaQuesitoEsameClient) Hooks() []Hook {
	return c.hooks.AttivitaQuesitoEsame
}

// Interceptors returns the client interceptors.
func (c *AttivitaQuesitoEsameClient) Interceptors() []Interceptor {
	return c.inters.AttivitaQuesitoEsame
}

func (c *AttivitaQuesitoEsameClient) mutate(ctx context.Context, m *AttivitaQuesitoEsameMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AttivitaQuesitoEsameCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AttivitaQuesitoEsameUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AttivitaQuesitoEsameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AttivitaQuesitoEsameDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AttivitaQuesitoEsame mutation op: %q", m.Op())
	}
}

// CapitoloClient is a client for the Capitolo schema.
type CapitoloClient struct {
	config
}

// NewCapitoloClient returns a client for the Capitolo from the given config.
func NewCapitoloClient(c config) *CapitoloClient {
	return &CapitoloClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `capitolo.Hooks(f(g(h())))`.
func (c *CapitoloClient) Use(hooks ...Hook) {
	c.hooks.Capitolo = append(c.hooks.Capitolo, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `capitolo.Intercept(f(g(h())))`.
func (c *CapitoloClient) Intercept(interceptors ...Interceptor) {
	c.inters.Capitolo = append(c.inters.Capitolo, interceptors...)
}

// Create returns a builder for creating a Capitolo entity.
func (c *CapitoloClient) Create() *CapitoloCreate {
	mutation := newCapitoloMutation(c.config, OpCreate)
	return &CapitoloCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Capitolo entities.
func (c *CapitoloClient) CreateBulk(builders ...*CapitoloCreate) *CapitoloCreateBulk {
	return &CapitoloCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CapitoloClient) MapCreateBulk(slice any, setFunc func(*CapitoloCreate, int)) *CapitoloCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CapitoloCreateBulk{err: fmt.Errorf("calling to CapitoloClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CapitoloCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CapitoloCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Capitolo.
func (c *CapitoloClient) Update() *CapitoloUpdate {
	mutation := newCapitoloMutation(c.config, OpUpdate)
	return &CapitoloUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CapitoloClient) UpdateOne(_m *Capitolo) *CapitoloUpdateOne {
	mutation := newCapitoloMutation(c.config, OpUpdateOne, withCapitolo(_m))
	return &CapitoloUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CapitoloClient) UpdateOneID(id int) *CapitoloUpdateOne {
	mutation := newCapitoloMutation(c.config, OpUpdateOne, withCapitoloID(id))
	return &CapitoloUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Capitolo.
func (c *CapitoloClient) Delete() *CapitoloDelete {
	mutation := newCapitoloMutation(c.config, OpDelete)
	return &CapitoloDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CapitoloClient) DeleteOne(_m *Capitolo) *CapitoloDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CapitoloClient) DeleteOneID(id int) *CapitoloDeleteOne {
	builder := c.Delete().Where(capitolo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CapitoloDeleteOne{builder}
}

// Query returns a query builder for Capitolo.
func (c *CapitoloClient) Query() *CapitoloQuery {
	return &CapitoloQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCapitolo},
		inters: c.Interceptors(),
	}
}

// Get returns a Capitolo entity by its id.
func (c *CapitoloClient) Get(ctx context.Context, id int) (*Capitolo, error) {
	return c.Query().Where(capitolo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CapitoloClient) GetX(ctx context.Context, id int) *Capitolo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDomande queries the domande edge of a Capitolo.
func (c *CapitoloClient) QueryDomande(_m *Capitolo) *DomandaQuery {
	query := (&DomandaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(capitolo.Table, capitolo.FieldID, id),
			sqlgraph.To(domanda.Table, domanda.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, capitolo.DomandeTable, capitolo.DomandeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CapitoloClient) Hooks() []Hook {
	return c.hooks.Capitolo
}

// Interceptors returns the client interceptors.
func (c *CapitoloClient) Interceptors() []Interceptor {
	return c.inters.Capitolo
}

func (c *CapitoloClient) mutate(ctx context.Context, m *CapitoloMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CapitoloCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CapitoloUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CapitoloUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CapitoloDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Capitolo mutation op: %q", m.Op())
	}
}

// DomandaClient is a client for the Domanda schema.
type DomandaClient struct {
	config
}

// NewDomandaClient returns a client for the Domanda from the given config.
func NewDomandaClient(c config) *DomandaClient {
	return &DomandaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `domanda.Hooks(f(g(h())))`.
func (c *DomandaClient) Use(hooks ...Hook) {
	c.hooks.Domanda = append(c.hooks.Domanda, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `domanda.Intercept(f(g(h())))`.
func (c *DomandaClient) Intercept(interceptors ...Interceptor) {
	c.inters.Domanda = append(c.inters.Domanda, interceptors...)
}

// Create returns a builder for creating a Domanda entity.
func (c *DomandaClient) Create() *DomandaCreate {
	mutation := newDomandaMutation(c.config, OpCreate)
	return &DomandaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Domanda entities.
func (c *DomandaClient) CreateBulk(builders ...*DomandaCreate) *DomandaCreateBulk {
	return &DomandaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DomandaClient) MapCreateBulk(slice any, setFunc func(*DomandaCreate, int)) *DomandaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DomandaCreateBulk{err: fmt.Errorf("calling to DomandaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DomandaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DomandaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Domanda.
func (c *DomandaClient) Update() *DomandaUpdate {
	mutation := newDomandaMutation(c.config, OpUpdate)
	return &DomandaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DomandaClient) UpdateOne(_m *Domanda) *DomandaUpdateOne {
	mutation := newDomandaMutation(c.config, OpUpdateOne, withDomanda(_m))
	return &DomandaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DomandaClient) UpdateOneID(id int) *DomandaUpdateOne {
	mutation := newDomandaMutation(c.config, OpUpdateOne, withDomandaID(id))
	return &DomandaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Domanda.
func (c *DomandaClient) Delete() *DomandaDelete {
	mutation := newDomandaMutation(c.config, OpDelete)
	return &DomandaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DomandaClient) DeleteOne(_m *Domanda) *DomandaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DomandaClient) DeleteOneID(id int) *DomandaDeleteOne {
	builder := c.Delete().Where(domanda.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DomandaDeleteOne{builder}
}

// Query returns a query builder for Domanda.
func (c *DomandaClient) Query() *DomandaQuery {
	return &DomandaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDomanda},
		inters: c.Interceptors(),
	}
}

// Get returns a Domanda entity by its id.
func (c *DomandaClient) Get(ctx context.Context, id int) (*Domanda, error) {
	return c.Query().Where(domanda.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DomandaClient) GetX(ctx context.Context, id int) *Domanda {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryArgomenti queries the argomenti edge of a Domanda.
func (c *DomandaClient) QueryArgomenti(_m *Domanda) *ArgomentoQuery {
	query := (&ArgomentoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(domanda.Table, domanda.FieldID, id),
			sqlgraph.To(argomento.Table, argomento.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, domanda.ArgomentiTable, domanda.ArgomentiPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCapitolo queries the capitolo edge of a Domanda.
func (c *DomandaClient) QueryCapitolo(_m *Domanda) *CapitoloQuery {
	query := (&CapitoloClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(domanda.Table, domanda.FieldID, id),
			sqlgraph.To(capitolo.Table, capitolo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, domanda.CapitoloTable, domanda.CapitoloColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DomandaClient) Hooks() []Hook {
	return c.hooks.Domanda
}

// Interceptors returns the client interceptors.
func (c *DomandaClient) Interceptors() []Interceptor {
	return c.inters.Domanda
}

func (c *DomandaClient) mutate(ctx context.Context, m *DomandaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DomandaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DomandaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DomandaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DomandaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Domanda mutation op: %q", m.Op())
	}
}

// EsameClient is a client for the Esame schema.
type EsameClient struct {
	config
}

// NewEsameClient returns a client for the Esame from the given config.
func NewEsameClient(c config) *EsameClient {
	return &EsameClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `esame.Hooks(f(g(h())))`.
func (c *EsameClient) Use(hooks ...Hook) {
	c.hooks.Esame = append(c.hooks.Esame, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `esame.Intercept(f(g(h())))`.
func (c *EsameClient) Intercept(interceptors ...Interceptor) {
	c.inters.Esame = append(c.inters.Esame, interceptors...)
}

// Create returns a builder for creating a Esame entity.
func (c *EsameClient) Create() *EsameCreate {
	mutation := newEsameMutation(c.config, OpCreate)
	return &EsameCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Esame entities.
func (c *EsameClient) CreateBulk(builders ...*EsameCreate) *EsameCreateBulk {
	return &EsameCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EsameClient) MapCreateBulk(slice any, setFunc func(*EsameCreate, int)) *EsameCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EsameCreateBulk{err: fmt.Errorf("calling to EsameClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EsameCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EsameCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Esame.
func (c *EsameClient) Update() *EsameUpdate {
	mutation := newEsameMutation(c.config, OpUpdate)
	return &EsameUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EsameClient) UpdateOne(_m *Esame) *EsameUpdateOne {
	mutation := newEsameMutation(c.config, OpUpdateOne, withEsame(_m))
	return &EsameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EsameClient) UpdateOneID(id int) *EsameUpdateOne {
	mutation := newEsameMutation(c.config, OpUpdateOne, withEsameID(id))
	return &EsameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Esame.
func (c *EsameClient) Delete() *EsameDelete {
	mutation := newEsameMutation(c.config, OpDelete)
	return &EsameDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EsameClient) DeleteOne(_m *Esame) *EsameDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EsameClient) DeleteOneID(id int) *EsameDeleteOne {
	builder := c.Delete().Where(esame.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EsameDeleteOne{builder}
}

// Query returns a query builder for Esame.
func (c *EsameClient) Query() *EsameQuery {
	return &EsameQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEsame},
		inters: c.Interceptors(),
	}
}

// Get returns a Esame entity by its id.
func (c *EsameClient) Get(ctx context.Context, id int) (*Esame, error) {
	return c.Query().Where(esame.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EsameClient) GetX(ctx context.Context, id int) *Esame {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUtente queries the utente edge of a Esame.
func (c *EsameClient) QueryUtente(_m *Esame) *UtenteQuery {
	query := (&UtenteClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(esame.Table, esame.FieldID, id),
			sqlgraph.To(utente.Table, utente.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, esame.UtenteTable, esame.UtenteColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryQuesiti queries the quesiti edge of a Esame.
func (c *EsameClient) QueryQuesiti(_m *Esame) *QuesitoEsameQuery {
	query := (&QuesitoEsameClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(esame.Table, esame.FieldID, id),
			sqlgraph.To(quesitoesame.Table, quesitoesame.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, esame.QuesitiTable, esame.QuesitiColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EsameClient) Hooks() []Hook {
	return c.hooks.Esame
}

// Interceptors returns the client interceptors.
func (c *EsameClient) Interceptors() []Interceptor {
	return c.inters.Esame
}

func (c *EsameClient) mutate(ctx context.Context, m *EsameMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EsameCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EsameUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EsameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EsameDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Esame mutation op: %q", m.Op())
	}
}

// QuesitoEsameClient is a client for the QuesitoEsame schema.
type QuesitoEsameClient struct {
	config
}

// NewQuesitoEsameClient returns a client for the QuesitoEsame from the given config.
func NewQuesitoEsameClient(c config) *QuesitoEsameClient {
	return &QuesitoEsameClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `quesitoesame.Hooks(f(g(h())))`.
func (c *QuesitoEsameClient) Use(hooks ...Hook) {
	c.hooks.QuesitoEsame = append(c.hooks.QuesitoEsame, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `quesitoesame.Intercept(f(g(h())))`.
func (c *QuesitoEsameClient) Intercept(interceptors ...Interceptor) {
	c.inters.QuesitoEsame = append(c.inters.QuesitoEsame, interceptors...)
}

// Create returns a builder for creating a QuesitoEsame entity.
func (c *QuesitoEsameClient) Create() *QuesitoEsameCreate {
	mutation := newQuesitoEsameMutation(c.config, OpCreate)
	return &QuesitoEsameCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of QuesitoEsame entities.
func (c *QuesitoEsameClient) CreateBulk(builders ...*QuesitoEsameCreate) *QuesitoEsameCreateBulk {
	return &QuesitoEsameCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *QuesitoEsameClient) MapCreateBulk(slice any, setFunc func(*QuesitoEsameCreate, int)) *QuesitoEsameCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &QuesitoEsameCreateBulk{err: fmt.Errorf("calling to QuesitoEsameClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*QuesitoEsameCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &QuesitoEsameCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for QuesitoEsame.
func (c *QuesitoEsameClient) Update() *QuesitoEsameUpdate {
	mutation := newQuesitoEsameMutation(c.config, OpUpdate)
	return &QuesitoEsameUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *QuesitoEsameClient) UpdateOne(_m *QuesitoEsame) *QuesitoEsameUpdateOne {
	mutation := newQuesitoEsameMutation(c.config, OpUpdateOne, withQuesitoEsame(_m))
	return &QuesitoEsameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *QuesitoEsameClient) UpdateOneID(id int) *QuesitoEsameUpdateOne {
	mutation := newQuesitoEsameMutation(c.config, OpUpdateOne, withQuesitoEsameID(id))
	return &QuesitoEsameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for QuesitoEsame.
func (c *QuesitoEsameClient) Delete() *QuesitoEsameDelete {
	mutation := newQuesitoEsameMutation(c.config, OpDelete)
	return &QuesitoEsameDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *QuesitoEsameClient) DeleteOne(_m *QuesitoEsame) *QuesitoEsameDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *QuesitoEsameClient) DeleteOneID(id int) *QuesitoEsameDeleteOne {
	builder := c.Delete().Where(quesitoesame.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &QuesitoEsameDeleteOne{builder}
}

// Query returns a query builder for QuesitoEsame.
func (c *QuesitoEsameClient) Query() *QuesitoEsameQuery {
	return &QuesitoEsameQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeQuesitoEsame},
		inters: c.Interceptors(),
	}
}

// Get returns a QuesitoEsame entity by its id.
func (c *QuesitoEsameClient) Get(ctx context.Context, id int) (*QuesitoEsame, error) {
	return c.Query().Where(quesitoesame.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *QuesitoEsameClient) GetX(ctx context.Context, id int) *QuesitoEsame {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEsame queries the esame edge of a QuesitoEsame.
func (c *QuesitoEsameClient) QueryEsame(_m *QuesitoEsame) *EsameQuery {
	query := (&EsameClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(quesitoesame.Table, quesitoesame.FieldID, id),
			sqlgraph.To(esame.Table, esame.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, quesitoesame.EsameTable, quesitoesame.EsameColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDomandaOriginale queries the domanda_originale edge of a QuesitoEsame.
func (c *QuesitoEsameClient) QueryDomandaOriginale(_m *QuesitoEsame) *DomandaQuery {
	query := (&DomandaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(quesitoesame.Table, quesitoesame.FieldID, id),
			sqlgraph.To(domanda.Table, domanda.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, quesitoesame.DomandaOriginaleTable, quesitoesame.DomandaOriginaleColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLogs queries the logs edge of a QuesitoEsame.
func (c *QuesitoEsameClient) QueryLogs(_m *QuesitoEsame) *AttivitaQuesitoEsameQuery {
	query := (&AttivitaQuesitoEsameClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(quesitoesame.Table, quesitoesame.FieldID, id),
			sqlgraph.To(attivitaquesitoesame.Table, attivitaquesitoesame.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, quesitoesame.LogsTable, quesitoesame.LogsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *QuesitoEsameClient) Hooks() []Hook {
	return c.hooks.QuesitoEsame
}

// Interceptors returns the client interceptors.
func (c *QuesitoEsameClient) Interceptors() []Interceptor {
	return c.inters.QuesitoEsame
}

func (c *QuesitoEsameClient) mutate(ctx context.Context, m *QuesitoEsameMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&QuesitoEsameCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&QuesitoEsameUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&QuesitoEsameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&QuesitoEsameDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown QuesitoEsame mutation op: %q", m.Op())
	}
}

// SeedClient is a client for the Seed schema.
type SeedClient struct {
	config
}

// NewSeedClient returns a client for the Seed from the given config.
func NewSeedClient(c config) *SeedClient {
	return &SeedClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `seed.Hooks(f(g(h())))`.
func (c *SeedClient) Use(hooks ...Hook) {
	c.hooks.Seed = append(c.hooks.Seed, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `seed.Intercept(f(g(h())))`.
func (c *SeedClient) Intercept(interceptors ...Interceptor) {
	c.inters.Seed = append(c.inters.Seed, interceptors...)
}

// Create returns a builder for creating a Seed entity.
func (c *SeedClient) Create() *SeedCreate {
	mutation := newSeedMutation(c.config, OpCreate)
	return &SeedCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Seed entities.
func (c *SeedClient) CreateBulk(builders ...*SeedCreate) *SeedCreateBulk {
	return &SeedCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SeedClient) MapCreateBulk(slice any, setFunc func(*SeedCreate, int)) *SeedCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SeedCreateBulk{err: fmt.Errorf("calling to SeedClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SeedCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SeedCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Seed.
func (c *SeedClient) Update() *SeedUpdate {
	mutation := newSeedMutation(c.config, OpUpdate)
	return &SeedUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SeedClient) UpdateOne(_m *Seed) *SeedUpdateOne {
	mutation := newSeedMutation(c.config, OpUpdateOne, withSeed(_m))
	return &SeedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SeedClient) UpdateOneID(id int) *SeedUpdateOne {
	mutation := newSeedMutation(c.config, OpUpdateOne, withSeedID(id))
	return &SeedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Seed.
func (c *SeedClient) Delete() *SeedDelete {
	mutation := newSeedMutation(c.config, OpDelete)
	return &SeedDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SeedClient) DeleteOne(_m *Seed) *SeedDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SeedClient) DeleteOneID(id int) *SeedDeleteOne {
	builder := c.Delete().Where(seed.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SeedDeleteOne{builder}
}

// Query returns a query builder for Seed.
func (c *SeedClient) Query() *SeedQuery {
	return &SeedQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSeed},
		inters: c.Interceptors(),
	}
}

// Get returns a Seed entity by its id.
func (c *SeedClient) Get(ctx context.Context, id int) (*Seed, error) {
	return c.Query().Where(seed.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SeedClient) GetX(ctx context.Context, id int) *Seed {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SeedClient) Hooks() []Hook {
	return c.hooks.Seed
}

// Interceptors returns the client interceptors.
func (c *SeedClient) Interceptors() []Interceptor {
	return c.inters.Seed
}

func (c *SeedClient) mutate(ctx context.Context, m *SeedMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SeedCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SeedUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SeedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SeedDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Seed mutation op: %q", m.Op())
	}
}

// UtenteClient is a client for the Utente schema.
type UtenteClient struct {
	config
}

// NewUtenteClient returns a client for the Utente from the given config.
func NewUtenteClient(c config) *UtenteClient {
	return &UtenteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `utente.Hooks(f(g(h())))`.
func (c *UtenteClient) Use(hooks ...Hook) {
	c.hooks.Utente = append(c.hooks.Utente, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `utente.Intercept(f(g(h())))`.
func (c *UtenteClient) Intercept(interceptors ...Interceptor) {
	c.inters.Utente = append(c.inters.Utente, interceptors...)
}

// Create returns a builder for creating a Utente entity.
func (c *UtenteClient) Create() *UtenteCreate {
	mutation := newUtenteMutation(c.config, OpCreate)
	return &UtenteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Utente entities.
func (c *UtenteClient) CreateBulk(builders ...*UtenteCreate) *UtenteCreateBulk {
	return &UtenteCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UtenteClient) MapCreateBulk(slice any, setFunc func(*UtenteCreate, int)) *UtenteCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UtenteCreateBulk{err: fmt.Errorf("calling to UtenteClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UtenteCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UtenteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Utente.
func (c *UtenteClient) Update() *UtenteUpdate {
	mutation := newUtenteMutation(c.config, OpUpdate)
	return &UtenteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UtenteClient) UpdateOne(_m *Utente) *UtenteUpdateOne {
	mutation := newUtenteMutation(c.config, OpUpdateOne, withUtente(_m))
	return &UtenteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UtenteClient) UpdateOneID(id string) *UtenteUpdateOne {
	mutation := newUtenteMutation(c.config, OpUpdateOne, withUtenteID(id))
	return &UtenteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Utente.
func (c *UtenteClient) Delete() *UtenteDelete {
	mutation := newUtenteMutation(c.config, OpDelete)
	return &UtenteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UtenteClient) DeleteOne(_m *Utente) *UtenteDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UtenteClient) DeleteOneID(id string) *UtenteDeleteOne {
	builder := c.Delete().Where(utente.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UtenteDeleteOne{builder}
}

// Query returns a query builder for Utente.
func (c *UtenteClient) Query() *UtenteQuery {
	return &UtenteQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUtente},
		inters: c.Interceptors(),
	}
}

// Get returns a Utente entity by its id.
func (c *UtenteClient) Get(ctx context.Context, id string) (*Utente, error) {
	return c.Query().Where(utente.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UtenteClient) GetX(ctx context.Context, id string) *Utente {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UtenteClient) Hooks() []Hook {
	return c.hooks.Utente
}

// Interceptors returns the client interceptors.
func (c *UtenteClient) Interceptors() []Interceptor {
	return c.inters.Utente
}

func (c *UtenteClient) mutate(ctx context.Context, m *UtenteMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UtenteCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UtenteUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UtenteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UtenteDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Utente mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Argomento, AttivitaQuesitoEsame, Capitolo, Domanda, Esame, QuesitoEsame, Seed,
		Utente []ent.Hook
	}
	inters struct {
		Argomento, AttivitaQuesitoEsame, Capitolo, Domanda, Esame, QuesitoEsame, Seed,
		Utente []ent.Interceptor
	}
)

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
