// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ed-evo/hankinson/server/ent/correzione"
	"github.com/ed-evo/hankinson/server/ent/predicate"
)

// CorrezioneUpdate is the builder for updating Correzione entities.
type CorrezioneUpdate struct {
	config
	hooks    []Hook
	mutation *CorrezioneMutation
}

// Where appends a list predicates to the CorrezioneUpdate builder.
func (_u *CorrezioneUpdate) Where(ps ...predicate.Correzione) *CorrezioneUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *CorrezioneUpdate) SetType(v correzione.Type) *CorrezioneUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CorrezioneUpdate) SetNillableType(v *correzione.Type) *CorrezioneUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetEsaminatore sets the "esaminatore" field.
func (_u *CorrezioneUpdate) SetEsaminatore(v string) *CorrezioneUpdate {
	_u.mutation.SetEsaminatore(v)
	return _u
}

// SetNillableEsaminatore sets the "esaminatore" field if the given value is not nil.
func (_u *CorrezioneUpdate) SetNillableEsaminatore(v *string) *CorrezioneUpdate {
	if v != nil {
		_u.SetEsaminatore(*v)
	}
	return _u
}

// SetIsPromosso sets the "is_promosso" field.
func (_u *CorrezioneUpdate) SetIsPromosso(v bool) *CorrezioneUpdate {
	_u.mutation.SetIsPromosso(v)
	return _u
}

// SetNillableIsPromosso sets the "is_promosso" field if the given value is not nil.
func (_u *CorrezioneUpdate) SetNillableIsPromosso(v *bool) *CorrezioneUpdate {
	if v != nil {
		_u.SetIsPromosso(*v)
	}
	return _u
}

// SetTesto sets the "testo" field.
func (_u *CorrezioneUpdate) SetTesto(v string) *CorrezioneUpdate {
	_u.mutation.SetTesto(v)
	return _u
}

// SetNillableTesto sets the "testo" field if the given value is not nil.
func (_u *CorrezioneUpdate) SetNillableTesto(v *string) *CorrezioneUpdate {
	if v != nil {
		_u.SetTesto(*v)
	}
	return _u
}

// SetMeta sets the "meta" field.
func (_u *CorrezioneUpdate) SetMeta(v string) *CorrezioneUpdate {
	_u.mutation.SetMeta(v)
	return _u
}

// SetNillableMeta sets the "meta" field if the given value is not nil.
func (_u *CorrezioneUpdate) SetNillableMeta(v *string) *CorrezioneUpdate {
	if v != nil {
		_u.SetMeta(*v)
	}
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *CorrezioneUpdate) ClearMeta() *CorrezioneUpdate {
	_u.mutation.ClearMeta()
	return _u
}

// Mutation returns the CorrezioneMutation object of the builder.
func (_u *CorrezioneUpdate) Mutation() *CorrezioneMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CorrezioneUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CorrezioneUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CorrezioneUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CorrezioneUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CorrezioneUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := correzione.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Correzione.type": %w`, err)}
		}
	}
	if _u.mutation.EsameCleared() && len(_u.mutation.EsameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Correzione.esame"`)
	}
	return nil
}

func (_u *CorrezioneUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(correzione.Table, correzione.Columns, sqlgraph.NewFieldSpec(correzione.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(correzione.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Esaminatore(); ok {
		_spec.SetField(correzione.FieldEsaminatore, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPromosso(); ok {
		_spec.SetField(correzione.FieldIsPromosso, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Testo(); ok {
		_spec.SetField(correzione.FieldTesto, field.TypeString, value)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(correzione.FieldMeta, field.TypeString, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(correzione.FieldMeta, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{correzione.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CorrezioneUpdateOne is the builder for updating a single Correzione entity.
type CorrezioneUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CorrezioneMutation
}

// SetType sets the "type" field.
func (_u *CorrezioneUpdateOne) SetType(v correzione.Type) *CorrezioneUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CorrezioneUpdateOne) SetNillableType(v *correzione.Type) *CorrezioneUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetEsaminatore sets the "esaminatore" field.
func (_u *CorrezioneUpdateOne) SetEsaminatore(v string) *CorrezioneUpdateOne {
	_u.mutation.SetEsaminatore(v)
	return _u
}

// SetNillableEsaminatore sets the "esaminatore" field if the given value is not nil.
func (_u *CorrezioneUpdateOne) SetNillableEsaminatore(v *string) *CorrezioneUpdateOne {
	if v != nil {
		_u.SetEsaminatore(*v)
	}
	return _u
}

// SetIsPromosso sets the "is_promosso" field.
func (_u *CorrezioneUpdateOne) SetIsPromosso(v bool) *CorrezioneUpdateOne {
	_u.mutation.SetIsPromosso(v)
	return _u
}

// SetNillableIsPromosso sets the "is_promosso" field if the given value is not nil.
func (_u *CorrezioneUpdateOne) SetNillableIsPromosso(v *bool) *CorrezioneUpdateOne {
	if v != nil {
		_u.SetIsPromosso(*v)
	}
	return _u
}

// SetTesto sets the "testo" field.
func (_u *CorrezioneUpdateOne) SetTesto(v string) *CorrezioneUpdateOne {
	_u.mutation.SetTesto(v)
	return _u
}

// SetNillableTesto sets the "testo" field if the given value is not nil.
func (_u *CorrezioneUpdateOne) SetNillableTesto(v *string) *CorrezioneUpdateOne {
	if v != nil {
		_u.SetTesto(*v)
	}
	return _u
}

// SetMeta sets the "meta" field.
func (_u *CorrezioneUpdateOne) SetMeta(v string) *CorrezioneUpdateOne {
	_u.mutation.SetMeta(v)
	return _u
}

// SetNillableMeta sets the "meta" field if the given value is not nil.
func (_u *CorrezioneUpdateOne) SetNillableMeta(v *string) *CorrezioneUpdateOne {
	if v != nil {
		_u.SetMeta(*v)
	}
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *CorrezioneUpdateOne) ClearMeta() *CorrezioneUpdateOne {
	_u.mutation.ClearMeta()
	return _u
}

// Mutation returns the CorrezioneMutation object of the builder.
func (_u *CorrezioneUpdateOne) Mutation() *CorrezioneMutation {
	return _u.mutation
}

// Where appends a list predicates to the CorrezioneUpdate builder.
func (_u *CorrezioneUpdateOne) Where(ps ...predicate.Correzione) *CorrezioneUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CorrezioneUpdateOne) Select(field string, fields ...string) *CorrezioneUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Correzione entity.
func (_u *CorrezioneUpdateOne) Save(ctx context.Context) (*Correzione, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CorrezioneUpdateOne) SaveX(ctx context.Context) *Correzione {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CorrezioneUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CorrezioneUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CorrezioneUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := correzione.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Correzione.type": %w`, err)}
		}
	}
	if _u.mutation.EsameCleared() && len(_u.mutation.EsameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Correzione.esame"`)
	}
	return nil
}

func (_u *CorrezioneUpdateOne) sqlSave(ctx context.Context) (_node *Correzione, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(correzione.Table, correzione.Columns, sqlgraph.NewFieldSpec(correzione.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Correzione.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, correzione.FieldID)
		for _, f := range fields {
			if !correzione.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != correzione.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(correzione.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Esaminatore(); ok {
		_spec.SetField(correzione.FieldEsaminatore, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPromosso(); ok {
		_spec.SetField(correzione.FieldIsPromosso, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Testo(); ok {
		_spec.SetField(correzione.FieldTesto, field.TypeString, value)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(correzione.FieldMeta, field.TypeString, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(correzione.FieldMeta, field.TypeString)
	}
	_node = &Correzione{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{correzione.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
