// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ed-evo/hankinson/server/ent/correzione"
	"github.com/ed-evo/hankinson/server/ent/esame"
)

// Correzione is the model entity for the Correzione schema.
type Correzione struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EsameID holds the value of the "esame_id" field.
	EsameID int `json:"esame_id,omitempty"`
	// Type holds the value of the "type" field.
	Type correzione.Type `json:"type,omitempty"`
	// Esaminatore holds the value of the "esaminatore" field.
	Esaminatore string `json:"esaminatore,omitempty"`
	// IsPromosso holds the value of the "is_promosso" field.
	IsPromosso bool `json:"is_promosso"`
	// Testo holds the value of the "testo" field.
	Testo string `json:"testo,omitempty"`
	// Meta holds the value of the "meta" field.
	Meta string `json:"meta,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CorrezioneQuery when eager-loading is set.
	Edges        CorrezioneEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CorrezioneEdges holds the relations/edges for other nodes in the graph.
type CorrezioneEdges struct {
	// Esame holds the value of the esame edge.
	Esame *Esame `json:"esame,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EsameOrErr returns the Esame value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CorrezioneEdges) EsameOrErr() (*Esame, error) {
	if e.Esame != nil {
		return e.Esame, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: esame.Label}
	}
	return nil, &NotLoadedError{edge: "esame"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Correzione) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case correzione.FieldIsPromosso:
			values[i] = new(sql.NullBool)
		case correzione.FieldID, correzione.FieldEsameID:
			values[i] = new(sql.NullInt64)
		case correzione.FieldType, correzione.FieldEsaminatore, correzione.FieldTesto, correzione.FieldMeta:
			values[i] = new(sql.NullString)
		case correzione.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Correzione fields.
func (_m *Correzione) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case correzione.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case correzione.FieldEsameID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field esame_id", values[i])
			} else if value.Valid {
				_m.EsameID = int(value.Int64)
			}
		case correzione.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = correzione.Type(value.String)
			}
		case correzione.FieldEsaminatore:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field esaminatore", values[i])
			} else if value.Valid {
				_m.Esaminatore = value.String
			}
		case correzione.FieldIsPromosso:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_promosso", values[i])
			} else if value.Valid {
				_m.IsPromosso = value.Bool
			}
		case correzione.FieldTesto:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field testo", values[i])
			} else if value.Valid {
				_m.Testo = value.String
			}
		case correzione.FieldMeta:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field meta", values[i])
			} else if value.Valid {
				_m.Meta = value.String
			}
		case correzione.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Correzione.
// This includes values selected through modifiers, order, etc.
func (_m *Correzione) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEsame queries the "esame" edge of the Correzione entity.
func (_m *Correzione) QueryEsame() *EsameQuery {
	return NewCorrezioneClient(_m.config).QueryEsame(_m)
}

// Update returns a builder for updating this Correzione.
// Note that you need to call Correzione.Unwrap() before calling this method if this Correzione
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Correzione) Update() *CorrezioneUpdateOne {
	return NewCorrezioneClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Correzione entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Correzione) Unwrap() *Correzione {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Correzione is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Correzione) String() string {
	var builder strings.Builder
	builder.WriteString("Correzione(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("esame_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EsameID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("esaminatore=")
	builder.WriteString(_m.Esaminatore)
	builder.WriteString(", ")
	builder.WriteString("is_promosso=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPromosso))
	builder.WriteString(", ")
	builder.WriteString("testo=")
	builder.WriteString(_m.Testo)
	builder.WriteString(", ")
	builder.WriteString("meta=")
	builder.WriteString(_m.Meta)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Correziones is a parsable slice of Correzione.
type Correziones []*Correzione
