// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ed-evo/hankinson/server/ent/capitolo"
	"github.com/ed-evo/hankinson/server/ent/domanda"
)

// Domanda is the model entity for the Domanda schema.
type Domanda struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Testo holds the value of the "testo" field.
	Testo string `json:"testo,omitempty"`
	// IsTrue holds the value of the "is_true" field.
	IsTrue bool `json:"is_true"`
	// Immagine holds the value of the "immagine" field.
	Immagine *string `json:"immagine,omitempty"`
	// IDCapitolo holds the value of the "id_capitolo" field.
	IDCapitolo int `json:"id_capitolo,omitempty"`
	// PaginaQuiz holds the value of the "pagina_quiz" field.
	PaginaQuiz int `json:"pagina_quiz,omitempty"`
	// IDBlocco holds the value of the "id_blocco" field.
	IDBlocco int `json:"id_blocco,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DomandaQuery when eager-loading is set.
	Edges        DomandaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DomandaEdges holds the relations/edges for other nodes in the graph.
type DomandaEdges struct {
	// Argomenti holds the value of the argomenti edge.
	Argomenti []*Argomento `json:"argomenti,omitempty"`
	// Capitolo holds the value of the capitolo edge.
	Capitolo *Capitolo `json:"capitolo,omitempty"`
	// Spiegazione holds the value of the spiegazione edge.
	Spiegazione []*Spiegazione `json:"spiegazione,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ArgomentiOrErr returns the Argomenti value or an error if the edge
// was not loaded in eager-loading.
func (e DomandaEdges) ArgomentiOrErr() ([]*Argomento, error) {
	if e.loadedTypes[0] {
		return e.Argomenti, nil
	}
	return nil, &NotLoadedError{edge: "argomenti"}
}

// CapitoloOrErr returns the Capitolo value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DomandaEdges) CapitoloOrErr() (*Capitolo, error) {
	if e.Capitolo != nil {
		return e.Capitolo, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: capitolo.Label}
	}
	return nil, &NotLoadedError{edge: "capitolo"}
}

// SpiegazioneOrErr returns the Spiegazione value or an error if the edge
// was not loaded in eager-loading.
func (e DomandaEdges) SpiegazioneOrErr() ([]*Spiegazione, error) {
	if e.loadedTypes[2] {
		return e.Spiegazione, nil
	}
	return nil, &NotLoadedError{edge: "spiegazione"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Domanda) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case domanda.FieldIsTrue:
			values[i] = new(sql.NullBool)
		case domanda.FieldID, domanda.FieldIDCapitolo, domanda.FieldPaginaQuiz, domanda.FieldIDBlocco:
			values[i] = new(sql.NullInt64)
		case domanda.FieldTesto, domanda.FieldImmagine:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Domanda fields.
func (_m *Domanda) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case domanda.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case domanda.FieldTesto:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field testo", values[i])
			} else if value.Valid {
				_m.Testo = value.String
			}
		case domanda.FieldIsTrue:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_true", values[i])
			} else if value.Valid {
				_m.IsTrue = value.Bool
			}
		case domanda.FieldImmagine:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field immagine", values[i])
			} else if value.Valid {
				_m.Immagine = new(string)
				*_m.Immagine = value.String
			}
		case domanda.FieldIDCapitolo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id_capitolo", values[i])
			} else if value.Valid {
				_m.IDCapitolo = int(value.Int64)
			}
		case domanda.FieldPaginaQuiz:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pagina_quiz", values[i])
			} else if value.Valid {
				_m.PaginaQuiz = int(value.Int64)
			}
		case domanda.FieldIDBlocco:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id_blocco", values[i])
			} else if value.Valid {
				_m.IDBlocco = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Domanda.
// This includes values selected through modifiers, order, etc.
func (_m *Domanda) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryArgomenti queries the "argomenti" edge of the Domanda entity.
func (_m *Domanda) QueryArgomenti() *ArgomentoQuery {
	return NewDomandaClient(_m.config).QueryArgomenti(_m)
}

// QueryCapitolo queries the "capitolo" edge of the Domanda entity.
func (_m *Domanda) QueryCapitolo() *CapitoloQuery {
	return NewDomandaClient(_m.config).QueryCapitolo(_m)
}

// QuerySpiegazione queries the "spiegazione" edge of the Domanda entity.
func (_m *Domanda) QuerySpiegazione() *SpiegazioneQuery {
	return NewDomandaClient(_m.config).QuerySpiegazione(_m)
}

// Update returns a builder for updating this Domanda.
// Note that you need to call Domanda.Unwrap() before calling this method if this Domanda
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Domanda) Update() *DomandaUpdateOne {
	return NewDomandaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Domanda entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Domanda) Unwrap() *Domanda {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Domanda is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Domanda) String() string {
	var builder strings.Builder
	builder.WriteString("Domanda(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("testo=")
	builder.WriteString(_m.Testo)
	builder.WriteString(", ")
	builder.WriteString("is_true=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsTrue))
	builder.WriteString(", ")
	if v := _m.Immagine; v != nil {
		builder.WriteString("immagine=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("id_capitolo=")
	builder.WriteString(fmt.Sprintf("%v", _m.IDCapitolo))
	builder.WriteString(", ")
	builder.WriteString("pagina_quiz=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaginaQuiz))
	builder.WriteString(", ")
	builder.WriteString("id_blocco=")
	builder.WriteString(fmt.Sprintf("%v", _m.IDBlocco))
	builder.WriteByte(')')
	return builder.String()
}

// Domandas is a parsable slice of Domanda.
type Domandas []*Domanda
