// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ed-evo/hankinson/server/ent/esame"
	"github.com/ed-evo/hankinson/server/ent/quesitoesame"
	"github.com/ed-evo/hankinson/server/ent/utente"
)

// EsameCreate is the builder for creating a Esame entity.
type EsameCreate struct {
	config
	mutation *EsameMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTipo sets the "tipo" field.
func (_c *EsameCreate) SetTipo(v esame.Tipo) *EsameCreate {
	_c.mutation.SetTipo(v)
	return _c
}

// SetNumeroQuesiti sets the "numero_quesiti" field.
func (_c *EsameCreate) SetNumeroQuesiti(v int) *EsameCreate {
	_c.mutation.SetNumeroQuesiti(v)
	return _c
}

// SetMaxErrori sets the "max_errori" field.
func (_c *EsameCreate) SetMaxErrori(v int) *EsameCreate {
	_c.mutation.SetMaxErrori(v)
	return _c
}

// SetNillableMaxErrori sets the "max_errori" field if the given value is not nil.
func (_c *EsameCreate) SetNillableMaxErrori(v *int) *EsameCreate {
	if v != nil {
		_c.SetMaxErrori(*v)
	}
	return _c
}

// SetMinutiDisponibili sets the "minuti_disponibili" field.
func (_c *EsameCreate) SetMinutiDisponibili(v int) *EsameCreate {
	_c.mutation.SetMinutiDisponibili(v)
	return _c
}

// SetNillableMinutiDisponibili sets the "minuti_disponibili" field if the given value is not nil.
func (_c *EsameCreate) SetNillableMinutiDisponibili(v *int) *EsameCreate {
	if v != nil {
		_c.SetMinutiDisponibili(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EsameCreate) SetCreatedAt(v time.Time) *EsameCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EsameCreate) SetNillableCreatedAt(v *time.Time) *EsameCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EsameCreate) SetUpdatedAt(v time.Time) *EsameCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EsameCreate) SetNillableUpdatedAt(v *time.Time) *EsameCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUtenteID sets the "utente" edge to the Utente entity by ID.
func (_c *EsameCreate) SetUtenteID(id string) *EsameCreate {
	_c.mutation.SetUtenteID(id)
	return _c
}

// SetUtente sets the "utente" edge to the Utente entity.
func (_c *EsameCreate) SetUtente(v *Utente) *EsameCreate {
	return _c.SetUtenteID(v.ID)
}

// AddQuesitiIDs adds the "quesiti" edge to the QuesitoEsame entity by IDs.
func (_c *EsameCreate) AddQuesitiIDs(ids ...int) *EsameCreate {
	_c.mutation.AddQuesitiIDs(ids...)
	return _c
}

// AddQuesiti adds the "quesiti" edges to the QuesitoEsame entity.
func (_c *EsameCreate) AddQuesiti(v ...*QuesitoEsame) *EsameCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddQuesitiIDs(ids...)
}

// Mutation returns the EsameMutation object of the builder.
func (_c *EsameCreate) Mutation() *EsameMutation {
	return _c.mutation
}

// Save creates the Esame in the database.
func (_c *EsameCreate) Save(ctx context.Context) (*Esame, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EsameCreate) SaveX(ctx context.Context) *Esame {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EsameCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EsameCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EsameCreate) defaults() {
	if _, ok := _c.mutation.MaxErrori(); !ok {
		v := esame.DefaultMaxErrori
		_c.mutation.SetMaxErrori(v)
	}
	if _, ok := _c.mutation.MinutiDisponibili(); !ok {
		v := esame.DefaultMinutiDisponibili
		_c.mutation.SetMinutiDisponibili(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := esame.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := esame.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EsameCreate) check() error {
	if _, ok := _c.mutation.Tipo(); !ok {
		return &ValidationError{Name: "tipo", err: errors.New(`ent: missing required field "Esame.tipo"`)}
	}
	if v, ok := _c.mutation.Tipo(); ok {
		if err := esame.TipoValidator(v); err != nil {
			return &ValidationError{Name: "tipo", err: fmt.Errorf(`ent: validator failed for field "Esame.tipo": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NumeroQuesiti(); !ok {
		return &ValidationError{Name: "numero_quesiti", err: errors.New(`ent: missing required field "Esame.numero_quesiti"`)}
	}
	if _, ok := _c.mutation.MaxErrori(); !ok {
		return &ValidationError{Name: "max_errori", err: errors.New(`ent: missing required field "Esame.max_errori"`)}
	}
	if _, ok := _c.mutation.MinutiDisponibili(); !ok {
		return &ValidationError{Name: "minuti_disponibili", err: errors.New(`ent: missing required field "Esame.minuti_disponibili"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Esame.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Esame.updated_at"`)}
	}
	if len(_c.mutation.UtenteIDs()) == 0 {
		return &ValidationError{Name: "utente", err: errors.New(`ent: missing required edge "Esame.utente"`)}
	}
	return nil
}

func (_c *EsameCreate) sqlSave(ctx context.Context) (*Esame, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EsameCreate) createSpec() (*Esame, *sqlgraph.CreateSpec) {
	var (
		_node = &Esame{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(esame.Table, sqlgraph.NewFieldSpec(esame.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Tipo(); ok {
		_spec.SetField(esame.FieldTipo, field.TypeEnum, value)
		_node.Tipo = value
	}
	if value, ok := _c.mutation.NumeroQuesiti(); ok {
		_spec.SetField(esame.FieldNumeroQuesiti, field.TypeInt, value)
		_node.NumeroQuesiti = value
	}
	if value, ok := _c.mutation.MaxErrori(); ok {
		_spec.SetField(esame.FieldMaxErrori, field.TypeInt, value)
		_node.MaxErrori = value
	}
	if value, ok := _c.mutation.MinutiDisponibili(); ok {
		_spec.SetField(esame.FieldMinutiDisponibili, field.TypeInt, value)
		_node.MinutiDisponibili = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(esame.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(esame.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UtenteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   esame.UtenteTable,
			Columns: []string{esame.UtenteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(utente.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.esame_utente = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.QuesitiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.QuesitiTable,
			Columns: []string{esame.QuesitiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Esame.Create().
//		SetTipo(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EsameUpsert) {
//			SetTipo(v+v).
//		}).
//		Exec(ctx)
func (_c *EsameCreate) OnConflict(opts ...sql.ConflictOption) *EsameUpsertOne {
	_c.conflict = opts
	return &EsameUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Esame.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EsameCreate) OnConflictColumns(columns ...string) *EsameUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EsameUpsertOne{
		create: _c,
	}
}

type (
	// EsameUpsertOne is the builder for "upsert"-ing
	//  one Esame node.
	EsameUpsertOne struct {
		create *EsameCreate
	}

	// EsameUpsert is the "OnConflict" setter.
	EsameUpsert struct {
		*sql.UpdateSet
	}
)

// SetTipo sets the "tipo" field.
func (u *EsameUpsert) SetTipo(v esame.Tipo) *EsameUpsert {
	u.Set(esame.FieldTipo, v)
	return u
}

// UpdateTipo sets the "tipo" field to the value that was provided on create.
func (u *EsameUpsert) UpdateTipo() *EsameUpsert {
	u.SetExcluded(esame.FieldTipo)
	return u
}

// SetNumeroQuesiti sets the "numero_quesiti" field.
func (u *EsameUpsert) SetNumeroQuesiti(v int) *EsameUpsert {
	u.Set(esame.FieldNumeroQuesiti, v)
	return u
}

// UpdateNumeroQuesiti sets the "numero_quesiti" field to the value that was provided on create.
func (u *EsameUpsert) UpdateNumeroQuesiti() *EsameUpsert {
	u.SetExcluded(esame.FieldNumeroQuesiti)
	return u
}

// AddNumeroQuesiti adds v to the "numero_quesiti" field.
func (u *EsameUpsert) AddNumeroQuesiti(v int) *EsameUpsert {
	u.Add(esame.FieldNumeroQuesiti, v)
	return u
}

// SetMaxErrori sets the "max_errori" field.
func (u *EsameUpsert) SetMaxErrori(v int) *EsameUpsert {
	u.Set(esame.FieldMaxErrori, v)
	return u
}

// UpdateMaxErrori sets the "max_errori" field to the value that was provided on create.
func (u *EsameUpsert) UpdateMaxErrori() *EsameUpsert {
	u.SetExcluded(esame.FieldMaxErrori)
	return u
}

// AddMaxErrori adds v to the "max_errori" field.
func (u *EsameUpsert) AddMaxErrori(v int) *EsameUpsert {
	u.Add(esame.FieldMaxErrori, v)
	return u
}

// SetMinutiDisponibili sets the "minuti_disponibili" field.
func (u *EsameUpsert) SetMinutiDisponibili(v int) *EsameUpsert {
	u.Set(esame.FieldMinutiDisponibili, v)
	return u
}

// UpdateMinutiDisponibili sets the "minuti_disponibili" field to the value that was provided on create.
func (u *EsameUpsert) UpdateMinutiDisponibili() *EsameUpsert {
	u.SetExcluded(esame.FieldMinutiDisponibili)
	return u
}

// AddMinutiDisponibili adds v to the "minuti_disponibili" field.
func (u *EsameUpsert) AddMinutiDisponibili(v int) *EsameUpsert {
	u.Add(esame.FieldMinutiDisponibili, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *EsameUpsert) SetCreatedAt(v time.Time) *EsameUpsert {
	u.Set(esame.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EsameUpsert) UpdateCreatedAt() *EsameUpsert {
	u.SetExcluded(esame.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EsameUpsert) SetUpdatedAt(v time.Time) *EsameUpsert {
	u.Set(esame.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EsameUpsert) UpdateUpdatedAt() *EsameUpsert {
	u.SetExcluded(esame.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Esame.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EsameUpsertOne) UpdateNewValues() *EsameUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Esame.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EsameUpsertOne) Ignore() *EsameUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EsameUpsertOne) DoNothing() *EsameUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EsameCreate.OnConflict
// documentation for more info.
func (u *EsameUpsertOne) Update(set func(*EsameUpsert)) *EsameUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EsameUpsert{UpdateSet: update})
	}))
	return u
}

// SetTipo sets the "tipo" field.
func (u *EsameUpsertOne) SetTipo(v esame.Tipo) *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.SetTipo(v)
	})
}

// UpdateTipo sets the "tipo" field to the value that was provided on create.
func (u *EsameUpsertOne) UpdateTipo() *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateTipo()
	})
}

// SetNumeroQuesiti sets the "numero_quesiti" field.
func (u *EsameUpsertOne) SetNumeroQuesiti(v int) *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.SetNumeroQuesiti(v)
	})
}

// AddNumeroQuesiti adds v to the "numero_quesiti" field.
func (u *EsameUpsertOne) AddNumeroQuesiti(v int) *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.AddNumeroQuesiti(v)
	})
}

// UpdateNumeroQuesiti sets the "numero_quesiti" field to the value that was provided on create.
func (u *EsameUpsertOne) UpdateNumeroQuesiti() *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateNumeroQuesiti()
	})
}

// SetMaxErrori sets the "max_errori" field.
func (u *EsameUpsertOne) SetMaxErrori(v int) *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.SetMaxErrori(v)
	})
}

// AddMaxErrori adds v to the "max_errori" field.
func (u *EsameUpsertOne) AddMaxErrori(v int) *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.AddMaxErrori(v)
	})
}

// UpdateMaxErrori sets the "max_errori" field to the value that was provided on create.
func (u *EsameUpsertOne) UpdateMaxErrori() *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateMaxErrori()
	})
}

// SetMinutiDisponibili sets the "minuti_disponibili" field.
func (u *EsameUpsertOne) SetMinutiDisponibili(v int) *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.SetMinutiDisponibili(v)
	})
}

// AddMinutiDisponibili adds v to the "minuti_disponibili" field.
func (u *EsameUpsertOne) AddMinutiDisponibili(v int) *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.AddMinutiDisponibili(v)
	})
}

// UpdateMinutiDisponibili sets the "minuti_disponibili" field to the value that was provided on create.
func (u *EsameUpsertOne) UpdateMinutiDisponibili() *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateMinutiDisponibili()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *EsameUpsertOne) SetCreatedAt(v time.Time) *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EsameUpsertOne) UpdateCreatedAt() *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EsameUpsertOne) SetUpdatedAt(v time.Time) *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EsameUpsertOne) UpdateUpdatedAt() *EsameUpsertOne {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EsameUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EsameCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EsameUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EsameUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EsameUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EsameCreateBulk is the builder for creating many Esame entities in bulk.
type EsameCreateBulk struct {
	config
	err      error
	builders []*EsameCreate
	conflict []sql.ConflictOption
}

// Save creates the Esame entities in the database.
func (_c *EsameCreateBulk) Save(ctx context.Context) ([]*Esame, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Esame, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EsameMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EsameCreateBulk) SaveX(ctx context.Context) []*Esame {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EsameCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EsameCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Esame.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EsameUpsert) {
//			SetTipo(v+v).
//		}).
//		Exec(ctx)
func (_c *EsameCreateBulk) OnConflict(opts ...sql.ConflictOption) *EsameUpsertBulk {
	_c.conflict = opts
	return &EsameUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Esame.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EsameCreateBulk) OnConflictColumns(columns ...string) *EsameUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EsameUpsertBulk{
		create: _c,
	}
}

// EsameUpsertBulk is the builder for "upsert"-ing
// a bulk of Esame nodes.
type EsameUpsertBulk struct {
	create *EsameCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Esame.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EsameUpsertBulk) UpdateNewValues() *EsameUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Esame.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EsameUpsertBulk) Ignore() *EsameUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EsameUpsertBulk) DoNothing() *EsameUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EsameCreateBulk.OnConflict
// documentation for more info.
func (u *EsameUpsertBulk) Update(set func(*EsameUpsert)) *EsameUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EsameUpsert{UpdateSet: update})
	}))
	return u
}

// SetTipo sets the "tipo" field.
func (u *EsameUpsertBulk) SetTipo(v esame.Tipo) *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.SetTipo(v)
	})
}

// UpdateTipo sets the "tipo" field to the value that was provided on create.
func (u *EsameUpsertBulk) UpdateTipo() *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateTipo()
	})
}

// SetNumeroQuesiti sets the "numero_quesiti" field.
func (u *EsameUpsertBulk) SetNumeroQuesiti(v int) *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.SetNumeroQuesiti(v)
	})
}

// AddNumeroQuesiti adds v to the "numero_quesiti" field.
func (u *EsameUpsertBulk) AddNumeroQuesiti(v int) *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.AddNumeroQuesiti(v)
	})
}

// UpdateNumeroQuesiti sets the "numero_quesiti" field to the value that was provided on create.
func (u *EsameUpsertBulk) UpdateNumeroQuesiti() *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateNumeroQuesiti()
	})
}

// SetMaxErrori sets the "max_errori" field.
func (u *EsameUpsertBulk) SetMaxErrori(v int) *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.SetMaxErrori(v)
	})
}

// AddMaxErrori adds v to the "max_errori" field.
func (u *EsameUpsertBulk) AddMaxErrori(v int) *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.AddMaxErrori(v)
	})
}

// UpdateMaxErrori sets the "max_errori" field to the value that was provided on create.
func (u *EsameUpsertBulk) UpdateMaxErrori() *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateMaxErrori()
	})
}

// SetMinutiDisponibili sets the "minuti_disponibili" field.
func (u *EsameUpsertBulk) SetMinutiDisponibili(v int) *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.SetMinutiDisponibili(v)
	})
}

// AddMinutiDisponibili adds v to the "minuti_disponibili" field.
func (u *EsameUpsertBulk) AddMinutiDisponibili(v int) *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.AddMinutiDisponibili(v)
	})
}

// UpdateMinutiDisponibili sets the "minuti_disponibili" field to the value that was provided on create.
func (u *EsameUpsertBulk) UpdateMinutiDisponibili() *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateMinutiDisponibili()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *EsameUpsertBulk) SetCreatedAt(v time.Time) *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EsameUpsertBulk) UpdateCreatedAt() *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EsameUpsertBulk) SetUpdatedAt(v time.Time) *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EsameUpsertBulk) UpdateUpdatedAt() *EsameUpsertBulk {
	return u.Update(func(s *EsameUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EsameUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EsameCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EsameCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EsameUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
