// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ed-evo/hankinson/server/ent/esame"
	"github.com/ed-evo/hankinson/server/ent/utente"
)

// Esame is the model entity for the Esame schema.
type Esame struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Tipo holds the value of the "tipo" field.
	Tipo esame.Tipo `json:"tipo,omitempty"`
	// NumeroQuesiti holds the value of the "numero_quesiti" field.
	NumeroQuesiti int `json:"numero_quesiti,omitempty"`
	// MaxErrori holds the value of the "max_errori" field.
	MaxErrori int `json:"max_errori,omitempty"`
	// MinutiDisponibili holds the value of the "minuti_disponibili" field.
	MinutiDisponibili int `json:"minuti_disponibili,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EsameQuery when eager-loading is set.
	Edges        EsameEdges `json:"edges"`
	esame_utente *string
	selectValues sql.SelectValues
}

// EsameEdges holds the relations/edges for other nodes in the graph.
type EsameEdges struct {
	// Utente holds the value of the utente edge.
	Utente *Utente `json:"utente,omitempty"`
	// Quesiti holds the value of the quesiti edge.
	Quesiti []*QuesitoEsame `json:"quesiti,omitempty"`
	// Correzioni holds the value of the correzioni edge.
	Correzioni []*Correzione `json:"correzioni,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UtenteOrErr returns the Utente value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EsameEdges) UtenteOrErr() (*Utente, error) {
	if e.Utente != nil {
		return e.Utente, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: utente.Label}
	}
	return nil, &NotLoadedError{edge: "utente"}
}

// QuesitiOrErr returns the Quesiti value or an error if the edge
// was not loaded in eager-loading.
func (e EsameEdges) QuesitiOrErr() ([]*QuesitoEsame, error) {
	if e.loadedTypes[1] {
		return e.Quesiti, nil
	}
	return nil, &NotLoadedError{edge: "quesiti"}
}

// CorrezioniOrErr returns the Correzioni value or an error if the edge
// was not loaded in eager-loading.
func (e EsameEdges) CorrezioniOrErr() ([]*Correzione, error) {
	if e.loadedTypes[2] {
		return e.Correzioni, nil
	}
	return nil, &NotLoadedError{edge: "correzioni"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Esame) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case esame.FieldID, esame.FieldNumeroQuesiti, esame.FieldMaxErrori, esame.FieldMinutiDisponibili:
			values[i] = new(sql.NullInt64)
		case esame.FieldTipo:
			values[i] = new(sql.NullString)
		case esame.FieldCreatedAt, esame.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case esame.ForeignKeys[0]: // esame_utente
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Esame fields.
func (_m *Esame) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case esame.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case esame.FieldTipo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tipo", values[i])
			} else if value.Valid {
				_m.Tipo = esame.Tipo(value.String)
			}
		case esame.FieldNumeroQuesiti:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field numero_quesiti", values[i])
			} else if value.Valid {
				_m.NumeroQuesiti = int(value.Int64)
			}
		case esame.FieldMaxErrori:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_errori", values[i])
			} else if value.Valid {
				_m.MaxErrori = int(value.Int64)
			}
		case esame.FieldMinutiDisponibili:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field minuti_disponibili", values[i])
			} else if value.Valid {
				_m.MinutiDisponibili = int(value.Int64)
			}
		case esame.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case esame.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case esame.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field esame_utente", values[i])
			} else if value.Valid {
				_m.esame_utente = new(string)
				*_m.esame_utente = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Esame.
// This includes values selected through modifiers, order, etc.
func (_m *Esame) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUtente queries the "utente" edge of the Esame entity.
func (_m *Esame) QueryUtente() *UtenteQuery {
	return NewEsameClient(_m.config).QueryUtente(_m)
}

// QueryQuesiti queries the "quesiti" edge of the Esame entity.
func (_m *Esame) QueryQuesiti() *QuesitoEsameQuery {
	return NewEsameClient(_m.config).QueryQuesiti(_m)
}

// QueryCorrezioni queries the "correzioni" edge of the Esame entity.
func (_m *Esame) QueryCorrezioni() *CorrezioneQuery {
	return NewEsameClient(_m.config).QueryCorrezioni(_m)
}

// Update returns a builder for updating this Esame.
// Note that you need to call Esame.Unwrap() before calling this method if this Esame
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Esame) Update() *EsameUpdateOne {
	return NewEsameClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Esame entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Esame) Unwrap() *Esame {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Esame is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Esame) String() string {
	var builder strings.Builder
	builder.WriteString("Esame(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tipo=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tipo))
	builder.WriteString(", ")
	builder.WriteString("numero_quesiti=")
	builder.WriteString(fmt.Sprintf("%v", _m.NumeroQuesiti))
	builder.WriteString(", ")
	builder.WriteString("max_errori=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxErrori))
	builder.WriteString(", ")
	builder.WriteString("minuti_disponibili=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinutiDisponibili))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Esames is a parsable slice of Esame.
type Esames []*Esame
