// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ed-evo/hankinson/server/ent/correzione"
	"github.com/ed-evo/hankinson/server/ent/esame"
	"github.com/ed-evo/hankinson/server/ent/predicate"
	"github.com/ed-evo/hankinson/server/ent/quesitoesame"
	"github.com/ed-evo/hankinson/server/ent/utente"
)

// EsameUpdate is the builder for updating Esame entities.
type EsameUpdate struct {
	config
	hooks    []Hook
	mutation *EsameMutation
}

// Where appends a list predicates to the EsameUpdate builder.
func (_u *EsameUpdate) Where(ps ...predicate.Esame) *EsameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTipo sets the "tipo" field.
func (_u *EsameUpdate) SetTipo(v esame.Tipo) *EsameUpdate {
	_u.mutation.SetTipo(v)
	return _u
}

// SetNillableTipo sets the "tipo" field if the given value is not nil.
func (_u *EsameUpdate) SetNillableTipo(v *esame.Tipo) *EsameUpdate {
	if v != nil {
		_u.SetTipo(*v)
	}
	return _u
}

// SetNumeroQuesiti sets the "numero_quesiti" field.
func (_u *EsameUpdate) SetNumeroQuesiti(v int) *EsameUpdate {
	_u.mutation.ResetNumeroQuesiti()
	_u.mutation.SetNumeroQuesiti(v)
	return _u
}

// SetNillableNumeroQuesiti sets the "numero_quesiti" field if the given value is not nil.
func (_u *EsameUpdate) SetNillableNumeroQuesiti(v *int) *EsameUpdate {
	if v != nil {
		_u.SetNumeroQuesiti(*v)
	}
	return _u
}

// AddNumeroQuesiti adds value to the "numero_quesiti" field.
func (_u *EsameUpdate) AddNumeroQuesiti(v int) *EsameUpdate {
	_u.mutation.AddNumeroQuesiti(v)
	return _u
}

// SetMaxErrori sets the "max_errori" field.
func (_u *EsameUpdate) SetMaxErrori(v int) *EsameUpdate {
	_u.mutation.ResetMaxErrori()
	_u.mutation.SetMaxErrori(v)
	return _u
}

// SetNillableMaxErrori sets the "max_errori" field if the given value is not nil.
func (_u *EsameUpdate) SetNillableMaxErrori(v *int) *EsameUpdate {
	if v != nil {
		_u.SetMaxErrori(*v)
	}
	return _u
}

// AddMaxErrori adds value to the "max_errori" field.
func (_u *EsameUpdate) AddMaxErrori(v int) *EsameUpdate {
	_u.mutation.AddMaxErrori(v)
	return _u
}

// SetMinutiDisponibili sets the "minuti_disponibili" field.
func (_u *EsameUpdate) SetMinutiDisponibili(v int) *EsameUpdate {
	_u.mutation.ResetMinutiDisponibili()
	_u.mutation.SetMinutiDisponibili(v)
	return _u
}

// SetNillableMinutiDisponibili sets the "minuti_disponibili" field if the given value is not nil.
func (_u *EsameUpdate) SetNillableMinutiDisponibili(v *int) *EsameUpdate {
	if v != nil {
		_u.SetMinutiDisponibili(*v)
	}
	return _u
}

// AddMinutiDisponibili adds value to the "minuti_disponibili" field.
func (_u *EsameUpdate) AddMinutiDisponibili(v int) *EsameUpdate {
	_u.mutation.AddMinutiDisponibili(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EsameUpdate) SetCreatedAt(v time.Time) *EsameUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EsameUpdate) SetNillableCreatedAt(v *time.Time) *EsameUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EsameUpdate) SetUpdatedAt(v time.Time) *EsameUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *EsameUpdate) SetNillableUpdatedAt(v *time.Time) *EsameUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUtenteID sets the "utente" edge to the Utente entity by ID.
func (_u *EsameUpdate) SetUtenteID(id string) *EsameUpdate {
	_u.mutation.SetUtenteID(id)
	return _u
}

// SetUtente sets the "utente" edge to the Utente entity.
func (_u *EsameUpdate) SetUtente(v *Utente) *EsameUpdate {
	return _u.SetUtenteID(v.ID)
}

// AddQuesitiIDs adds the "quesiti" edge to the QuesitoEsame entity by IDs.
func (_u *EsameUpdate) AddQuesitiIDs(ids ...int) *EsameUpdate {
	_u.mutation.AddQuesitiIDs(ids...)
	return _u
}

// AddQuesiti adds the "quesiti" edges to the QuesitoEsame entity.
func (_u *EsameUpdate) AddQuesiti(v ...*QuesitoEsame) *EsameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuesitiIDs(ids...)
}

// AddCorrezioniIDs adds the "correzioni" edge to the Correzione entity by IDs.
func (_u *EsameUpdate) AddCorrezioniIDs(ids ...int) *EsameUpdate {
	_u.mutation.AddCorrezioniIDs(ids...)
	return _u
}

// AddCorrezioni adds the "correzioni" edges to the Correzione entity.
func (_u *EsameUpdate) AddCorrezioni(v ...*Correzione) *EsameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCorrezioniIDs(ids...)
}

// Mutation returns the EsameMutation object of the builder.
func (_u *EsameUpdate) Mutation() *EsameMutation {
	return _u.mutation
}

// ClearUtente clears the "utente" edge to the Utente entity.
func (_u *EsameUpdate) ClearUtente() *EsameUpdate {
	_u.mutation.ClearUtente()
	return _u
}

// ClearQuesiti clears all "quesiti" edges to the QuesitoEsame entity.
func (_u *EsameUpdate) ClearQuesiti() *EsameUpdate {
	_u.mutation.ClearQuesiti()
	return _u
}

// RemoveQuesitiIDs removes the "quesiti" edge to QuesitoEsame entities by IDs.
func (_u *EsameUpdate) RemoveQuesitiIDs(ids ...int) *EsameUpdate {
	_u.mutation.RemoveQuesitiIDs(ids...)
	return _u
}

// RemoveQuesiti removes "quesiti" edges to QuesitoEsame entities.
func (_u *EsameUpdate) RemoveQuesiti(v ...*QuesitoEsame) *EsameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuesitiIDs(ids...)
}

// ClearCorrezioni clears all "correzioni" edges to the Correzione entity.
func (_u *EsameUpdate) ClearCorrezioni() *EsameUpdate {
	_u.mutation.ClearCorrezioni()
	return _u
}

// RemoveCorrezioniIDs removes the "correzioni" edge to Correzione entities by IDs.
func (_u *EsameUpdate) RemoveCorrezioniIDs(ids ...int) *EsameUpdate {
	_u.mutation.RemoveCorrezioniIDs(ids...)
	return _u
}

// RemoveCorrezioni removes "correzioni" edges to Correzione entities.
func (_u *EsameUpdate) RemoveCorrezioni(v ...*Correzione) *EsameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCorrezioniIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EsameUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EsameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EsameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EsameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EsameUpdate) check() error {
	if v, ok := _u.mutation.Tipo(); ok {
		if err := esame.TipoValidator(v); err != nil {
			return &ValidationError{Name: "tipo", err: fmt.Errorf(`ent: validator failed for field "Esame.tipo": %w`, err)}
		}
	}
	if _u.mutation.UtenteCleared() && len(_u.mutation.UtenteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Esame.utente"`)
	}
	return nil
}

func (_u *EsameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(esame.Table, esame.Columns, sqlgraph.NewFieldSpec(esame.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tipo(); ok {
		_spec.SetField(esame.FieldTipo, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NumeroQuesiti(); ok {
		_spec.SetField(esame.FieldNumeroQuesiti, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumeroQuesiti(); ok {
		_spec.AddField(esame.FieldNumeroQuesiti, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxErrori(); ok {
		_spec.SetField(esame.FieldMaxErrori, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxErrori(); ok {
		_spec.AddField(esame.FieldMaxErrori, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinutiDisponibili(); ok {
		_spec.SetField(esame.FieldMinutiDisponibili, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinutiDisponibili(); ok {
		_spec.AddField(esame.FieldMinutiDisponibili, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(esame.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(esame.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UtenteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   esame.UtenteTable,
			Columns: []string{esame.UtenteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(utente.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UtenteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   esame.UtenteTable,
			Columns: []string{esame.UtenteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(utente.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuesitiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.QuesitiTable,
			Columns: []string{esame.QuesitiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuesitiIDs(); len(nodes) > 0 && !_u.mutation.QuesitiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.QuesitiTable,
			Columns: []string{esame.QuesitiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuesitiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.QuesitiTable,
			Columns: []string{esame.QuesitiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CorrezioniCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.CorrezioniTable,
			Columns: []string{esame.CorrezioniColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(correzione.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCorrezioniIDs(); len(nodes) > 0 && !_u.mutation.CorrezioniCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.CorrezioniTable,
			Columns: []string{esame.CorrezioniColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(correzione.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CorrezioniIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.CorrezioniTable,
			Columns: []string{esame.CorrezioniColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(correzione.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{esame.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EsameUpdateOne is the builder for updating a single Esame entity.
type EsameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EsameMutation
}

// SetTipo sets the "tipo" field.
func (_u *EsameUpdateOne) SetTipo(v esame.Tipo) *EsameUpdateOne {
	_u.mutation.SetTipo(v)
	return _u
}

// SetNillableTipo sets the "tipo" field if the given value is not nil.
func (_u *EsameUpdateOne) SetNillableTipo(v *esame.Tipo) *EsameUpdateOne {
	if v != nil {
		_u.SetTipo(*v)
	}
	return _u
}

// SetNumeroQuesiti sets the "numero_quesiti" field.
func (_u *EsameUpdateOne) SetNumeroQuesiti(v int) *EsameUpdateOne {
	_u.mutation.ResetNumeroQuesiti()
	_u.mutation.SetNumeroQuesiti(v)
	return _u
}

// SetNillableNumeroQuesiti sets the "numero_quesiti" field if the given value is not nil.
func (_u *EsameUpdateOne) SetNillableNumeroQuesiti(v *int) *EsameUpdateOne {
	if v != nil {
		_u.SetNumeroQuesiti(*v)
	}
	return _u
}

// AddNumeroQuesiti adds value to the "numero_quesiti" field.
func (_u *EsameUpdateOne) AddNumeroQuesiti(v int) *EsameUpdateOne {
	_u.mutation.AddNumeroQuesiti(v)
	return _u
}

// SetMaxErrori sets the "max_errori" field.
func (_u *EsameUpdateOne) SetMaxErrori(v int) *EsameUpdateOne {
	_u.mutation.ResetMaxErrori()
	_u.mutation.SetMaxErrori(v)
	return _u
}

// SetNillableMaxErrori sets the "max_errori" field if the given value is not nil.
func (_u *EsameUpdateOne) SetNillableMaxErrori(v *int) *EsameUpdateOne {
	if v != nil {
		_u.SetMaxErrori(*v)
	}
	return _u
}

// AddMaxErrori adds value to the "max_errori" field.
func (_u *EsameUpdateOne) AddMaxErrori(v int) *EsameUpdateOne {
	_u.mutation.AddMaxErrori(v)
	return _u
}

// SetMinutiDisponibili sets the "minuti_disponibili" field.
func (_u *EsameUpdateOne) SetMinutiDisponibili(v int) *EsameUpdateOne {
	_u.mutation.ResetMinutiDisponibili()
	_u.mutation.SetMinutiDisponibili(v)
	return _u
}

// SetNillableMinutiDisponibili sets the "minuti_disponibili" field if the given value is not nil.
func (_u *EsameUpdateOne) SetNillableMinutiDisponibili(v *int) *EsameUpdateOne {
	if v != nil {
		_u.SetMinutiDisponibili(*v)
	}
	return _u
}

// AddMinutiDisponibili adds value to the "minuti_disponibili" field.
func (_u *EsameUpdateOne) AddMinutiDisponibili(v int) *EsameUpdateOne {
	_u.mutation.AddMinutiDisponibili(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EsameUpdateOne) SetCreatedAt(v time.Time) *EsameUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EsameUpdateOne) SetNillableCreatedAt(v *time.Time) *EsameUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EsameUpdateOne) SetUpdatedAt(v time.Time) *EsameUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *EsameUpdateOne) SetNillableUpdatedAt(v *time.Time) *EsameUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUtenteID sets the "utente" edge to the Utente entity by ID.
func (_u *EsameUpdateOne) SetUtenteID(id string) *EsameUpdateOne {
	_u.mutation.SetUtenteID(id)
	return _u
}

// SetUtente sets the "utente" edge to the Utente entity.
func (_u *EsameUpdateOne) SetUtente(v *Utente) *EsameUpdateOne {
	return _u.SetUtenteID(v.ID)
}

// AddQuesitiIDs adds the "quesiti" edge to the QuesitoEsame entity by IDs.
func (_u *EsameUpdateOne) AddQuesitiIDs(ids ...int) *EsameUpdateOne {
	_u.mutation.AddQuesitiIDs(ids...)
	return _u
}

// AddQuesiti adds the "quesiti" edges to the QuesitoEsame entity.
func (_u *EsameUpdateOne) AddQuesiti(v ...*QuesitoEsame) *EsameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuesitiIDs(ids...)
}

// AddCorrezioniIDs adds the "correzioni" edge to the Correzione entity by IDs.
func (_u *EsameUpdateOne) AddCorrezioniIDs(ids ...int) *EsameUpdateOne {
	_u.mutation.AddCorrezioniIDs(ids...)
	return _u
}

// AddCorrezioni adds the "correzioni" edges to the Correzione entity.
func (_u *EsameUpdateOne) AddCorrezioni(v ...*Correzione) *EsameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCorrezioniIDs(ids...)
}

// Mutation returns the EsameMutation object of the builder.
func (_u *EsameUpdateOne) Mutation() *EsameMutation {
	return _u.mutation
}

// ClearUtente clears the "utente" edge to the Utente entity.
func (_u *EsameUpdateOne) ClearUtente() *EsameUpdateOne {
	_u.mutation.ClearUtente()
	return _u
}

// ClearQuesiti clears all "quesiti" edges to the QuesitoEsame entity.
func (_u *EsameUpdateOne) ClearQuesiti() *EsameUpdateOne {
	_u.mutation.ClearQuesiti()
	return _u
}

// RemoveQuesitiIDs removes the "quesiti" edge to QuesitoEsame entities by IDs.
func (_u *EsameUpdateOne) RemoveQuesitiIDs(ids ...int) *EsameUpdateOne {
	_u.mutation.RemoveQuesitiIDs(ids...)
	return _u
}

// RemoveQuesiti removes "quesiti" edges to QuesitoEsame entities.
func (_u *EsameUpdateOne) RemoveQuesiti(v ...*QuesitoEsame) *EsameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuesitiIDs(ids...)
}

// ClearCorrezioni clears all "correzioni" edges to the Correzione entity.
func (_u *EsameUpdateOne) ClearCorrezioni() *EsameUpdateOne {
	_u.mutation.ClearCorrezioni()
	return _u
}

// RemoveCorrezioniIDs removes the "correzioni" edge to Correzione entities by IDs.
func (_u *EsameUpdateOne) RemoveCorrezioniIDs(ids ...int) *EsameUpdateOne {
	_u.mutation.RemoveCorrezioniIDs(ids...)
	return _u
}

// RemoveCorrezioni removes "correzioni" edges to Correzione entities.
func (_u *EsameUpdateOne) RemoveCorrezioni(v ...*Correzione) *EsameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCorrezioniIDs(ids...)
}

// Where appends a list predicates to the EsameUpdate builder.
func (_u *EsameUpdateOne) Where(ps ...predicate.Esame) *EsameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EsameUpdateOne) Select(field string, fields ...string) *EsameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Esame entity.
func (_u *EsameUpdateOne) Save(ctx context.Context) (*Esame, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EsameUpdateOne) SaveX(ctx context.Context) *Esame {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EsameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EsameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EsameUpdateOne) check() error {
	if v, ok := _u.mutation.Tipo(); ok {
		if err := esame.TipoValidator(v); err != nil {
			return &ValidationError{Name: "tipo", err: fmt.Errorf(`ent: validator failed for field "Esame.tipo": %w`, err)}
		}
	}
	if _u.mutation.UtenteCleared() && len(_u.mutation.UtenteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Esame.utente"`)
	}
	return nil
}

func (_u *EsameUpdateOne) sqlSave(ctx context.Context) (_node *Esame, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(esame.Table, esame.Columns, sqlgraph.NewFieldSpec(esame.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Esame.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, esame.FieldID)
		for _, f := range fields {
			if !esame.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != esame.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tipo(); ok {
		_spec.SetField(esame.FieldTipo, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NumeroQuesiti(); ok {
		_spec.SetField(esame.FieldNumeroQuesiti, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumeroQuesiti(); ok {
		_spec.AddField(esame.FieldNumeroQuesiti, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxErrori(); ok {
		_spec.SetField(esame.FieldMaxErrori, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxErrori(); ok {
		_spec.AddField(esame.FieldMaxErrori, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinutiDisponibili(); ok {
		_spec.SetField(esame.FieldMinutiDisponibili, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinutiDisponibili(); ok {
		_spec.AddField(esame.FieldMinutiDisponibili, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(esame.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(esame.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UtenteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   esame.UtenteTable,
			Columns: []string{esame.UtenteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(utente.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UtenteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   esame.UtenteTable,
			Columns: []string{esame.UtenteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(utente.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuesitiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.QuesitiTable,
			Columns: []string{esame.QuesitiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuesitiIDs(); len(nodes) > 0 && !_u.mutation.QuesitiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.QuesitiTable,
			Columns: []string{esame.QuesitiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuesitiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.QuesitiTable,
			Columns: []string{esame.QuesitiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CorrezioniCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.CorrezioniTable,
			Columns: []string{esame.CorrezioniColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(correzione.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCorrezioniIDs(); len(nodes) > 0 && !_u.mutation.CorrezioniCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.CorrezioniTable,
			Columns: []string{esame.CorrezioniColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(correzione.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CorrezioniIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   esame.CorrezioniTable,
			Columns: []string{esame.CorrezioniColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(correzione.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Esame{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{esame.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
