// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ed-evo/hankinson/server/ent/domanda"
	"github.com/ed-evo/hankinson/server/ent/esame"
	"github.com/ed-evo/hankinson/server/ent/quesitoesame"
)

// QuesitoEsame is the model entity for the QuesitoEsame schema.
type QuesitoEsame struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RispostaFinale holds the value of the "risposta_finale" field.
	RispostaFinale *bool `json:"risposta_finale,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QuesitoEsameQuery when eager-loading is set.
	Edges                           QuesitoEsameEdges `json:"edges"`
	esame_quesiti                   *int
	quesito_esame_domanda_originale *int
	selectValues                    sql.SelectValues
}

// QuesitoEsameEdges holds the relations/edges for other nodes in the graph.
type QuesitoEsameEdges struct {
	// Esame holds the value of the esame edge.
	Esame *Esame `json:"esame,omitempty"`
	// DomandaOriginale holds the value of the domanda_originale edge.
	DomandaOriginale *Domanda `json:"domanda_originale,omitempty"`
	// Attivita holds the value of the attivita edge.
	Attivita []*AttivitaQuesitoEsame `json:"attivita,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// EsameOrErr returns the Esame value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QuesitoEsameEdges) EsameOrErr() (*Esame, error) {
	if e.Esame != nil {
		return e.Esame, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: esame.Label}
	}
	return nil, &NotLoadedError{edge: "esame"}
}

// DomandaOriginaleOrErr returns the DomandaOriginale value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QuesitoEsameEdges) DomandaOriginaleOrErr() (*Domanda, error) {
	if e.DomandaOriginale != nil {
		return e.DomandaOriginale, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: domanda.Label}
	}
	return nil, &NotLoadedError{edge: "domanda_originale"}
}

// AttivitaOrErr returns the Attivita value or an error if the edge
// was not loaded in eager-loading.
func (e QuesitoEsameEdges) AttivitaOrErr() ([]*AttivitaQuesitoEsame, error) {
	if e.loadedTypes[2] {
		return e.Attivita, nil
	}
	return nil, &NotLoadedError{edge: "attivita"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QuesitoEsame) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quesitoesame.FieldRispostaFinale:
			values[i] = new(sql.NullBool)
		case quesitoesame.FieldID:
			values[i] = new(sql.NullInt64)
		case quesitoesame.FieldCreatedAt, quesitoesame.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case quesitoesame.ForeignKeys[0]: // esame_quesiti
			values[i] = new(sql.NullInt64)
		case quesitoesame.ForeignKeys[1]: // quesito_esame_domanda_originale
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QuesitoEsame fields.
func (_m *QuesitoEsame) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quesitoesame.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case quesitoesame.FieldRispostaFinale:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field risposta_finale", values[i])
			} else if value.Valid {
				_m.RispostaFinale = new(bool)
				*_m.RispostaFinale = value.Bool
			}
		case quesitoesame.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case quesitoesame.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case quesitoesame.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field esame_quesiti", value)
			} else if value.Valid {
				_m.esame_quesiti = new(int)
				*_m.esame_quesiti = int(value.Int64)
			}
		case quesitoesame.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field quesito_esame_domanda_originale", value)
			} else if value.Valid {
				_m.quesito_esame_domanda_originale = new(int)
				*_m.quesito_esame_domanda_originale = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QuesitoEsame.
// This includes values selected through modifiers, order, etc.
func (_m *QuesitoEsame) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEsame queries the "esame" edge of the QuesitoEsame entity.
func (_m *QuesitoEsame) QueryEsame() *EsameQuery {
	return NewQuesitoEsameClient(_m.config).QueryEsame(_m)
}

// QueryDomandaOriginale queries the "domanda_originale" edge of the QuesitoEsame entity.
func (_m *QuesitoEsame) QueryDomandaOriginale() *DomandaQuery {
	return NewQuesitoEsameClient(_m.config).QueryDomandaOriginale(_m)
}

// QueryAttivita queries the "attivita" edge of the QuesitoEsame entity.
func (_m *QuesitoEsame) QueryAttivita() *AttivitaQuesitoEsameQuery {
	return NewQuesitoEsameClient(_m.config).QueryAttivita(_m)
}

// Update returns a builder for updating this QuesitoEsame.
// Note that you need to call QuesitoEsame.Unwrap() before calling this method if this QuesitoEsame
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *QuesitoEsame) Update() *QuesitoEsameUpdateOne {
	return NewQuesitoEsameClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the QuesitoEsame entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *QuesitoEsame) Unwrap() *QuesitoEsame {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: QuesitoEsame is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *QuesitoEsame) String() string {
	var builder strings.Builder
	builder.WriteString("QuesitoEsame(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.RispostaFinale; v != nil {
		builder.WriteString("risposta_finale=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// QuesitoEsames is a parsable slice of QuesitoEsame.
type QuesitoEsames []*QuesitoEsame
