// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ed-evo/hankinson/server/ent/attivitaquesitoesame"
	"github.com/ed-evo/hankinson/server/ent/domanda"
	"github.com/ed-evo/hankinson/server/ent/esame"
	"github.com/ed-evo/hankinson/server/ent/predicate"
	"github.com/ed-evo/hankinson/server/ent/quesitoesame"
)

// QuesitoEsameQuery is the builder for querying QuesitoEsame entities.
type QuesitoEsameQuery struct {
	config
	ctx                  *QueryContext
	order                []quesitoesame.OrderOption
	inters               []Interceptor
	predicates           []predicate.QuesitoEsame
	withEsame            *EsameQuery
	withDomandaOriginale *DomandaQuery
	withLogs             *AttivitaQuesitoEsameQuery
	withFKs              bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuesitoEsameQuery builder.
func (_q *QuesitoEsameQuery) Where(ps ...predicate.QuesitoEsame) *QuesitoEsameQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *QuesitoEsameQuery) Limit(limit int) *QuesitoEsameQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *QuesitoEsameQuery) Offset(offset int) *QuesitoEsameQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *QuesitoEsameQuery) Unique(unique bool) *QuesitoEsameQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *QuesitoEsameQuery) Order(o ...quesitoesame.OrderOption) *QuesitoEsameQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEsame chains the current query on the "esame" edge.
func (_q *QuesitoEsameQuery) QueryEsame() *EsameQuery {
	query := (&EsameClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quesitoesame.Table, quesitoesame.FieldID, selector),
			sqlgraph.To(esame.Table, esame.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, quesitoesame.EsameTable, quesitoesame.EsameColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDomandaOriginale chains the current query on the "domanda_originale" edge.
func (_q *QuesitoEsameQuery) QueryDomandaOriginale() *DomandaQuery {
	query := (&DomandaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quesitoesame.Table, quesitoesame.FieldID, selector),
			sqlgraph.To(domanda.Table, domanda.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, quesitoesame.DomandaOriginaleTable, quesitoesame.DomandaOriginaleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLogs chains the current query on the "logs" edge.
func (_q *QuesitoEsameQuery) QueryLogs() *AttivitaQuesitoEsameQuery {
	query := (&AttivitaQuesitoEsameClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quesitoesame.Table, quesitoesame.FieldID, selector),
			sqlgraph.To(attivitaquesitoesame.Table, attivitaquesitoesame.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, quesitoesame.LogsTable, quesitoesame.LogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QuesitoEsame entity from the query.
// Returns a *NotFoundError when no QuesitoEsame was found.
func (_q *QuesitoEsameQuery) First(ctx context.Context) (*QuesitoEsame, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{quesitoesame.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *QuesitoEsameQuery) FirstX(ctx context.Context) *QuesitoEsame {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QuesitoEsame ID from the query.
// Returns a *NotFoundError when no QuesitoEsame ID was found.
func (_q *QuesitoEsameQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{quesitoesame.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *QuesitoEsameQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QuesitoEsame entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QuesitoEsame entity is found.
// Returns a *NotFoundError when no QuesitoEsame entities are found.
func (_q *QuesitoEsameQuery) Only(ctx context.Context) (*QuesitoEsame, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{quesitoesame.Label}
	default:
		return nil, &NotSingularError{quesitoesame.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *QuesitoEsameQuery) OnlyX(ctx context.Context) *QuesitoEsame {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QuesitoEsame ID in the query.
// Returns a *NotSingularError when more than one QuesitoEsame ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *QuesitoEsameQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{quesitoesame.Label}
	default:
		err = &NotSingularError{quesitoesame.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *QuesitoEsameQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QuesitoEsames.
func (_q *QuesitoEsameQuery) All(ctx context.Context) ([]*QuesitoEsame, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QuesitoEsame, *QuesitoEsameQuery]()
	return withInterceptors[[]*QuesitoEsame](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *QuesitoEsameQuery) AllX(ctx context.Context) []*QuesitoEsame {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QuesitoEsame IDs.
func (_q *QuesitoEsameQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(quesitoesame.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *QuesitoEsameQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *QuesitoEsameQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*QuesitoEsameQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *QuesitoEsameQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *QuesitoEsameQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *QuesitoEsameQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuesitoEsameQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *QuesitoEsameQuery) Clone() *QuesitoEsameQuery {
	if _q == nil {
		return nil
	}
	return &QuesitoEsameQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]quesitoesame.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.QuesitoEsame{}, _q.predicates...),
		withEsame:            _q.withEsame.Clone(),
		withDomandaOriginale: _q.withDomandaOriginale.Clone(),
		withLogs:             _q.withLogs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEsame tells the query-builder to eager-load the nodes that are connected to
// the "esame" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuesitoEsameQuery) WithEsame(opts ...func(*EsameQuery)) *QuesitoEsameQuery {
	query := (&EsameClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEsame = query
	return _q
}

// WithDomandaOriginale tells the query-builder to eager-load the nodes that are connected to
// the "domanda_originale" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuesitoEsameQuery) WithDomandaOriginale(opts ...func(*DomandaQuery)) *QuesitoEsameQuery {
	query := (&DomandaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDomandaOriginale = query
	return _q
}

// WithLogs tells the query-builder to eager-load the nodes that are connected to
// the "logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuesitoEsameQuery) WithLogs(opts ...func(*AttivitaQuesitoEsameQuery)) *QuesitoEsameQuery {
	query := (&AttivitaQuesitoEsameClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLogs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RispostaFinale bool `json:"risposta_finale,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QuesitoEsame.Query().
//		GroupBy(quesitoesame.FieldRispostaFinale).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *QuesitoEsameQuery) GroupBy(field string, fields ...string) *QuesitoEsameGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuesitoEsameGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = quesitoesame.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RispostaFinale bool `json:"risposta_finale,omitempty"`
//	}
//
//	client.QuesitoEsame.Query().
//		Select(quesitoesame.FieldRispostaFinale).
//		Scan(ctx, &v)
func (_q *QuesitoEsameQuery) Select(fields ...string) *QuesitoEsameSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &QuesitoEsameSelect{QuesitoEsameQuery: _q}
	sbuild.label = quesitoesame.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuesitoEsameSelect configured with the given aggregations.
func (_q *QuesitoEsameQuery) Aggregate(fns ...AggregateFunc) *QuesitoEsameSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *QuesitoEsameQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !quesitoesame.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *QuesitoEsameQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QuesitoEsame, error) {
	var (
		nodes       = []*QuesitoEsame{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withEsame != nil,
			_q.withDomandaOriginale != nil,
			_q.withLogs != nil,
		}
	)
	if _q.withEsame != nil || _q.withDomandaOriginale != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, quesitoesame.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QuesitoEsame).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QuesitoEsame{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEsame; query != nil {
		if err := _q.loadEsame(ctx, query, nodes, nil,
			func(n *QuesitoEsame, e *Esame) { n.Edges.Esame = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDomandaOriginale; query != nil {
		if err := _q.loadDomandaOriginale(ctx, query, nodes, nil,
			func(n *QuesitoEsame, e *Domanda) { n.Edges.DomandaOriginale = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLogs; query != nil {
		if err := _q.loadLogs(ctx, query, nodes,
			func(n *QuesitoEsame) { n.Edges.Logs = []*AttivitaQuesitoEsame{} },
			func(n *QuesitoEsame, e *AttivitaQuesitoEsame) { n.Edges.Logs = append(n.Edges.Logs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *QuesitoEsameQuery) loadEsame(ctx context.Context, query *EsameQuery, nodes []*QuesitoEsame, init func(*QuesitoEsame), assign func(*QuesitoEsame, *Esame)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QuesitoEsame)
	for i := range nodes {
		if nodes[i].esame_quesiti == nil {
			continue
		}
		fk := *nodes[i].esame_quesiti
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(esame.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "esame_quesiti" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *QuesitoEsameQuery) loadDomandaOriginale(ctx context.Context, query *DomandaQuery, nodes []*QuesitoEsame, init func(*QuesitoEsame), assign func(*QuesitoEsame, *Domanda)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QuesitoEsame)
	for i := range nodes {
		if nodes[i].quesito_esame_domanda_originale == nil {
			continue
		}
		fk := *nodes[i].quesito_esame_domanda_originale
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(domanda.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "quesito_esame_domanda_originale" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *QuesitoEsameQuery) loadLogs(ctx context.Context, query *AttivitaQuesitoEsameQuery, nodes []*QuesitoEsame, init func(*QuesitoEsame), assign func(*QuesitoEsame, *AttivitaQuesitoEsame)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*QuesitoEsame)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.AttivitaQuesitoEsame(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(quesitoesame.LogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.quesito_esame_logs
		if fk == nil {
			return fmt.Errorf(`foreign-key "quesito_esame_logs" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "quesito_esame_logs" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *QuesitoEsameQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *QuesitoEsameQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(quesitoesame.Table, quesitoesame.Columns, sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quesitoesame.FieldID)
		for i := range fields {
			if fields[i] != quesitoesame.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *QuesitoEsameQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(quesitoesame.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = quesitoesame.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QuesitoEsameGroupBy is the group-by builder for QuesitoEsame entities.
type QuesitoEsameGroupBy struct {
	selector
	build *QuesitoEsameQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *QuesitoEsameGroupBy) Aggregate(fns ...AggregateFunc) *QuesitoEsameGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *QuesitoEsameGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuesitoEsameQuery, *QuesitoEsameGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *QuesitoEsameGroupBy) sqlScan(ctx context.Context, root *QuesitoEsameQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuesitoEsameSelect is the builder for selecting fields of QuesitoEsame entities.
type QuesitoEsameSelect struct {
	*QuesitoEsameQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *QuesitoEsameSelect) Aggregate(fns ...AggregateFunc) *QuesitoEsameSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *QuesitoEsameSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuesitoEsameQuery, *QuesitoEsameSelect](ctx, _s.QuesitoEsameQuery, _s, _s.inters, v)
}

func (_s *QuesitoEsameSelect) sqlScan(ctx context.Context, root *QuesitoEsameQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
