// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ed-evo/hankinson/server/ent/attivitaquesitoesame"
	"github.com/ed-evo/hankinson/server/ent/domanda"
	"github.com/ed-evo/hankinson/server/ent/esame"
	"github.com/ed-evo/hankinson/server/ent/predicate"
	"github.com/ed-evo/hankinson/server/ent/quesitoesame"
)

// QuesitoEsameUpdate is the builder for updating QuesitoEsame entities.
type QuesitoEsameUpdate struct {
	config
	hooks    []Hook
	mutation *QuesitoEsameMutation
}

// Where appends a list predicates to the QuesitoEsameUpdate builder.
func (_u *QuesitoEsameUpdate) Where(ps ...predicate.QuesitoEsame) *QuesitoEsameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRispostaFinale sets the "risposta_finale" field.
func (_u *QuesitoEsameUpdate) SetRispostaFinale(v bool) *QuesitoEsameUpdate {
	_u.mutation.SetRispostaFinale(v)
	return _u
}

// SetNillableRispostaFinale sets the "risposta_finale" field if the given value is not nil.
func (_u *QuesitoEsameUpdate) SetNillableRispostaFinale(v *bool) *QuesitoEsameUpdate {
	if v != nil {
		_u.SetRispostaFinale(*v)
	}
	return _u
}

// ClearRispostaFinale clears the value of the "risposta_finale" field.
func (_u *QuesitoEsameUpdate) ClearRispostaFinale() *QuesitoEsameUpdate {
	_u.mutation.ClearRispostaFinale()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *QuesitoEsameUpdate) SetCreatedAt(v time.Time) *QuesitoEsameUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *QuesitoEsameUpdate) SetNillableCreatedAt(v *time.Time) *QuesitoEsameUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuesitoEsameUpdate) SetUpdatedAt(v time.Time) *QuesitoEsameUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *QuesitoEsameUpdate) SetNillableUpdatedAt(v *time.Time) *QuesitoEsameUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetEsameID sets the "esame" edge to the Esame entity by ID.
func (_u *QuesitoEsameUpdate) SetEsameID(id int) *QuesitoEsameUpdate {
	_u.mutation.SetEsameID(id)
	return _u
}

// SetEsame sets the "esame" edge to the Esame entity.
func (_u *QuesitoEsameUpdate) SetEsame(v *Esame) *QuesitoEsameUpdate {
	return _u.SetEsameID(v.ID)
}

// SetDomandaOriginaleID sets the "domanda_originale" edge to the Domanda entity by ID.
func (_u *QuesitoEsameUpdate) SetDomandaOriginaleID(id int) *QuesitoEsameUpdate {
	_u.mutation.SetDomandaOriginaleID(id)
	return _u
}

// SetDomandaOriginale sets the "domanda_originale" edge to the Domanda entity.
func (_u *QuesitoEsameUpdate) SetDomandaOriginale(v *Domanda) *QuesitoEsameUpdate {
	return _u.SetDomandaOriginaleID(v.ID)
}

// AddAttivitumIDs adds the "attivita" edge to the AttivitaQuesitoEsame entity by IDs.
func (_u *QuesitoEsameUpdate) AddAttivitumIDs(ids ...int) *QuesitoEsameUpdate {
	_u.mutation.AddAttivitumIDs(ids...)
	return _u
}

// AddAttivita adds the "attivita" edges to the AttivitaQuesitoEsame entity.
func (_u *QuesitoEsameUpdate) AddAttivita(v ...*AttivitaQuesitoEsame) *QuesitoEsameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttivitumIDs(ids...)
}

// Mutation returns the QuesitoEsameMutation object of the builder.
func (_u *QuesitoEsameUpdate) Mutation() *QuesitoEsameMutation {
	return _u.mutation
}

// ClearEsame clears the "esame" edge to the Esame entity.
func (_u *QuesitoEsameUpdate) ClearEsame() *QuesitoEsameUpdate {
	_u.mutation.ClearEsame()
	return _u
}

// ClearDomandaOriginale clears the "domanda_originale" edge to the Domanda entity.
func (_u *QuesitoEsameUpdate) ClearDomandaOriginale() *QuesitoEsameUpdate {
	_u.mutation.ClearDomandaOriginale()
	return _u
}

// ClearAttivita clears all "attivita" edges to the AttivitaQuesitoEsame entity.
func (_u *QuesitoEsameUpdate) ClearAttivita() *QuesitoEsameUpdate {
	_u.mutation.ClearAttivita()
	return _u
}

// RemoveAttivitumIDs removes the "attivita" edge to AttivitaQuesitoEsame entities by IDs.
func (_u *QuesitoEsameUpdate) RemoveAttivitumIDs(ids ...int) *QuesitoEsameUpdate {
	_u.mutation.RemoveAttivitumIDs(ids...)
	return _u
}

// RemoveAttivita removes "attivita" edges to AttivitaQuesitoEsame entities.
func (_u *QuesitoEsameUpdate) RemoveAttivita(v ...*AttivitaQuesitoEsame) *QuesitoEsameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttivitumIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuesitoEsameUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuesitoEsameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuesitoEsameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuesitoEsameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuesitoEsameUpdate) check() error {
	if _u.mutation.EsameCleared() && len(_u.mutation.EsameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuesitoEsame.esame"`)
	}
	if _u.mutation.DomandaOriginaleCleared() && len(_u.mutation.DomandaOriginaleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuesitoEsame.domanda_originale"`)
	}
	return nil
}

func (_u *QuesitoEsameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quesitoesame.Table, quesitoesame.Columns, sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RispostaFinale(); ok {
		_spec.SetField(quesitoesame.FieldRispostaFinale, field.TypeBool, value)
	}
	if _u.mutation.RispostaFinaleCleared() {
		_spec.ClearField(quesitoesame.FieldRispostaFinale, field.TypeBool)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(quesitoesame.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quesitoesame.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EsameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quesitoesame.EsameTable,
			Columns: []string{quesitoesame.EsameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(esame.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EsameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quesitoesame.EsameTable,
			Columns: []string{quesitoesame.EsameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(esame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DomandaOriginaleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quesitoesame.DomandaOriginaleTable,
			Columns: []string{quesitoesame.DomandaOriginaleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomandaOriginaleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quesitoesame.DomandaOriginaleTable,
			Columns: []string{quesitoesame.DomandaOriginaleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttivitaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quesitoesame.AttivitaTable,
			Columns: []string{quesitoesame.AttivitaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attivitaquesitoesame.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttivitaIDs(); len(nodes) > 0 && !_u.mutation.AttivitaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quesitoesame.AttivitaTable,
			Columns: []string{quesitoesame.AttivitaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attivitaquesitoesame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttivitaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quesitoesame.AttivitaTable,
			Columns: []string{quesitoesame.AttivitaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attivitaquesitoesame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quesitoesame.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuesitoEsameUpdateOne is the builder for updating a single QuesitoEsame entity.
type QuesitoEsameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuesitoEsameMutation
}

// SetRispostaFinale sets the "risposta_finale" field.
func (_u *QuesitoEsameUpdateOne) SetRispostaFinale(v bool) *QuesitoEsameUpdateOne {
	_u.mutation.SetRispostaFinale(v)
	return _u
}

// SetNillableRispostaFinale sets the "risposta_finale" field if the given value is not nil.
func (_u *QuesitoEsameUpdateOne) SetNillableRispostaFinale(v *bool) *QuesitoEsameUpdateOne {
	if v != nil {
		_u.SetRispostaFinale(*v)
	}
	return _u
}

// ClearRispostaFinale clears the value of the "risposta_finale" field.
func (_u *QuesitoEsameUpdateOne) ClearRispostaFinale() *QuesitoEsameUpdateOne {
	_u.mutation.ClearRispostaFinale()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *QuesitoEsameUpdateOne) SetCreatedAt(v time.Time) *QuesitoEsameUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *QuesitoEsameUpdateOne) SetNillableCreatedAt(v *time.Time) *QuesitoEsameUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuesitoEsameUpdateOne) SetUpdatedAt(v time.Time) *QuesitoEsameUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *QuesitoEsameUpdateOne) SetNillableUpdatedAt(v *time.Time) *QuesitoEsameUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetEsameID sets the "esame" edge to the Esame entity by ID.
func (_u *QuesitoEsameUpdateOne) SetEsameID(id int) *QuesitoEsameUpdateOne {
	_u.mutation.SetEsameID(id)
	return _u
}

// SetEsame sets the "esame" edge to the Esame entity.
func (_u *QuesitoEsameUpdateOne) SetEsame(v *Esame) *QuesitoEsameUpdateOne {
	return _u.SetEsameID(v.ID)
}

// SetDomandaOriginaleID sets the "domanda_originale" edge to the Domanda entity by ID.
func (_u *QuesitoEsameUpdateOne) SetDomandaOriginaleID(id int) *QuesitoEsameUpdateOne {
	_u.mutation.SetDomandaOriginaleID(id)
	return _u
}

// SetDomandaOriginale sets the "domanda_originale" edge to the Domanda entity.
func (_u *QuesitoEsameUpdateOne) SetDomandaOriginale(v *Domanda) *QuesitoEsameUpdateOne {
	return _u.SetDomandaOriginaleID(v.ID)
}

// AddAttivitumIDs adds the "attivita" edge to the AttivitaQuesitoEsame entity by IDs.
func (_u *QuesitoEsameUpdateOne) AddAttivitumIDs(ids ...int) *QuesitoEsameUpdateOne {
	_u.mutation.AddAttivitumIDs(ids...)
	return _u
}

// AddAttivita adds the "attivita" edges to the AttivitaQuesitoEsame entity.
func (_u *QuesitoEsameUpdateOne) AddAttivita(v ...*AttivitaQuesitoEsame) *QuesitoEsameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttivitumIDs(ids...)
}

// Mutation returns the QuesitoEsameMutation object of the builder.
func (_u *QuesitoEsameUpdateOne) Mutation() *QuesitoEsameMutation {
	return _u.mutation
}

// ClearEsame clears the "esame" edge to the Esame entity.
func (_u *QuesitoEsameUpdateOne) ClearEsame() *QuesitoEsameUpdateOne {
	_u.mutation.ClearEsame()
	return _u
}

// ClearDomandaOriginale clears the "domanda_originale" edge to the Domanda entity.
func (_u *QuesitoEsameUpdateOne) ClearDomandaOriginale() *QuesitoEsameUpdateOne {
	_u.mutation.ClearDomandaOriginale()
	return _u
}

// ClearAttivita clears all "attivita" edges to the AttivitaQuesitoEsame entity.
func (_u *QuesitoEsameUpdateOne) ClearAttivita() *QuesitoEsameUpdateOne {
	_u.mutation.ClearAttivita()
	return _u
}

// RemoveAttivitumIDs removes the "attivita" edge to AttivitaQuesitoEsame entities by IDs.
func (_u *QuesitoEsameUpdateOne) RemoveAttivitumIDs(ids ...int) *QuesitoEsameUpdateOne {
	_u.mutation.RemoveAttivitumIDs(ids...)
	return _u
}

// RemoveAttivita removes "attivita" edges to AttivitaQuesitoEsame entities.
func (_u *QuesitoEsameUpdateOne) RemoveAttivita(v ...*AttivitaQuesitoEsame) *QuesitoEsameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttivitumIDs(ids...)
}

// Where appends a list predicates to the QuesitoEsameUpdate builder.
func (_u *QuesitoEsameUpdateOne) Where(ps ...predicate.QuesitoEsame) *QuesitoEsameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuesitoEsameUpdateOne) Select(field string, fields ...string) *QuesitoEsameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuesitoEsame entity.
func (_u *QuesitoEsameUpdateOne) Save(ctx context.Context) (*QuesitoEsame, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuesitoEsameUpdateOne) SaveX(ctx context.Context) *QuesitoEsame {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuesitoEsameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuesitoEsameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuesitoEsameUpdateOne) check() error {
	if _u.mutation.EsameCleared() && len(_u.mutation.EsameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuesitoEsame.esame"`)
	}
	if _u.mutation.DomandaOriginaleCleared() && len(_u.mutation.DomandaOriginaleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuesitoEsame.domanda_originale"`)
	}
	return nil
}

func (_u *QuesitoEsameUpdateOne) sqlSave(ctx context.Context) (_node *QuesitoEsame, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quesitoesame.Table, quesitoesame.Columns, sqlgraph.NewFieldSpec(quesitoesame.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuesitoEsame.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quesitoesame.FieldID)
		for _, f := range fields {
			if !quesitoesame.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quesitoesame.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RispostaFinale(); ok {
		_spec.SetField(quesitoesame.FieldRispostaFinale, field.TypeBool, value)
	}
	if _u.mutation.RispostaFinaleCleared() {
		_spec.ClearField(quesitoesame.FieldRispostaFinale, field.TypeBool)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(quesitoesame.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quesitoesame.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EsameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quesitoesame.EsameTable,
			Columns: []string{quesitoesame.EsameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(esame.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EsameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quesitoesame.EsameTable,
			Columns: []string{quesitoesame.EsameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(esame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DomandaOriginaleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quesitoesame.DomandaOriginaleTable,
			Columns: []string{quesitoesame.DomandaOriginaleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomandaOriginaleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   quesitoesame.DomandaOriginaleTable,
			Columns: []string{quesitoesame.DomandaOriginaleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(domanda.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttivitaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quesitoesame.AttivitaTable,
			Columns: []string{quesitoesame.AttivitaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attivitaquesitoesame.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttivitaIDs(); len(nodes) > 0 && !_u.mutation.AttivitaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quesitoesame.AttivitaTable,
			Columns: []string{quesitoesame.AttivitaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attivitaquesitoesame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttivitaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quesitoesame.AttivitaTable,
			Columns: []string{quesitoesame.AttivitaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attivitaquesitoesame.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &QuesitoEsame{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quesitoesame.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
