// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ed-evo/hankinson/server/ent/argomento"
	"github.com/ed-evo/hankinson/server/ent/capitolo"
	"github.com/ed-evo/hankinson/server/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	argomentoFields := schema.Argomento{}.Fields()
	_ = argomentoFields
	// argomentoDescNome is the schema descriptor for nome field.
	argomentoDescNome := argomentoFields[1].Descriptor()
	// argomento.NomeValidator is a validator for the "nome" field. It is called by the builders before save.
	argomento.NomeValidator = argomentoDescNome.Validators[0].(func(string) error)
	capitoloFields := schema.Capitolo{}.Fields()
	_ = capitoloFields
	// capitoloDescNome is the schema descriptor for nome field.
	capitoloDescNome := capitoloFields[1].Descriptor()
	// capitolo.NomeValidator is a validator for the "nome" field. It is called by the builders before save.
	capitolo.NomeValidator = capitoloDescNome.Validators[0].(func(string) error)
}
