// Code generated by ent, DO NOT EDIT.

package argomento

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ed-evo/hankinson/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Argomento {
	return predicate.Argomento(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Argomento {
	return predicate.Argomento(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Argomento {
	return predicate.Argomento(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Argomento {
	return predicate.Argomento(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Argomento {
	return predicate.Argomento(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Argomento {
	return predicate.Argomento(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Argomento {
	return predicate.Argomento(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Argomento {
	return predicate.Argomento(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Argomento {
	return predicate.Argomento(sql.FieldLTE(FieldID, id))
}

// Nome applies equality check predicate on the "nome" field. It's identical to NomeEQ.
func Nome(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldEQ(FieldNome, v))
}

// NomeEQ applies the EQ predicate on the "nome" field.
func NomeEQ(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldEQ(FieldNome, v))
}

// NomeNEQ applies the NEQ predicate on the "nome" field.
func NomeNEQ(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldNEQ(FieldNome, v))
}

// NomeIn applies the In predicate on the "nome" field.
func NomeIn(vs ...string) predicate.Argomento {
	return predicate.Argomento(sql.FieldIn(FieldNome, vs...))
}

// NomeNotIn applies the NotIn predicate on the "nome" field.
func NomeNotIn(vs ...string) predicate.Argomento {
	return predicate.Argomento(sql.FieldNotIn(FieldNome, vs...))
}

// NomeGT applies the GT predicate on the "nome" field.
func NomeGT(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldGT(FieldNome, v))
}

// NomeGTE applies the GTE predicate on the "nome" field.
func NomeGTE(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldGTE(FieldNome, v))
}

// NomeLT applies the LT predicate on the "nome" field.
func NomeLT(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldLT(FieldNome, v))
}

// NomeLTE applies the LTE predicate on the "nome" field.
func NomeLTE(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldLTE(FieldNome, v))
}

// NomeContains applies the Contains predicate on the "nome" field.
func NomeContains(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldContains(FieldNome, v))
}

// NomeHasPrefix applies the HasPrefix predicate on the "nome" field.
func NomeHasPrefix(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldHasPrefix(FieldNome, v))
}

// NomeHasSuffix applies the HasSuffix predicate on the "nome" field.
func NomeHasSuffix(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldHasSuffix(FieldNome, v))
}

// NomeEqualFold applies the EqualFold predicate on the "nome" field.
func NomeEqualFold(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldEqualFold(FieldNome, v))
}

// NomeContainsFold applies the ContainsFold predicate on the "nome" field.
func NomeContainsFold(v string) predicate.Argomento {
	return predicate.Argomento(sql.FieldContainsFold(FieldNome, v))
}

// HasDomande applies the HasEdge predicate on the "domande" edge.
func HasDomande() predicate.Argomento {
	return predicate.Argomento(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, DomandeTable, DomandePrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDomandeWith applies the HasEdge predicate on the "domande" edge with a given conditions (other predicates).
func HasDomandeWith(preds ...predicate.Domanda) predicate.Argomento {
	return predicate.Argomento(func(s *sql.Selector) {
		step := newDomandeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Argomento) predicate.Argomento {
	return predicate.Argomento(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Argomento) predicate.Argomento {
	return predicate.Argomento(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Argomento) predicate.Argomento {
	return predicate.Argomento(sql.NotPredicates(p))
}
