// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Argomento is the predicate function for argomento builders.
type Argomento func(*sql.Selector)

// Domanda is the predicate function for domanda builders.
type Domanda func(*sql.Selector)
