// Code generated by ent, DO NOT EDIT.

package spiegazione

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ed-evo/hankinson/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldLTE(FieldID, id))
}

// NumeroDomanda applies equality check predicate on the "numero_domanda" field. It's identical to NumeroDomandaEQ.
func NumeroDomanda(v int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEQ(FieldNumeroDomanda, v))
}

// Spiegazione applies equality check predicate on the "spiegazione" field. It's identical to SpiegazioneEQ.
func Spiegazione(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEQ(FieldSpiegazione, v))
}

// FocusLinguistico applies equality check predicate on the "focus_linguistico" field. It's identical to FocusLinguisticoEQ.
func FocusLinguistico(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEQ(FieldFocusLinguistico, v))
}

// RegolaChiave applies equality check predicate on the "regola_chiave" field. It's identical to RegolaChiaveEQ.
func RegolaChiave(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEQ(FieldRegolaChiave, v))
}

// NumeroDomandaEQ applies the EQ predicate on the "numero_domanda" field.
func NumeroDomandaEQ(v int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEQ(FieldNumeroDomanda, v))
}

// NumeroDomandaNEQ applies the NEQ predicate on the "numero_domanda" field.
func NumeroDomandaNEQ(v int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldNEQ(FieldNumeroDomanda, v))
}

// NumeroDomandaIn applies the In predicate on the "numero_domanda" field.
func NumeroDomandaIn(vs ...int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldIn(FieldNumeroDomanda, vs...))
}

// NumeroDomandaNotIn applies the NotIn predicate on the "numero_domanda" field.
func NumeroDomandaNotIn(vs ...int) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldNotIn(FieldNumeroDomanda, vs...))
}

// SpiegazioneEQ applies the EQ predicate on the "spiegazione" field.
func SpiegazioneEQ(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEQ(FieldSpiegazione, v))
}

// SpiegazioneNEQ applies the NEQ predicate on the "spiegazione" field.
func SpiegazioneNEQ(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldNEQ(FieldSpiegazione, v))
}

// SpiegazioneIn applies the In predicate on the "spiegazione" field.
func SpiegazioneIn(vs ...string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldIn(FieldSpiegazione, vs...))
}

// SpiegazioneNotIn applies the NotIn predicate on the "spiegazione" field.
func SpiegazioneNotIn(vs ...string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldNotIn(FieldSpiegazione, vs...))
}

// SpiegazioneGT applies the GT predicate on the "spiegazione" field.
func SpiegazioneGT(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldGT(FieldSpiegazione, v))
}

// SpiegazioneGTE applies the GTE predicate on the "spiegazione" field.
func SpiegazioneGTE(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldGTE(FieldSpiegazione, v))
}

// SpiegazioneLT applies the LT predicate on the "spiegazione" field.
func SpiegazioneLT(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldLT(FieldSpiegazione, v))
}

// SpiegazioneLTE applies the LTE predicate on the "spiegazione" field.
func SpiegazioneLTE(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldLTE(FieldSpiegazione, v))
}

// SpiegazioneContains applies the Contains predicate on the "spiegazione" field.
func SpiegazioneContains(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldContains(FieldSpiegazione, v))
}

// SpiegazioneHasPrefix applies the HasPrefix predicate on the "spiegazione" field.
func SpiegazioneHasPrefix(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldHasPrefix(FieldSpiegazione, v))
}

// SpiegazioneHasSuffix applies the HasSuffix predicate on the "spiegazione" field.
func SpiegazioneHasSuffix(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldHasSuffix(FieldSpiegazione, v))
}

// SpiegazioneEqualFold applies the EqualFold predicate on the "spiegazione" field.
func SpiegazioneEqualFold(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEqualFold(FieldSpiegazione, v))
}

// SpiegazioneContainsFold applies the ContainsFold predicate on the "spiegazione" field.
func SpiegazioneContainsFold(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldContainsFold(FieldSpiegazione, v))
}

// FocusLinguisticoEQ applies the EQ predicate on the "focus_linguistico" field.
func FocusLinguisticoEQ(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEQ(FieldFocusLinguistico, v))
}

// FocusLinguisticoNEQ applies the NEQ predicate on the "focus_linguistico" field.
func FocusLinguisticoNEQ(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldNEQ(FieldFocusLinguistico, v))
}

// FocusLinguisticoIn applies the In predicate on the "focus_linguistico" field.
func FocusLinguisticoIn(vs ...string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldIn(FieldFocusLinguistico, vs...))
}

// FocusLinguisticoNotIn applies the NotIn predicate on the "focus_linguistico" field.
func FocusLinguisticoNotIn(vs ...string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldNotIn(FieldFocusLinguistico, vs...))
}

// FocusLinguisticoGT applies the GT predicate on the "focus_linguistico" field.
func FocusLinguisticoGT(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldGT(FieldFocusLinguistico, v))
}

// FocusLinguisticoGTE applies the GTE predicate on the "focus_linguistico" field.
func FocusLinguisticoGTE(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldGTE(FieldFocusLinguistico, v))
}

// FocusLinguisticoLT applies the LT predicate on the "focus_linguistico" field.
func FocusLinguisticoLT(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldLT(FieldFocusLinguistico, v))
}

// FocusLinguisticoLTE applies the LTE predicate on the "focus_linguistico" field.
func FocusLinguisticoLTE(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldLTE(FieldFocusLinguistico, v))
}

// FocusLinguisticoContains applies the Contains predicate on the "focus_linguistico" field.
func FocusLinguisticoContains(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldContains(FieldFocusLinguistico, v))
}

// FocusLinguisticoHasPrefix applies the HasPrefix predicate on the "focus_linguistico" field.
func FocusLinguisticoHasPrefix(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldHasPrefix(FieldFocusLinguistico, v))
}

// FocusLinguisticoHasSuffix applies the HasSuffix predicate on the "focus_linguistico" field.
func FocusLinguisticoHasSuffix(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldHasSuffix(FieldFocusLinguistico, v))
}

// FocusLinguisticoEqualFold applies the EqualFold predicate on the "focus_linguistico" field.
func FocusLinguisticoEqualFold(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEqualFold(FieldFocusLinguistico, v))
}

// FocusLinguisticoContainsFold applies the ContainsFold predicate on the "focus_linguistico" field.
func FocusLinguisticoContainsFold(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldContainsFold(FieldFocusLinguistico, v))
}

// RegolaChiaveEQ applies the EQ predicate on the "regola_chiave" field.
func RegolaChiaveEQ(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEQ(FieldRegolaChiave, v))
}

// RegolaChiaveNEQ applies the NEQ predicate on the "regola_chiave" field.
func RegolaChiaveNEQ(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldNEQ(FieldRegolaChiave, v))
}

// RegolaChiaveIn applies the In predicate on the "regola_chiave" field.
func RegolaChiaveIn(vs ...string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldIn(FieldRegolaChiave, vs...))
}

// RegolaChiaveNotIn applies the NotIn predicate on the "regola_chiave" field.
func RegolaChiaveNotIn(vs ...string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldNotIn(FieldRegolaChiave, vs...))
}

// RegolaChiaveGT applies the GT predicate on the "regola_chiave" field.
func RegolaChiaveGT(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldGT(FieldRegolaChiave, v))
}

// RegolaChiaveGTE applies the GTE predicate on the "regola_chiave" field.
func RegolaChiaveGTE(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldGTE(FieldRegolaChiave, v))
}

// RegolaChiaveLT applies the LT predicate on the "regola_chiave" field.
func RegolaChiaveLT(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldLT(FieldRegolaChiave, v))
}

// RegolaChiaveLTE applies the LTE predicate on the "regola_chiave" field.
func RegolaChiaveLTE(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldLTE(FieldRegolaChiave, v))
}

// RegolaChiaveContains applies the Contains predicate on the "regola_chiave" field.
func RegolaChiaveContains(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldContains(FieldRegolaChiave, v))
}

// RegolaChiaveHasPrefix applies the HasPrefix predicate on the "regola_chiave" field.
func RegolaChiaveHasPrefix(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldHasPrefix(FieldRegolaChiave, v))
}

// RegolaChiaveHasSuffix applies the HasSuffix predicate on the "regola_chiave" field.
func RegolaChiaveHasSuffix(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldHasSuffix(FieldRegolaChiave, v))
}

// RegolaChiaveEqualFold applies the EqualFold predicate on the "regola_chiave" field.
func RegolaChiaveEqualFold(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldEqualFold(FieldRegolaChiave, v))
}

// RegolaChiaveContainsFold applies the ContainsFold predicate on the "regola_chiave" field.
func RegolaChiaveContainsFold(v string) predicate.Spiegazione {
	return predicate.Spiegazione(sql.FieldContainsFold(FieldRegolaChiave, v))
}

// HasDomanda applies the HasEdge predicate on the "domanda" edge.
func HasDomanda() predicate.Spiegazione {
	return predicate.Spiegazione(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DomandaTable, DomandaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDomandaWith applies the HasEdge predicate on the "domanda" edge with a given conditions (other predicates).
func HasDomandaWith(preds ...predicate.Domanda) predicate.Spiegazione {
	return predicate.Spiegazione(func(s *sql.Selector) {
		step := newDomandaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Spiegazione) predicate.Spiegazione {
	return predicate.Spiegazione(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Spiegazione) predicate.Spiegazione {
	return predicate.Spiegazione(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Spiegazione) predicate.Spiegazione {
	return predicate.Spiegazione(sql.NotPredicates(p))
}
