// Code generated by ent, DO NOT EDIT.

package attivitaquesitoesame

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ed-evo/hankinson/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldLTE(FieldID, id))
}

// RispostaData applies equality check predicate on the "risposta_data" field. It's identical to RispostaDataEQ.
func RispostaData(v bool) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldEQ(FieldRispostaData, v))
}

// Inizio applies equality check predicate on the "inizio" field. It's identical to InizioEQ.
func Inizio(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldEQ(FieldInizio, v))
}

// Fine applies equality check predicate on the "fine" field. It's identical to FineEQ.
func Fine(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldEQ(FieldFine, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldEQ(FieldTimestamp, v))
}

// TipoEQ applies the EQ predicate on the "tipo" field.
func TipoEQ(v Tipo) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldEQ(FieldTipo, v))
}

// TipoNEQ applies the NEQ predicate on the "tipo" field.
func TipoNEQ(v Tipo) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNEQ(FieldTipo, v))
}

// TipoIn applies the In predicate on the "tipo" field.
func TipoIn(vs ...Tipo) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldIn(FieldTipo, vs...))
}

// TipoNotIn applies the NotIn predicate on the "tipo" field.
func TipoNotIn(vs ...Tipo) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNotIn(FieldTipo, vs...))
}

// RispostaDataEQ applies the EQ predicate on the "risposta_data" field.
func RispostaDataEQ(v bool) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldEQ(FieldRispostaData, v))
}

// RispostaDataNEQ applies the NEQ predicate on the "risposta_data" field.
func RispostaDataNEQ(v bool) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNEQ(FieldRispostaData, v))
}

// RispostaDataIsNil applies the IsNil predicate on the "risposta_data" field.
func RispostaDataIsNil() predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldIsNull(FieldRispostaData))
}

// RispostaDataNotNil applies the NotNil predicate on the "risposta_data" field.
func RispostaDataNotNil() predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNotNull(FieldRispostaData))
}

// InizioEQ applies the EQ predicate on the "inizio" field.
func InizioEQ(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldEQ(FieldInizio, v))
}

// InizioNEQ applies the NEQ predicate on the "inizio" field.
func InizioNEQ(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNEQ(FieldInizio, v))
}

// InizioIn applies the In predicate on the "inizio" field.
func InizioIn(vs ...time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldIn(FieldInizio, vs...))
}

// InizioNotIn applies the NotIn predicate on the "inizio" field.
func InizioNotIn(vs ...time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNotIn(FieldInizio, vs...))
}

// InizioGT applies the GT predicate on the "inizio" field.
func InizioGT(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldGT(FieldInizio, v))
}

// InizioGTE applies the GTE predicate on the "inizio" field.
func InizioGTE(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldGTE(FieldInizio, v))
}

// InizioLT applies the LT predicate on the "inizio" field.
func InizioLT(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldLT(FieldInizio, v))
}

// InizioLTE applies the LTE predicate on the "inizio" field.
func InizioLTE(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldLTE(FieldInizio, v))
}

// FineEQ applies the EQ predicate on the "fine" field.
func FineEQ(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldEQ(FieldFine, v))
}

// FineNEQ applies the NEQ predicate on the "fine" field.
func FineNEQ(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNEQ(FieldFine, v))
}

// FineIn applies the In predicate on the "fine" field.
func FineIn(vs ...time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldIn(FieldFine, vs...))
}

// FineNotIn applies the NotIn predicate on the "fine" field.
func FineNotIn(vs ...time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNotIn(FieldFine, vs...))
}

// FineGT applies the GT predicate on the "fine" field.
func FineGT(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldGT(FieldFine, v))
}

// FineGTE applies the GTE predicate on the "fine" field.
func FineGTE(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldGTE(FieldFine, v))
}

// FineLT applies the LT predicate on the "fine" field.
func FineLT(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldLT(FieldFine, v))
}

// FineLTE applies the LTE predicate on the "fine" field.
func FineLTE(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldLTE(FieldFine, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.FieldLTE(FieldTimestamp, v))
}

// HasQuesitoEsame applies the HasEdge predicate on the "quesito_esame" edge.
func HasQuesitoEsame() predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, QuesitoEsameTable, QuesitoEsameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuesitoEsameWith applies the HasEdge predicate on the "quesito_esame" edge with a given conditions (other predicates).
func HasQuesitoEsameWith(preds ...predicate.QuesitoEsame) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(func(s *sql.Selector) {
		step := newQuesitoEsameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AttivitaQuesitoEsame) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AttivitaQuesitoEsame) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AttivitaQuesitoEsame) predicate.AttivitaQuesitoEsame {
	return predicate.AttivitaQuesitoEsame(sql.NotPredicates(p))
}
