// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArgomentiColumns holds the columns for the "argomenti" table.
	ArgomentiColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt},
		{Name: "nome", Type: field.TypeString, Unique: true},
	}
	// ArgomentiTable holds the schema information for the "argomenti" table.
	ArgomentiTable = &schema.Table{
		Name:       "argomenti",
		Columns:    ArgomentiColumns,
		PrimaryKey: []*schema.Column{ArgomentiColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "argomento_nome",
				Unique:  false,
				Columns: []*schema.Column{ArgomentiColumns[1]},
			},
		},
	}
	// AttivitaQuesitoEsameColumns holds the columns for the "attivita_quesito_esame" table.
	AttivitaQuesitoEsameColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tipo", Type: field.TypeEnum, Enums: []string{"salta", "risposta", "pausa", "noop"}},
		{Name: "risposta_data", Type: field.TypeBool, Nullable: true},
		{Name: "inizio", Type: field.TypeTime},
		{Name: "fine", Type: field.TypeTime},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "quesito_esame_logs", Type: field.TypeInt},
	}
	// AttivitaQuesitoEsameTable holds the schema information for the "attivita_quesito_esame" table.
	AttivitaQuesitoEsameTable = &schema.Table{
		Name:       "attivita_quesito_esame",
		Columns:    AttivitaQuesitoEsameColumns,
		PrimaryKey: []*schema.Column{AttivitaQuesitoEsameColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attivita_quesito_esame_quesiti_esame_logs",
				Columns:    []*schema.Column{AttivitaQuesitoEsameColumns[6]},
				RefColumns: []*schema.Column{QuesitiEsameColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CapitoliColumns holds the columns for the "capitoli" table.
	CapitoliColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt},
		{Name: "nome", Type: field.TypeString},
		{Name: "min_numero_domanda", Type: field.TypeInt},
		{Name: "max_numero_domanda", Type: field.TypeInt},
		{Name: "totale_domande", Type: field.TypeInt},
	}
	// CapitoliTable holds the schema information for the "capitoli" table.
	CapitoliTable = &schema.Table{
		Name:       "capitoli",
		Columns:    CapitoliColumns,
		PrimaryKey: []*schema.Column{CapitoliColumns[0]},
	}
	// DomandeColumns holds the columns for the "domande" table.
	DomandeColumns = []*schema.Column{
		{Name: "numero", Type: field.TypeInt},
		{Name: "testo", Type: field.TypeString, Size: 2147483647},
		{Name: "is_true", Type: field.TypeBool},
		{Name: "immagine", Type: field.TypeString, Nullable: true},
		{Name: "pagina_quiz", Type: field.TypeInt},
		{Name: "id_blocco", Type: field.TypeInt},
		{Name: "id_capitolo", Type: field.TypeInt},
	}
	// DomandeTable holds the schema information for the "domande" table.
	DomandeTable = &schema.Table{
		Name:       "domande",
		Columns:    DomandeColumns,
		PrimaryKey: []*schema.Column{DomandeColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "domande_capitoli_domande",
				Columns:    []*schema.Column{DomandeColumns[6]},
				RefColumns: []*schema.Column{CapitoliColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "domanda_id_capitolo",
				Unique:  false,
				Columns: []*schema.Column{DomandeColumns[6]},
			},
			{
				Name:    "domanda_is_true",
				Unique:  false,
				Columns: []*schema.Column{DomandeColumns[2]},
			},
			{
				Name:    "domanda_id_blocco",
				Unique:  false,
				Columns: []*schema.Column{DomandeColumns[5]},
			},
			{
				Name:    "domanda_pagina_quiz",
				Unique:  false,
				Columns: []*schema.Column{DomandeColumns[4]},
			},
		},
	}
	// EsamiColumns holds the columns for the "esami" table.
	EsamiColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tipo", Type: field.TypeEnum, Enums: []string{"ministeriale", "parziale", "aperto"}},
		{Name: "numero_quesiti", Type: field.TypeInt},
		{Name: "max_errori", Type: field.TypeInt, Default: 3},
		{Name: "minuti_disponibili", Type: field.TypeInt, Default: 30},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "esame_utente", Type: field.TypeString},
	}
	// EsamiTable holds the schema information for the "esami" table.
	EsamiTable = &schema.Table{
		Name:       "esami",
		Columns:    EsamiColumns,
		PrimaryKey: []*schema.Column{EsamiColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "esami_utenti_utente",
				Columns:    []*schema.Column{EsamiColumns[7]},
				RefColumns: []*schema.Column{UtentiColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "esame_tipo_esame_utente",
				Unique:  true,
				Columns: []*schema.Column{EsamiColumns[1], EsamiColumns[7]},
				Annotation: &entsql.IndexAnnotation{
					Where: "tipo = 'aperto'",
				},
			},
		},
	}
	// QuesitiEsameColumns holds the columns for the "quesiti_esame" table.
	QuesitiEsameColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "risposta_finale", Type: field.TypeBool, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "esame_quesiti", Type: field.TypeInt},
		{Name: "quesito_esame_domanda_originale", Type: field.TypeInt},
	}
	// QuesitiEsameTable holds the schema information for the "quesiti_esame" table.
	QuesitiEsameTable = &schema.Table{
		Name:       "quesiti_esame",
		Columns:    QuesitiEsameColumns,
		PrimaryKey: []*schema.Column{QuesitiEsameColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "quesiti_esame_esami_quesiti",
				Columns:    []*schema.Column{QuesitiEsameColumns[4]},
				RefColumns: []*schema.Column{EsamiColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "quesiti_esame_domande_domanda_originale",
				Columns:    []*schema.Column{QuesitiEsameColumns[5]},
				RefColumns: []*schema.Column{DomandeColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SeedsColumns holds the columns for the "seeds" table.
	SeedsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hash", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SeedsTable holds the schema information for the "seeds" table.
	SeedsTable = &schema.Table{
		Name:       "seeds",
		Columns:    SeedsColumns,
		PrimaryKey: []*schema.Column{SeedsColumns[0]},
	}
	// UtentiColumns holds the columns for the "utenti" table.
	UtentiColumns = []*schema.Column{
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UtentiTable holds the schema information for the "utenti" table.
	UtentiTable = &schema.Table{
		Name:       "utenti",
		Columns:    UtentiColumns,
		PrimaryKey: []*schema.Column{UtentiColumns[0]},
	}
	// ArgomentiDomandeColumns holds the columns for the "argomenti_domande" table.
	ArgomentiDomandeColumns = []*schema.Column{
		{Name: "argomento_id", Type: field.TypeInt},
		{Name: "domanda_id", Type: field.TypeInt},
	}
	// ArgomentiDomandeTable holds the schema information for the "argomenti_domande" table.
	ArgomentiDomandeTable = &schema.Table{
		Name:       "argomenti_domande",
		Columns:    ArgomentiDomandeColumns,
		PrimaryKey: []*schema.Column{ArgomentiDomandeColumns[0], ArgomentiDomandeColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "argomenti_domande_argomento_id",
				Columns:    []*schema.Column{ArgomentiDomandeColumns[0]},
				RefColumns: []*schema.Column{ArgomentiColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "argomenti_domande_domanda_id",
				Columns:    []*schema.Column{ArgomentiDomandeColumns[1]},
				RefColumns: []*schema.Column{DomandeColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArgomentiTable,
		AttivitaQuesitoEsameTable,
		CapitoliTable,
		DomandeTable,
		EsamiTable,
		QuesitiEsameTable,
		SeedsTable,
		UtentiTable,
		ArgomentiDomandeTable,
	}
)

func init() {
	ArgomentiTable.Annotation = &entsql.Annotation{
		Table: "argomenti",
	}
	AttivitaQuesitoEsameTable.ForeignKeys[0].RefTable = QuesitiEsameTable
	AttivitaQuesitoEsameTable.Annotation = &entsql.Annotation{
		Table: "attivita_quesito_esame",
	}
	CapitoliTable.Annotation = &entsql.Annotation{
		Table: "capitoli",
	}
	DomandeTable.ForeignKeys[0].RefTable = CapitoliTable
	DomandeTable.Annotation = &entsql.Annotation{
		Table: "domande",
	}
	EsamiTable.ForeignKeys[0].RefTable = UtentiTable
	EsamiTable.Annotation = &entsql.Annotation{
		Table: "esami",
	}
	QuesitiEsameTable.ForeignKeys[0].RefTable = EsamiTable
	QuesitiEsameTable.ForeignKeys[1].RefTable = DomandeTable
	QuesitiEsameTable.Annotation = &entsql.Annotation{
		Table: "quesiti_esame",
	}
	UtentiTable.Annotation = &entsql.Annotation{
		Table: "utenti",
	}
	ArgomentiDomandeTable.ForeignKeys[0].RefTable = ArgomentiTable
	ArgomentiDomandeTable.ForeignKeys[1].RefTable = DomandeTable
}
