// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArgomentiColumns holds the columns for the "argomenti" table.
	ArgomentiColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt},
		{Name: "nome", Type: field.TypeString, Unique: true},
	}
	// ArgomentiTable holds the schema information for the "argomenti" table.
	ArgomentiTable = &schema.Table{
		Name:       "argomenti",
		Columns:    ArgomentiColumns,
		PrimaryKey: []*schema.Column{ArgomentiColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "argomento_nome",
				Unique:  false,
				Columns: []*schema.Column{ArgomentiColumns[1]},
			},
		},
	}
	// DomandeColumns holds the columns for the "domande" table.
	DomandeColumns = []*schema.Column{
		{Name: "numero", Type: field.TypeInt},
		{Name: "testo", Type: field.TypeString, Size: 2147483647},
		{Name: "is_true", Type: field.TypeBool},
		{Name: "immagine", Type: field.TypeString, Nullable: true},
		{Name: "pagina_quiz", Type: field.TypeInt},
		{Name: "id_blocco", Type: field.TypeInt},
	}
	// DomandeTable holds the schema information for the "domande" table.
	DomandeTable = &schema.Table{
		Name:       "domande",
		Columns:    DomandeColumns,
		PrimaryKey: []*schema.Column{DomandeColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "domanda_is_true",
				Unique:  false,
				Columns: []*schema.Column{DomandeColumns[2]},
			},
			{
				Name:    "domanda_id_blocco",
				Unique:  false,
				Columns: []*schema.Column{DomandeColumns[5]},
			},
			{
				Name:    "domanda_pagina_quiz",
				Unique:  false,
				Columns: []*schema.Column{DomandeColumns[4]},
			},
		},
	}
	// ArgomentiDomandeColumns holds the columns for the "argomenti_domande" table.
	ArgomentiDomandeColumns = []*schema.Column{
		{Name: "argomento_id", Type: field.TypeInt},
		{Name: "domanda_id", Type: field.TypeInt},
	}
	// ArgomentiDomandeTable holds the schema information for the "argomenti_domande" table.
	ArgomentiDomandeTable = &schema.Table{
		Name:       "argomenti_domande",
		Columns:    ArgomentiDomandeColumns,
		PrimaryKey: []*schema.Column{ArgomentiDomandeColumns[0], ArgomentiDomandeColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "argomenti_domande_argomento_id",
				Columns:    []*schema.Column{ArgomentiDomandeColumns[0]},
				RefColumns: []*schema.Column{ArgomentiColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "argomenti_domande_domanda_id",
				Columns:    []*schema.Column{ArgomentiDomandeColumns[1]},
				RefColumns: []*schema.Column{DomandeColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArgomentiTable,
		DomandeTable,
		ArgomentiDomandeTable,
	}
)

func init() {
	ArgomentiTable.Annotation = &entsql.Annotation{
		Table: "argomenti",
	}
	DomandeTable.Annotation = &entsql.Annotation{
		Table: "domande",
	}
	ArgomentiDomandeTable.ForeignKeys[0].RefTable = ArgomentiTable
	ArgomentiDomandeTable.ForeignKeys[1].RefTable = DomandeTable
}
