// Code generated by ent, DO NOT EDIT.

package correzione

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the correzione type in the database.
	Label = "correzione"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEsameID holds the string denoting the esame_id field in the database.
	FieldEsameID = "esame_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldEsaminatore holds the string denoting the esaminatore field in the database.
	FieldEsaminatore = "esaminatore"
	// FieldIsPromosso holds the string denoting the is_promosso field in the database.
	FieldIsPromosso = "is_promosso"
	// FieldTesto holds the string denoting the testo field in the database.
	FieldTesto = "testo"
	// FieldMeta holds the string denoting the meta field in the database.
	FieldMeta = "meta"
	// EdgeEsame holds the string denoting the esame edge name in mutations.
	EdgeEsame = "esame"
	// Table holds the table name of the correzione in the database.
	Table = "correzioni"
	// EsameTable is the table that holds the esame relation/edge.
	EsameTable = "correzioni"
	// EsameInverseTable is the table name for the Esame entity.
	// It exists in this package in order to avoid circular dependency with the "esame" package.
	EsameInverseTable = "esami"
	// EsameColumn is the table column denoting the esame relation/edge.
	EsameColumn = "esame_id"
)

// Columns holds all SQL columns for correzione fields.
var Columns = []string{
	FieldID,
	FieldEsameID,
	FieldType,
	FieldEsaminatore,
	FieldIsPromosso,
	FieldTesto,
	FieldMeta,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeHuman Type = "human"
	TypeAi    Type = "ai"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeHuman, TypeAi:
		return nil
	default:
		return fmt.Errorf("correzione: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Correzione queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEsameID orders the results by the esame_id field.
func ByEsameID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEsameID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByEsaminatore orders the results by the esaminatore field.
func ByEsaminatore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEsaminatore, opts...).ToFunc()
}

// ByIsPromosso orders the results by the is_promosso field.
func ByIsPromosso(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPromosso, opts...).ToFunc()
}

// ByTesto orders the results by the testo field.
func ByTesto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTesto, opts...).ToFunc()
}

// ByMeta orders the results by the meta field.
func ByMeta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeta, opts...).ToFunc()
}

// ByEsameField orders the results by esame field.
func ByEsameField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEsameStep(), sql.OrderByField(field, opts...))
	}
}
func newEsameStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EsameInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EsameTable, EsameColumn),
	)
}
