// Code generated by ent, DO NOT EDIT.

package correzione

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ed-evo/hankinson/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Correzione {
	return predicate.Correzione(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Correzione {
	return predicate.Correzione(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Correzione {
	return predicate.Correzione(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Correzione {
	return predicate.Correzione(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Correzione {
	return predicate.Correzione(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Correzione {
	return predicate.Correzione(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Correzione {
	return predicate.Correzione(sql.FieldLTE(FieldID, id))
}

// EsameID applies equality check predicate on the "esame_id" field. It's identical to EsameIDEQ.
func EsameID(v int) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldEsameID, v))
}

// Esaminatore applies equality check predicate on the "esaminatore" field. It's identical to EsaminatoreEQ.
func Esaminatore(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldEsaminatore, v))
}

// IsPromosso applies equality check predicate on the "is_promosso" field. It's identical to IsPromossoEQ.
func IsPromosso(v bool) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldIsPromosso, v))
}

// Testo applies equality check predicate on the "testo" field. It's identical to TestoEQ.
func Testo(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldTesto, v))
}

// Meta applies equality check predicate on the "meta" field. It's identical to MetaEQ.
func Meta(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldMeta, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldCreatedAt, v))
}

// EsameIDEQ applies the EQ predicate on the "esame_id" field.
func EsameIDEQ(v int) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldEsameID, v))
}

// EsameIDNEQ applies the NEQ predicate on the "esame_id" field.
func EsameIDNEQ(v int) predicate.Correzione {
	return predicate.Correzione(sql.FieldNEQ(FieldEsameID, v))
}

// EsameIDIn applies the In predicate on the "esame_id" field.
func EsameIDIn(vs ...int) predicate.Correzione {
	return predicate.Correzione(sql.FieldIn(FieldEsameID, vs...))
}

// EsameIDNotIn applies the NotIn predicate on the "esame_id" field.
func EsameIDNotIn(vs ...int) predicate.Correzione {
	return predicate.Correzione(sql.FieldNotIn(FieldEsameID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Correzione {
	return predicate.Correzione(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Correzione {
	return predicate.Correzione(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Correzione {
	return predicate.Correzione(sql.FieldNotIn(FieldType, vs...))
}

// EsaminatoreEQ applies the EQ predicate on the "esaminatore" field.
func EsaminatoreEQ(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldEsaminatore, v))
}

// EsaminatoreNEQ applies the NEQ predicate on the "esaminatore" field.
func EsaminatoreNEQ(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldNEQ(FieldEsaminatore, v))
}

// EsaminatoreIn applies the In predicate on the "esaminatore" field.
func EsaminatoreIn(vs ...string) predicate.Correzione {
	return predicate.Correzione(sql.FieldIn(FieldEsaminatore, vs...))
}

// EsaminatoreNotIn applies the NotIn predicate on the "esaminatore" field.
func EsaminatoreNotIn(vs ...string) predicate.Correzione {
	return predicate.Correzione(sql.FieldNotIn(FieldEsaminatore, vs...))
}

// EsaminatoreGT applies the GT predicate on the "esaminatore" field.
func EsaminatoreGT(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldGT(FieldEsaminatore, v))
}

// EsaminatoreGTE applies the GTE predicate on the "esaminatore" field.
func EsaminatoreGTE(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldGTE(FieldEsaminatore, v))
}

// EsaminatoreLT applies the LT predicate on the "esaminatore" field.
func EsaminatoreLT(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldLT(FieldEsaminatore, v))
}

// EsaminatoreLTE applies the LTE predicate on the "esaminatore" field.
func EsaminatoreLTE(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldLTE(FieldEsaminatore, v))
}

// EsaminatoreContains applies the Contains predicate on the "esaminatore" field.
func EsaminatoreContains(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldContains(FieldEsaminatore, v))
}

// EsaminatoreHasPrefix applies the HasPrefix predicate on the "esaminatore" field.
func EsaminatoreHasPrefix(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldHasPrefix(FieldEsaminatore, v))
}

// EsaminatoreHasSuffix applies the HasSuffix predicate on the "esaminatore" field.
func EsaminatoreHasSuffix(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldHasSuffix(FieldEsaminatore, v))
}

// EsaminatoreEqualFold applies the EqualFold predicate on the "esaminatore" field.
func EsaminatoreEqualFold(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldEqualFold(FieldEsaminatore, v))
}

// EsaminatoreContainsFold applies the ContainsFold predicate on the "esaminatore" field.
func EsaminatoreContainsFold(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldContainsFold(FieldEsaminatore, v))
}

// IsPromossoEQ applies the EQ predicate on the "is_promosso" field.
func IsPromossoEQ(v bool) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldIsPromosso, v))
}

// IsPromossoNEQ applies the NEQ predicate on the "is_promosso" field.
func IsPromossoNEQ(v bool) predicate.Correzione {
	return predicate.Correzione(sql.FieldNEQ(FieldIsPromosso, v))
}

// TestoEQ applies the EQ predicate on the "testo" field.
func TestoEQ(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldTesto, v))
}

// TestoNEQ applies the NEQ predicate on the "testo" field.
func TestoNEQ(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldNEQ(FieldTesto, v))
}

// TestoIn applies the In predicate on the "testo" field.
func TestoIn(vs ...string) predicate.Correzione {
	return predicate.Correzione(sql.FieldIn(FieldTesto, vs...))
}

// TestoNotIn applies the NotIn predicate on the "testo" field.
func TestoNotIn(vs ...string) predicate.Correzione {
	return predicate.Correzione(sql.FieldNotIn(FieldTesto, vs...))
}

// TestoGT applies the GT predicate on the "testo" field.
func TestoGT(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldGT(FieldTesto, v))
}

// TestoGTE applies the GTE predicate on the "testo" field.
func TestoGTE(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldGTE(FieldTesto, v))
}

// TestoLT applies the LT predicate on the "testo" field.
func TestoLT(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldLT(FieldTesto, v))
}

// TestoLTE applies the LTE predicate on the "testo" field.
func TestoLTE(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldLTE(FieldTesto, v))
}

// TestoContains applies the Contains predicate on the "testo" field.
func TestoContains(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldContains(FieldTesto, v))
}

// TestoHasPrefix applies the HasPrefix predicate on the "testo" field.
func TestoHasPrefix(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldHasPrefix(FieldTesto, v))
}

// TestoHasSuffix applies the HasSuffix predicate on the "testo" field.
func TestoHasSuffix(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldHasSuffix(FieldTesto, v))
}

// TestoEqualFold applies the EqualFold predicate on the "testo" field.
func TestoEqualFold(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldEqualFold(FieldTesto, v))
}

// TestoContainsFold applies the ContainsFold predicate on the "testo" field.
func TestoContainsFold(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldContainsFold(FieldTesto, v))
}

// MetaEQ applies the EQ predicate on the "meta" field.
func MetaEQ(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldMeta, v))
}

// MetaNEQ applies the NEQ predicate on the "meta" field.
func MetaNEQ(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldNEQ(FieldMeta, v))
}

// MetaIn applies the In predicate on the "meta" field.
func MetaIn(vs ...string) predicate.Correzione {
	return predicate.Correzione(sql.FieldIn(FieldMeta, vs...))
}

// MetaNotIn applies the NotIn predicate on the "meta" field.
func MetaNotIn(vs ...string) predicate.Correzione {
	return predicate.Correzione(sql.FieldNotIn(FieldMeta, vs...))
}

// MetaGT applies the GT predicate on the "meta" field.
func MetaGT(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldGT(FieldMeta, v))
}

// MetaGTE applies the GTE predicate on the "meta" field.
func MetaGTE(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldGTE(FieldMeta, v))
}

// MetaLT applies the LT predicate on the "meta" field.
func MetaLT(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldLT(FieldMeta, v))
}

// MetaLTE applies the LTE predicate on the "meta" field.
func MetaLTE(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldLTE(FieldMeta, v))
}

// MetaContains applies the Contains predicate on the "meta" field.
func MetaContains(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldContains(FieldMeta, v))
}

// MetaHasPrefix applies the HasPrefix predicate on the "meta" field.
func MetaHasPrefix(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldHasPrefix(FieldMeta, v))
}

// MetaHasSuffix applies the HasSuffix predicate on the "meta" field.
func MetaHasSuffix(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldHasSuffix(FieldMeta, v))
}

// MetaIsNil applies the IsNil predicate on the "meta" field.
func MetaIsNil() predicate.Correzione {
	return predicate.Correzione(sql.FieldIsNull(FieldMeta))
}

// MetaNotNil applies the NotNil predicate on the "meta" field.
func MetaNotNil() predicate.Correzione {
	return predicate.Correzione(sql.FieldNotNull(FieldMeta))
}

// MetaEqualFold applies the EqualFold predicate on the "meta" field.
func MetaEqualFold(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldEqualFold(FieldMeta, v))
}

// MetaContainsFold applies the ContainsFold predicate on the "meta" field.
func MetaContainsFold(v string) predicate.Correzione {
	return predicate.Correzione(sql.FieldContainsFold(FieldMeta, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Correzione {
	return predicate.Correzione(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Correzione {
	return predicate.Correzione(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Correzione {
	return predicate.Correzione(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Correzione {
	return predicate.Correzione(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Correzione {
	return predicate.Correzione(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Correzione {
	return predicate.Correzione(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Correzione {
	return predicate.Correzione(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Correzione {
	return predicate.Correzione(sql.FieldLTE(FieldCreatedAt, v))
}

// HasEsame applies the HasEdge predicate on the "esame" edge.
func HasEsame() predicate.Correzione {
	return predicate.Correzione(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EsameTable, EsameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEsameWith applies the HasEdge predicate on the "esame" edge with a given conditions (other predicates).
func HasEsameWith(preds ...predicate.Esame) predicate.Correzione {
	return predicate.Correzione(func(s *sql.Selector) {
		step := newEsameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Correzione) predicate.Correzione {
	return predicate.Correzione(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Correzione) predicate.Correzione {
	return predicate.Correzione(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Correzione) predicate.Correzione {
	return predicate.Correzione(sql.NotPredicates(p))
}
