// Code generated by ent, DO NOT EDIT.

package quesitoesame

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the quesitoesame type in the database.
	Label = "quesito_esame"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRispostaFinale holds the string denoting the risposta_finale field in the database.
	FieldRispostaFinale = "risposta_finale"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeEsame holds the string denoting the esame edge name in mutations.
	EdgeEsame = "esame"
	// EdgeDomandaOriginale holds the string denoting the domanda_originale edge name in mutations.
	EdgeDomandaOriginale = "domanda_originale"
	// EdgeAttivita holds the string denoting the attivita edge name in mutations.
	EdgeAttivita = "attivita"
	// DomandaFieldID holds the string denoting the ID field of the Domanda.
	DomandaFieldID = "numero"
	// Table holds the table name of the quesitoesame in the database.
	Table = "quesiti_esame"
	// EsameTable is the table that holds the esame relation/edge.
	EsameTable = "quesiti_esame"
	// EsameInverseTable is the table name for the Esame entity.
	// It exists in this package in order to avoid circular dependency with the "esame" package.
	EsameInverseTable = "esami"
	// EsameColumn is the table column denoting the esame relation/edge.
	EsameColumn = "esame_quesiti"
	// DomandaOriginaleTable is the table that holds the domanda_originale relation/edge.
	DomandaOriginaleTable = "quesiti_esame"
	// DomandaOriginaleInverseTable is the table name for the Domanda entity.
	// It exists in this package in order to avoid circular dependency with the "domanda" package.
	DomandaOriginaleInverseTable = "domande"
	// DomandaOriginaleColumn is the table column denoting the domanda_originale relation/edge.
	DomandaOriginaleColumn = "quesito_esame_domanda_originale"
	// AttivitaTable is the table that holds the attivita relation/edge.
	AttivitaTable = "attivita_quesito_esame"
	// AttivitaInverseTable is the table name for the AttivitaQuesitoEsame entity.
	// It exists in this package in order to avoid circular dependency with the "attivitaquesitoesame" package.
	AttivitaInverseTable = "attivita_quesito_esame"
	// AttivitaColumn is the table column denoting the attivita relation/edge.
	AttivitaColumn = "quesito_esame_attivita"
)

// Columns holds all SQL columns for quesitoesame fields.
var Columns = []string{
	FieldID,
	FieldRispostaFinale,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "quesiti_esame"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"esame_quesiti",
	"quesito_esame_domanda_originale",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the QuesitoEsame queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRispostaFinale orders the results by the risposta_finale field.
func ByRispostaFinale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRispostaFinale, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEsameField orders the results by esame field.
func ByEsameField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEsameStep(), sql.OrderByField(field, opts...))
	}
}

// ByDomandaOriginaleField orders the results by domanda_originale field.
func ByDomandaOriginaleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDomandaOriginaleStep(), sql.OrderByField(field, opts...))
	}
}

// ByAttivitaCount orders the results by attivita count.
func ByAttivitaCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttivitaStep(), opts...)
	}
}

// ByAttivita orders the results by attivita terms.
func ByAttivita(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttivitaStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEsameStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EsameInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EsameTable, EsameColumn),
	)
}
func newDomandaOriginaleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DomandaOriginaleInverseTable, DomandaFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, DomandaOriginaleTable, DomandaOriginaleColumn),
	)
}
func newAttivitaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttivitaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttivitaTable, AttivitaColumn),
	)
}
