// Code generated by ent, DO NOT EDIT.

package quesitoesame

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ed-evo/hankinson/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldLTE(FieldID, id))
}

// RispostaFinale applies equality check predicate on the "risposta_finale" field. It's identical to RispostaFinaleEQ.
func RispostaFinale(v bool) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldEQ(FieldRispostaFinale, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldEQ(FieldUpdatedAt, v))
}

// RispostaFinaleEQ applies the EQ predicate on the "risposta_finale" field.
func RispostaFinaleEQ(v bool) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldEQ(FieldRispostaFinale, v))
}

// RispostaFinaleNEQ applies the NEQ predicate on the "risposta_finale" field.
func RispostaFinaleNEQ(v bool) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldNEQ(FieldRispostaFinale, v))
}

// RispostaFinaleIsNil applies the IsNil predicate on the "risposta_finale" field.
func RispostaFinaleIsNil() predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldIsNull(FieldRispostaFinale))
}

// RispostaFinaleNotNil applies the NotNil predicate on the "risposta_finale" field.
func RispostaFinaleNotNil() predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldNotNull(FieldRispostaFinale))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasEsame applies the HasEdge predicate on the "esame" edge.
func HasEsame() predicate.QuesitoEsame {
	return predicate.QuesitoEsame(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EsameTable, EsameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEsameWith applies the HasEdge predicate on the "esame" edge with a given conditions (other predicates).
func HasEsameWith(preds ...predicate.Esame) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(func(s *sql.Selector) {
		step := newEsameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDomandaOriginale applies the HasEdge predicate on the "domanda_originale" edge.
func HasDomandaOriginale() predicate.QuesitoEsame {
	return predicate.QuesitoEsame(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, DomandaOriginaleTable, DomandaOriginaleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDomandaOriginaleWith applies the HasEdge predicate on the "domanda_originale" edge with a given conditions (other predicates).
func HasDomandaOriginaleWith(preds ...predicate.Domanda) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(func(s *sql.Selector) {
		step := newDomandaOriginaleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttivita applies the HasEdge predicate on the "attivita" edge.
func HasAttivita() predicate.QuesitoEsame {
	return predicate.QuesitoEsame(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttivitaTable, AttivitaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttivitaWith applies the HasEdge predicate on the "attivita" edge with a given conditions (other predicates).
func HasAttivitaWith(preds ...predicate.AttivitaQuesitoEsame) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(func(s *sql.Selector) {
		step := newAttivitaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuesitoEsame) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuesitoEsame) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuesitoEsame) predicate.QuesitoEsame {
	return predicate.QuesitoEsame(sql.NotPredicates(p))
}
