// Code generated by ent, DO NOT EDIT.

package domanda

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ed-evo/hankinson/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Domanda {
	return predicate.Domanda(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Domanda {
	return predicate.Domanda(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Domanda {
	return predicate.Domanda(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Domanda {
	return predicate.Domanda(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Domanda {
	return predicate.Domanda(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Domanda {
	return predicate.Domanda(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Domanda {
	return predicate.Domanda(sql.FieldLTE(FieldID, id))
}

// Testo applies equality check predicate on the "testo" field. It's identical to TestoEQ.
func Testo(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldTesto, v))
}

// IsTrue applies equality check predicate on the "is_true" field. It's identical to IsTrueEQ.
func IsTrue(v bool) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldIsTrue, v))
}

// Immagine applies equality check predicate on the "immagine" field. It's identical to ImmagineEQ.
func Immagine(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldImmagine, v))
}

// PaginaQuiz applies equality check predicate on the "pagina_quiz" field. It's identical to PaginaQuizEQ.
func PaginaQuiz(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldPaginaQuiz, v))
}

// IDBlocco applies equality check predicate on the "id_blocco" field. It's identical to IDBloccoEQ.
func IDBlocco(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldIDBlocco, v))
}

// TestoEQ applies the EQ predicate on the "testo" field.
func TestoEQ(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldTesto, v))
}

// TestoNEQ applies the NEQ predicate on the "testo" field.
func TestoNEQ(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldNEQ(FieldTesto, v))
}

// TestoIn applies the In predicate on the "testo" field.
func TestoIn(vs ...string) predicate.Domanda {
	return predicate.Domanda(sql.FieldIn(FieldTesto, vs...))
}

// TestoNotIn applies the NotIn predicate on the "testo" field.
func TestoNotIn(vs ...string) predicate.Domanda {
	return predicate.Domanda(sql.FieldNotIn(FieldTesto, vs...))
}

// TestoGT applies the GT predicate on the "testo" field.
func TestoGT(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldGT(FieldTesto, v))
}

// TestoGTE applies the GTE predicate on the "testo" field.
func TestoGTE(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldGTE(FieldTesto, v))
}

// TestoLT applies the LT predicate on the "testo" field.
func TestoLT(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldLT(FieldTesto, v))
}

// TestoLTE applies the LTE predicate on the "testo" field.
func TestoLTE(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldLTE(FieldTesto, v))
}

// TestoContains applies the Contains predicate on the "testo" field.
func TestoContains(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldContains(FieldTesto, v))
}

// TestoHasPrefix applies the HasPrefix predicate on the "testo" field.
func TestoHasPrefix(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldHasPrefix(FieldTesto, v))
}

// TestoHasSuffix applies the HasSuffix predicate on the "testo" field.
func TestoHasSuffix(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldHasSuffix(FieldTesto, v))
}

// TestoEqualFold applies the EqualFold predicate on the "testo" field.
func TestoEqualFold(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldEqualFold(FieldTesto, v))
}

// TestoContainsFold applies the ContainsFold predicate on the "testo" field.
func TestoContainsFold(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldContainsFold(FieldTesto, v))
}

// IsTrueEQ applies the EQ predicate on the "is_true" field.
func IsTrueEQ(v bool) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldIsTrue, v))
}

// IsTrueNEQ applies the NEQ predicate on the "is_true" field.
func IsTrueNEQ(v bool) predicate.Domanda {
	return predicate.Domanda(sql.FieldNEQ(FieldIsTrue, v))
}

// ImmagineEQ applies the EQ predicate on the "immagine" field.
func ImmagineEQ(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldImmagine, v))
}

// ImmagineNEQ applies the NEQ predicate on the "immagine" field.
func ImmagineNEQ(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldNEQ(FieldImmagine, v))
}

// ImmagineIn applies the In predicate on the "immagine" field.
func ImmagineIn(vs ...string) predicate.Domanda {
	return predicate.Domanda(sql.FieldIn(FieldImmagine, vs...))
}

// ImmagineNotIn applies the NotIn predicate on the "immagine" field.
func ImmagineNotIn(vs ...string) predicate.Domanda {
	return predicate.Domanda(sql.FieldNotIn(FieldImmagine, vs...))
}

// ImmagineGT applies the GT predicate on the "immagine" field.
func ImmagineGT(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldGT(FieldImmagine, v))
}

// ImmagineGTE applies the GTE predicate on the "immagine" field.
func ImmagineGTE(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldGTE(FieldImmagine, v))
}

// ImmagineLT applies the LT predicate on the "immagine" field.
func ImmagineLT(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldLT(FieldImmagine, v))
}

// ImmagineLTE applies the LTE predicate on the "immagine" field.
func ImmagineLTE(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldLTE(FieldImmagine, v))
}

// ImmagineContains applies the Contains predicate on the "immagine" field.
func ImmagineContains(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldContains(FieldImmagine, v))
}

// ImmagineHasPrefix applies the HasPrefix predicate on the "immagine" field.
func ImmagineHasPrefix(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldHasPrefix(FieldImmagine, v))
}

// ImmagineHasSuffix applies the HasSuffix predicate on the "immagine" field.
func ImmagineHasSuffix(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldHasSuffix(FieldImmagine, v))
}

// ImmagineIsNil applies the IsNil predicate on the "immagine" field.
func ImmagineIsNil() predicate.Domanda {
	return predicate.Domanda(sql.FieldIsNull(FieldImmagine))
}

// ImmagineNotNil applies the NotNil predicate on the "immagine" field.
func ImmagineNotNil() predicate.Domanda {
	return predicate.Domanda(sql.FieldNotNull(FieldImmagine))
}

// ImmagineEqualFold applies the EqualFold predicate on the "immagine" field.
func ImmagineEqualFold(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldEqualFold(FieldImmagine, v))
}

// ImmagineContainsFold applies the ContainsFold predicate on the "immagine" field.
func ImmagineContainsFold(v string) predicate.Domanda {
	return predicate.Domanda(sql.FieldContainsFold(FieldImmagine, v))
}

// PaginaQuizEQ applies the EQ predicate on the "pagina_quiz" field.
func PaginaQuizEQ(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldPaginaQuiz, v))
}

// PaginaQuizNEQ applies the NEQ predicate on the "pagina_quiz" field.
func PaginaQuizNEQ(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldNEQ(FieldPaginaQuiz, v))
}

// PaginaQuizIn applies the In predicate on the "pagina_quiz" field.
func PaginaQuizIn(vs ...int) predicate.Domanda {
	return predicate.Domanda(sql.FieldIn(FieldPaginaQuiz, vs...))
}

// PaginaQuizNotIn applies the NotIn predicate on the "pagina_quiz" field.
func PaginaQuizNotIn(vs ...int) predicate.Domanda {
	return predicate.Domanda(sql.FieldNotIn(FieldPaginaQuiz, vs...))
}

// PaginaQuizGT applies the GT predicate on the "pagina_quiz" field.
func PaginaQuizGT(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldGT(FieldPaginaQuiz, v))
}

// PaginaQuizGTE applies the GTE predicate on the "pagina_quiz" field.
func PaginaQuizGTE(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldGTE(FieldPaginaQuiz, v))
}

// PaginaQuizLT applies the LT predicate on the "pagina_quiz" field.
func PaginaQuizLT(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldLT(FieldPaginaQuiz, v))
}

// PaginaQuizLTE applies the LTE predicate on the "pagina_quiz" field.
func PaginaQuizLTE(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldLTE(FieldPaginaQuiz, v))
}

// IDBloccoEQ applies the EQ predicate on the "id_blocco" field.
func IDBloccoEQ(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldEQ(FieldIDBlocco, v))
}

// IDBloccoNEQ applies the NEQ predicate on the "id_blocco" field.
func IDBloccoNEQ(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldNEQ(FieldIDBlocco, v))
}

// IDBloccoIn applies the In predicate on the "id_blocco" field.
func IDBloccoIn(vs ...int) predicate.Domanda {
	return predicate.Domanda(sql.FieldIn(FieldIDBlocco, vs...))
}

// IDBloccoNotIn applies the NotIn predicate on the "id_blocco" field.
func IDBloccoNotIn(vs ...int) predicate.Domanda {
	return predicate.Domanda(sql.FieldNotIn(FieldIDBlocco, vs...))
}

// IDBloccoGT applies the GT predicate on the "id_blocco" field.
func IDBloccoGT(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldGT(FieldIDBlocco, v))
}

// IDBloccoGTE applies the GTE predicate on the "id_blocco" field.
func IDBloccoGTE(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldGTE(FieldIDBlocco, v))
}

// IDBloccoLT applies the LT predicate on the "id_blocco" field.
func IDBloccoLT(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldLT(FieldIDBlocco, v))
}

// IDBloccoLTE applies the LTE predicate on the "id_blocco" field.
func IDBloccoLTE(v int) predicate.Domanda {
	return predicate.Domanda(sql.FieldLTE(FieldIDBlocco, v))
}

// HasArgomenti applies the HasEdge predicate on the "argomenti" edge.
func HasArgomenti() predicate.Domanda {
	return predicate.Domanda(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, ArgomentiTable, ArgomentiPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArgomentiWith applies the HasEdge predicate on the "argomenti" edge with a given conditions (other predicates).
func HasArgomentiWith(preds ...predicate.Argomento) predicate.Domanda {
	return predicate.Domanda(func(s *sql.Selector) {
		step := newArgomentiStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Domanda) predicate.Domanda {
	return predicate.Domanda(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Domanda) predicate.Domanda {
	return predicate.Domanda(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Domanda) predicate.Domanda {
	return predicate.Domanda(sql.NotPredicates(p))
}
